// <auto-generated />
using System.Runtime.CompilerServices;
using Gpui.Interop;

namespace Gpui.Interop
{
    internal enum ComponentId : ushort
    {
        Div = 1,
        Text = 2,
        Button = 3,
        Checkbox = 4,
        Radio = 5,
        Badge = 6,
        Divider = 7,
        Spacer = 8,
        Scroll = 9,
        List = 10,
        Image = 11,
        Input = 12,
        Overlay = 13,
        Tooltip = 14,
        ContextMenu = 15,
        PopoverMenu = 16,
        Table = 17,
        Slider = 18,
        Drawing = 19,
        Path = 20,
        Dynamic = 21,
        DockArea = 22,
        DockSplit = 23,
        DockTabs = 24,
        DockPanel = 25,
        DockRegion = 26,
    }

    internal enum OpCode : ushort
    {
        Flex = 1,
        VStack = 2,
        ItemsCenter = 3,
        JustifyCenter = 4,
        JustifyBetween = 5,
        FlexGrow = 6,
        GapPx = 100,
        PaddingPx = 101,
        WidthPx = 102,
        WidthPercent = 103,
        BackgroundRgba = 104,
        Checked = 105,
        HeightPx = 106,
        HeightPercent = 107,
        BorderRgba = 108,
        BorderWidthPx = 109,
        RadiusPx = 110,
        TextRgba = 111,
        FontSizePx = 112,
        HoverBackgroundRgba = 113,
        HoverTextRgba = 114,
        HoverBorderRgba = 115,
        ActiveBackgroundRgba = 116,
        ActiveTextRgba = 117,
        ActiveBorderRgba = 118,
        Disabled = 119,
        OnClick = 200,
        WindowControlArea = 201,
        ElementOwner = 202,
        ResourceOwner = 300,
        ScrollAxis = 301,
        SmoothScroll = 302,
        ShowScrollbar = 303,
        ListItemCount = 310,
        ListRenderer = 311,
        ListBatchSize = 312,
        ListOverdrawPx = 313,
        ListAlignment = 314,
        ListEstimatedItemHeightPx = 315,
        ListContentRevision = 316,
        ListItemId = 317,
        ImageObjectFit = 400,
        ImageGrayscale = 401,
        InputDisabled = 500,
        InputReadOnly = 501,
        InputPassword = 502,
        InputOnChanged = 503,
        InputOnSubmitted = 504,
        InputOnFocusChanged = 505,
        OverlayPlacement = 600,
        OverlayPriority = 601,
        OverlayMarginPx = 602,
        OverlayModal = 603,
        OverlayBackdropRgba = 604,
        OverlayDismissOnBackdrop = 605,
        OverlayDismissOnEscape = 606,
        OverlayOnDismiss = 607,
        TooltipPlacement = 610,
        TooltipAlignment = 611,
        TooltipShowDelayMs = 612,
        TooltipHideDelayMs = 613,
        TooltipGapPx = 614,
        TooltipMarginPx = 615,
        ContextMenuPriority = 620,
        ContextMenuMarginPx = 621,
        PopoverMenuPriority = 630,
        PopoverMenuMarginPx = 631,
        TableShowHeader = 318,
        TableCellColumn = 319,
        ScrollbarGutter = 320,
        ScrollbarWidth = 321,
        TableColumn = 322,
        SliderMin = 330,
        SliderMax = 331,
        SliderStep = 332,
        SliderAxis = 333,
        SliderDisabled = 334,
        SliderScale = 335,
        SliderValue = 336,
        SliderRangeStart = 337,
        SliderRangeEnd = 338,
        SliderOnChanged = 339,
        SliderOnReleased = 340,
        DockAxis = 350,
        DockActiveIndex = 351,
        DockInitialSizePx = 352,
        DockPanelClosable = 353,
        DockPanelZoomable = 354,
        DockPanelInnerPadding = 355,
        DockLocked = 356,
        DockRegionSide = 357,
        DockRegionOpen = 358,
        DockRegionCollapsible = 359,
        DrawingViewBoxOrigin = 700,
        DrawingViewBoxSize = 701,
        DynamicActive = 702,
        PathMoveTo = 710,
        PathLineTo = 711,
        PathQuadraticControl = 712,
        PathQuadraticTo = 713,
        PathCubicControlA = 714,
        PathCubicControlB = 715,
        PathCubicTo = 716,
        PathArcRadii = 717,
        PathArcRotation = 718,
        PathArcFlags = 719,
        PathArcTo = 720,
        PathClose = 721,
        PathFillRgba = 722,
        PathFillRule = 723,
        PathStrokeRgba = 724,
        PathStrokeWidthPx = 725,
        PathDashPx = 726,
        PathCircleCenter = 727,
        PathCircleRadius = 728,
    }

    internal enum ValueKind : ushort
    {
        None = 0,
        F32 = 1,
        U32 = 2,
        Callback = 3,
        U64 = 4,
        F32x2 = 5,
    }

    internal static class SemanticRegistry
    {
        internal const uint SchemaVersion = 1;
        internal const ulong SchemaHash = 0xB55E495914E16758UL;

        internal static bool IsKnownComponent(ComponentId component) => component switch
        {
            ComponentId.Div => true,
            ComponentId.Text => true,
            ComponentId.Button => true,
            ComponentId.Checkbox => true,
            ComponentId.Radio => true,
            ComponentId.Badge => true,
            ComponentId.Divider => true,
            ComponentId.Spacer => true,
            ComponentId.Scroll => true,
            ComponentId.List => true,
            ComponentId.Image => true,
            ComponentId.Input => true,
            ComponentId.Overlay => true,
            ComponentId.Tooltip => true,
            ComponentId.ContextMenu => true,
            ComponentId.PopoverMenu => true,
            ComponentId.Table => true,
            ComponentId.Slider => true,
            ComponentId.Drawing => true,
            ComponentId.Path => true,
            ComponentId.Dynamic => true,
            ComponentId.DockArea => true,
            ComponentId.DockSplit => true,
            ComponentId.DockTabs => true,
            ComponentId.DockPanel => true,
            ComponentId.DockRegion => true,
            _ => false,
        };

        internal static bool IsDataRequired(ComponentId component) => component switch
        {
            ComponentId.Button => true,
            ComponentId.Checkbox => true,
            ComponentId.Radio => true,
            ComponentId.Scroll => true,
            ComponentId.List => true,
            ComponentId.Image => true,
            ComponentId.Input => true,
            ComponentId.Overlay => true,
            ComponentId.Tooltip => true,
            ComponentId.ContextMenu => true,
            ComponentId.PopoverMenu => true,
            ComponentId.Table => true,
            ComponentId.Slider => true,
            ComponentId.DockArea => true,
            ComponentId.DockPanel => true,
            _ => false,
        };

        internal static ValueKind? ExpectedValueKind(OpCode operation) => operation switch
        {
            OpCode.Flex => ValueKind.None,
            OpCode.VStack => ValueKind.None,
            OpCode.ItemsCenter => ValueKind.None,
            OpCode.JustifyCenter => ValueKind.None,
            OpCode.JustifyBetween => ValueKind.None,
            OpCode.FlexGrow => ValueKind.None,
            OpCode.GapPx => ValueKind.F32,
            OpCode.PaddingPx => ValueKind.F32,
            OpCode.WidthPx => ValueKind.F32,
            OpCode.WidthPercent => ValueKind.F32,
            OpCode.BackgroundRgba => ValueKind.U32,
            OpCode.Checked => ValueKind.U32,
            OpCode.HeightPx => ValueKind.F32,
            OpCode.HeightPercent => ValueKind.F32,
            OpCode.BorderRgba => ValueKind.U32,
            OpCode.BorderWidthPx => ValueKind.F32,
            OpCode.RadiusPx => ValueKind.F32,
            OpCode.TextRgba => ValueKind.U32,
            OpCode.FontSizePx => ValueKind.F32,
            OpCode.HoverBackgroundRgba => ValueKind.U32,
            OpCode.HoverTextRgba => ValueKind.U32,
            OpCode.HoverBorderRgba => ValueKind.U32,
            OpCode.ActiveBackgroundRgba => ValueKind.U32,
            OpCode.ActiveTextRgba => ValueKind.U32,
            OpCode.ActiveBorderRgba => ValueKind.U32,
            OpCode.Disabled => ValueKind.U32,
            OpCode.OnClick => ValueKind.Callback,
            OpCode.WindowControlArea => ValueKind.U32,
            OpCode.ElementOwner => ValueKind.U32,
            OpCode.ResourceOwner => ValueKind.U32,
            OpCode.ScrollAxis => ValueKind.U32,
            OpCode.SmoothScroll => ValueKind.U32,
            OpCode.ShowScrollbar => ValueKind.U32,
            OpCode.ListItemCount => ValueKind.U32,
            OpCode.ListRenderer => ValueKind.Callback,
            OpCode.ListBatchSize => ValueKind.U32,
            OpCode.ListOverdrawPx => ValueKind.F32,
            OpCode.ListAlignment => ValueKind.U32,
            OpCode.ListEstimatedItemHeightPx => ValueKind.F32,
            OpCode.ListContentRevision => ValueKind.U64,
            OpCode.ListItemId => ValueKind.U64,
            OpCode.ImageObjectFit => ValueKind.U32,
            OpCode.ImageGrayscale => ValueKind.U32,
            OpCode.InputDisabled => ValueKind.U32,
            OpCode.InputReadOnly => ValueKind.U32,
            OpCode.InputPassword => ValueKind.U32,
            OpCode.InputOnChanged => ValueKind.Callback,
            OpCode.InputOnSubmitted => ValueKind.Callback,
            OpCode.InputOnFocusChanged => ValueKind.Callback,
            OpCode.OverlayPlacement => ValueKind.U32,
            OpCode.OverlayPriority => ValueKind.U32,
            OpCode.OverlayMarginPx => ValueKind.F32,
            OpCode.OverlayModal => ValueKind.U32,
            OpCode.OverlayBackdropRgba => ValueKind.U32,
            OpCode.OverlayDismissOnBackdrop => ValueKind.U32,
            OpCode.OverlayDismissOnEscape => ValueKind.U32,
            OpCode.OverlayOnDismiss => ValueKind.Callback,
            OpCode.TooltipPlacement => ValueKind.U32,
            OpCode.TooltipAlignment => ValueKind.U32,
            OpCode.TooltipShowDelayMs => ValueKind.U32,
            OpCode.TooltipHideDelayMs => ValueKind.U32,
            OpCode.TooltipGapPx => ValueKind.F32,
            OpCode.TooltipMarginPx => ValueKind.F32,
            OpCode.ContextMenuPriority => ValueKind.U32,
            OpCode.ContextMenuMarginPx => ValueKind.F32,
            OpCode.PopoverMenuPriority => ValueKind.U32,
            OpCode.PopoverMenuMarginPx => ValueKind.F32,
            OpCode.TableShowHeader => ValueKind.U32,
            OpCode.TableCellColumn => ValueKind.U32,
            OpCode.ScrollbarGutter => ValueKind.U32,
            OpCode.ScrollbarWidth => ValueKind.F32,
            OpCode.TableColumn => ValueKind.U64,
            OpCode.SliderMin => ValueKind.F32,
            OpCode.SliderMax => ValueKind.F32,
            OpCode.SliderStep => ValueKind.F32,
            OpCode.SliderAxis => ValueKind.U32,
            OpCode.SliderDisabled => ValueKind.U32,
            OpCode.SliderScale => ValueKind.U32,
            OpCode.SliderValue => ValueKind.F32,
            OpCode.SliderRangeStart => ValueKind.F32,
            OpCode.SliderRangeEnd => ValueKind.F32,
            OpCode.SliderOnChanged => ValueKind.Callback,
            OpCode.SliderOnReleased => ValueKind.Callback,
            OpCode.DockAxis => ValueKind.U32,
            OpCode.DockActiveIndex => ValueKind.U32,
            OpCode.DockInitialSizePx => ValueKind.F32,
            OpCode.DockPanelClosable => ValueKind.U32,
            OpCode.DockPanelZoomable => ValueKind.U32,
            OpCode.DockPanelInnerPadding => ValueKind.U32,
            OpCode.DockLocked => ValueKind.U32,
            OpCode.DockRegionSide => ValueKind.U32,
            OpCode.DockRegionOpen => ValueKind.U32,
            OpCode.DockRegionCollapsible => ValueKind.U32,
            OpCode.DrawingViewBoxOrigin => ValueKind.F32x2,
            OpCode.DrawingViewBoxSize => ValueKind.F32x2,
            OpCode.DynamicActive => ValueKind.U32,
            OpCode.PathMoveTo => ValueKind.F32x2,
            OpCode.PathLineTo => ValueKind.F32x2,
            OpCode.PathQuadraticControl => ValueKind.F32x2,
            OpCode.PathQuadraticTo => ValueKind.F32x2,
            OpCode.PathCubicControlA => ValueKind.F32x2,
            OpCode.PathCubicControlB => ValueKind.F32x2,
            OpCode.PathCubicTo => ValueKind.F32x2,
            OpCode.PathArcRadii => ValueKind.F32x2,
            OpCode.PathArcRotation => ValueKind.F32,
            OpCode.PathArcFlags => ValueKind.U32,
            OpCode.PathArcTo => ValueKind.F32x2,
            OpCode.PathClose => ValueKind.None,
            OpCode.PathFillRgba => ValueKind.U32,
            OpCode.PathFillRule => ValueKind.U32,
            OpCode.PathStrokeRgba => ValueKind.U32,
            OpCode.PathStrokeWidthPx => ValueKind.F32,
            OpCode.PathDashPx => ValueKind.F32,
            OpCode.PathCircleCenter => ValueKind.F32x2,
            OpCode.PathCircleRadius => ValueKind.F32,
            _ => null,
        };

        private static ulong Capabilities(ComponentId component) => component switch
        {
            ComponentId.Div => 0x0000000000002007UL,
            ComponentId.Text => 0x0000000000000001UL,
            ComponentId.Button => 0x000000000000202BUL,
            ComponentId.Checkbox => 0x000000000000003BUL,
            ComponentId.Radio => 0x000000000000003BUL,
            ComponentId.Badge => 0x0000000000000003UL,
            ComponentId.Divider => 0x0000000000000001UL,
            ComponentId.Spacer => 0x0000000000000001UL,
            ComponentId.Scroll => 0x00000000000000C7UL,
            ComponentId.List => 0x0000000000000141UL,
            ComponentId.Image => 0x0000000000000201UL,
            ComponentId.Input => 0x0000000000000441UL,
            ComponentId.Overlay => 0x0000000000000842UL,
            ComponentId.Tooltip => 0x0000000000001042UL,
            ComponentId.ContextMenu => 0x0000000000004043UL,
            ComponentId.PopoverMenu => 0x0000000000008043UL,
            ComponentId.Table => 0x0000000000010141UL,
            ComponentId.Slider => 0x0000000000020041UL,
            ComponentId.Drawing => 0x0000000000040003UL,
            ComponentId.Path => 0x0000000000080000UL,
            ComponentId.Dynamic => 0x0000000000100042UL,
            ComponentId.DockArea => 0x0000000000200047UL,
            ComponentId.DockSplit => 0x0000000000C00002UL,
            ComponentId.DockTabs => 0x0000000001400002UL,
            ComponentId.DockPanel => 0x0000000002000002UL,
            ComponentId.DockRegion => 0x0000000004400002UL,
            _ => 0,
        };

        private static ulong RequiredCapability(OpCode operation) => operation switch
        {
            OpCode.Flex => 0x0000000000000004UL,
            OpCode.VStack => 0x0000000000000004UL,
            OpCode.ItemsCenter => 0x0000000000000001UL,
            OpCode.JustifyCenter => 0x0000000000000001UL,
            OpCode.JustifyBetween => 0x0000000000000001UL,
            OpCode.FlexGrow => 0x0000000000000001UL,
            OpCode.GapPx => 0x0000000000000001UL,
            OpCode.PaddingPx => 0x0000000000000001UL,
            OpCode.WidthPx => 0x0000000000000001UL,
            OpCode.WidthPercent => 0x0000000000000001UL,
            OpCode.BackgroundRgba => 0x0000000000000001UL,
            OpCode.Checked => 0x0000000000000010UL,
            OpCode.HeightPx => 0x0000000000000001UL,
            OpCode.HeightPercent => 0x0000000000000001UL,
            OpCode.BorderRgba => 0x0000000000000001UL,
            OpCode.BorderWidthPx => 0x0000000000000001UL,
            OpCode.RadiusPx => 0x0000000000000001UL,
            OpCode.TextRgba => 0x0000000000000001UL,
            OpCode.FontSizePx => 0x0000000000000001UL,
            OpCode.HoverBackgroundRgba => 0x0000000000000008UL,
            OpCode.HoverTextRgba => 0x0000000000000008UL,
            OpCode.HoverBorderRgba => 0x0000000000000008UL,
            OpCode.ActiveBackgroundRgba => 0x0000000000000008UL,
            OpCode.ActiveTextRgba => 0x0000000000000008UL,
            OpCode.ActiveBorderRgba => 0x0000000000000008UL,
            OpCode.Disabled => 0x0000000000000020UL,
            OpCode.OnClick => 0x0000000000000008UL,
            OpCode.WindowControlArea => 0x0000000000002000UL,
            OpCode.ElementOwner => 0x0000000000000008UL,
            OpCode.ResourceOwner => 0x0000000000000040UL,
            OpCode.ScrollAxis => 0x0000000000000080UL,
            OpCode.SmoothScroll => 0x0000000000000040UL,
            OpCode.ShowScrollbar => 0x0000000000000040UL,
            OpCode.ListItemCount => 0x0000000000000100UL,
            OpCode.ListRenderer => 0x0000000000000100UL,
            OpCode.ListBatchSize => 0x0000000000000100UL,
            OpCode.ListOverdrawPx => 0x0000000000000100UL,
            OpCode.ListAlignment => 0x0000000000000100UL,
            OpCode.ListEstimatedItemHeightPx => 0x0000000000000100UL,
            OpCode.ListContentRevision => 0x0000000000000100UL,
            OpCode.ListItemId => 0x0000000000000001UL,
            OpCode.ImageObjectFit => 0x0000000000000200UL,
            OpCode.ImageGrayscale => 0x0000000000000200UL,
            OpCode.InputDisabled => 0x0000000000000400UL,
            OpCode.InputReadOnly => 0x0000000000000400UL,
            OpCode.InputPassword => 0x0000000000000400UL,
            OpCode.InputOnChanged => 0x0000000000000400UL,
            OpCode.InputOnSubmitted => 0x0000000000000400UL,
            OpCode.InputOnFocusChanged => 0x0000000000000400UL,
            OpCode.OverlayPlacement => 0x0000000000000800UL,
            OpCode.OverlayPriority => 0x0000000000000800UL,
            OpCode.OverlayMarginPx => 0x0000000000000800UL,
            OpCode.OverlayModal => 0x0000000000000800UL,
            OpCode.OverlayBackdropRgba => 0x0000000000000800UL,
            OpCode.OverlayDismissOnBackdrop => 0x0000000000000800UL,
            OpCode.OverlayDismissOnEscape => 0x0000000000000800UL,
            OpCode.OverlayOnDismiss => 0x0000000000000800UL,
            OpCode.TooltipPlacement => 0x0000000000001000UL,
            OpCode.TooltipAlignment => 0x0000000000001000UL,
            OpCode.TooltipShowDelayMs => 0x0000000000001000UL,
            OpCode.TooltipHideDelayMs => 0x0000000000001000UL,
            OpCode.TooltipGapPx => 0x0000000000001000UL,
            OpCode.TooltipMarginPx => 0x0000000000001000UL,
            OpCode.ContextMenuPriority => 0x0000000000004000UL,
            OpCode.ContextMenuMarginPx => 0x0000000000004000UL,
            OpCode.PopoverMenuPriority => 0x0000000000008000UL,
            OpCode.PopoverMenuMarginPx => 0x0000000000008000UL,
            OpCode.TableShowHeader => 0x0000000000010000UL,
            OpCode.TableCellColumn => 0x0000000000000001UL,
            OpCode.ScrollbarGutter => 0x0000000000000040UL,
            OpCode.ScrollbarWidth => 0x0000000000000040UL,
            OpCode.TableColumn => 0x0000000000010000UL,
            OpCode.SliderMin => 0x0000000000020000UL,
            OpCode.SliderMax => 0x0000000000020000UL,
            OpCode.SliderStep => 0x0000000000020000UL,
            OpCode.SliderAxis => 0x0000000000020000UL,
            OpCode.SliderDisabled => 0x0000000000020000UL,
            OpCode.SliderScale => 0x0000000000020000UL,
            OpCode.SliderValue => 0x0000000000020000UL,
            OpCode.SliderRangeStart => 0x0000000000020000UL,
            OpCode.SliderRangeEnd => 0x0000000000020000UL,
            OpCode.SliderOnChanged => 0x0000000000020000UL,
            OpCode.SliderOnReleased => 0x0000000000020000UL,
            OpCode.DockAxis => 0x0000000000800000UL,
            OpCode.DockActiveIndex => 0x0000000001000000UL,
            OpCode.DockInitialSizePx => 0x0000000000400000UL,
            OpCode.DockPanelClosable => 0x0000000002000000UL,
            OpCode.DockPanelZoomable => 0x0000000002000000UL,
            OpCode.DockPanelInnerPadding => 0x0000000002000000UL,
            OpCode.DockLocked => 0x0000000000200000UL,
            OpCode.DockRegionSide => 0x0000000004000000UL,
            OpCode.DockRegionOpen => 0x0000000004000000UL,
            OpCode.DockRegionCollapsible => 0x0000000004000000UL,
            OpCode.DrawingViewBoxOrigin => 0x0000000000040000UL,
            OpCode.DrawingViewBoxSize => 0x0000000000040000UL,
            OpCode.DynamicActive => 0x0000000000100000UL,
            OpCode.PathMoveTo => 0x0000000000080000UL,
            OpCode.PathLineTo => 0x0000000000080000UL,
            OpCode.PathQuadraticControl => 0x0000000000080000UL,
            OpCode.PathQuadraticTo => 0x0000000000080000UL,
            OpCode.PathCubicControlA => 0x0000000000080000UL,
            OpCode.PathCubicControlB => 0x0000000000080000UL,
            OpCode.PathCubicTo => 0x0000000000080000UL,
            OpCode.PathArcRadii => 0x0000000000080000UL,
            OpCode.PathArcRotation => 0x0000000000080000UL,
            OpCode.PathArcFlags => 0x0000000000080000UL,
            OpCode.PathArcTo => 0x0000000000080000UL,
            OpCode.PathClose => 0x0000000000080000UL,
            OpCode.PathFillRgba => 0x0000000000080000UL,
            OpCode.PathFillRule => 0x0000000000080000UL,
            OpCode.PathStrokeRgba => 0x0000000000080000UL,
            OpCode.PathStrokeWidthPx => 0x0000000000080000UL,
            OpCode.PathDashPx => 0x0000000000080000UL,
            OpCode.PathCircleCenter => 0x0000000000080000UL,
            OpCode.PathCircleRadius => 0x0000000000080000UL,
            _ => 0,
        };

        internal static bool IsAllowed(ComponentId component, OpCode operation)
        {
            var required = RequiredCapability(operation);
            return required != 0 && (Capabilities(component) & required) == required;
        }

        internal static bool AllowsPayload(OpCode operation) => operation switch
        {
            OpCode.OnClick => true,
            OpCode.OverlayOnDismiss => true,
            _ => false,
        };

        internal static int PayloadError(OpCode operation, ulong a) => operation switch
        {
            OpCode.Checked when !(a <= 1UL) => -21,
            OpCode.Disabled when !(a <= 1UL) => -21,
            OpCode.WindowControlArea when !(a <= 3UL) => -39,
            OpCode.ElementOwner when !(a >= 1UL) => -25,
            OpCode.ResourceOwner when !(a >= 1UL) => -25,
            OpCode.ScrollAxis when !(a <= 2UL) => -26,
            OpCode.SmoothScroll when !(a <= 1UL) => -21,
            OpCode.ShowScrollbar when !(a <= 1UL) => -21,
            OpCode.ListBatchSize when !(a >= 1UL && a <= 512UL) => -27,
            OpCode.ListOverdrawPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -29,
            OpCode.ListAlignment when !(a <= 1UL) => -28,
            OpCode.ListEstimatedItemHeightPx when !(BitConverter.UInt32BitsToSingle((uint)a) > 0f) => -29,
            OpCode.ImageObjectFit when !(a <= 4UL) => -30,
            OpCode.ImageGrayscale when !(a <= 1UL) => -21,
            OpCode.InputDisabled when !(a <= 1UL) => -21,
            OpCode.InputReadOnly when !(a <= 1UL) => -21,
            OpCode.InputPassword when !(a <= 1UL) => -21,
            OpCode.OverlayPlacement when !(a <= 8UL) => -33,
            OpCode.OverlayMarginPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -34,
            OpCode.OverlayModal when !(a <= 1UL) => -21,
            OpCode.OverlayDismissOnBackdrop when !(a <= 1UL) => -21,
            OpCode.OverlayDismissOnEscape when !(a <= 1UL) => -21,
            OpCode.TooltipPlacement when !(a <= 4UL) => -35,
            OpCode.TooltipAlignment when !(a <= 2UL) => -36,
            OpCode.TooltipGapPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -37,
            OpCode.TooltipMarginPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -37,
            OpCode.ContextMenuMarginPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -40,
            OpCode.PopoverMenuMarginPx when !(BitConverter.UInt32BitsToSingle((uint)a) >= 0f) => -40,
            OpCode.ScrollbarGutter when !(a <= 1UL) => -21,
            OpCode.ScrollbarWidth when !(BitConverter.UInt32BitsToSingle((uint)a) >= 3f && BitConverter.UInt32BitsToSingle((uint)a) <= 32f) => -29,
            OpCode.TableColumn when !((a >> 36) == 0 && ((a >> 32) & 0b11) <= 1 && ((a >> 34) & 0b11) <= 2 && float.IsFinite(BitConverter.UInt32BitsToSingle((uint)a)) && BitConverter.UInt32BitsToSingle((uint)a) > 0f && (((a >> 32) & 0b11) != 1 || BitConverter.UInt32BitsToSingle((uint)a) <= 1f)) => -57,
            OpCode.SliderAxis when !(a <= 1UL) => -43,
            OpCode.SliderDisabled when !(a <= 1UL) => -21,
            OpCode.SliderScale when !(a <= 1UL) => -43,
            OpCode.DockAxis when !(a <= 1UL) => -60,
            OpCode.DockInitialSizePx when !(BitConverter.UInt32BitsToSingle((uint)a) > 0f) => -60,
            OpCode.DockPanelClosable when !(a <= 1UL) => -21,
            OpCode.DockPanelZoomable when !(a <= 1UL) => -21,
            OpCode.DockPanelInnerPadding when !(a <= 1UL) => -21,
            OpCode.DockLocked when !(a <= 1UL) => -21,
            OpCode.DockRegionSide when !(a <= 2UL) => -61,
            OpCode.DockRegionOpen when !(a <= 1UL) => -21,
            OpCode.DockRegionCollapsible when !(a <= 1UL) => -21,
            OpCode.DynamicActive when !(a <= 1UL) => -21,
            OpCode.PathArcFlags when !(a <= 3UL) => -59,
            OpCode.PathFillRule when !(a <= 1UL) => -59,
            OpCode.PathStrokeWidthPx when !(BitConverter.UInt32BitsToSingle((uint)a) > 0f) => -59,
            OpCode.PathDashPx when !(BitConverter.UInt32BitsToSingle((uint)a) > 0f) => -59,
            OpCode.PathCircleRadius when !(BitConverter.UInt32BitsToSingle((uint)a) > 0f) => -59,
            _ => 0,
        };
    }
}

namespace Gpui
{
    public interface IStyledElementTag { }
    public interface IParentElementTag { }
    public interface ILayoutElementTag { }
    public interface IInteractiveElementTag { }
    public interface ICheckableElementTag { }
    public interface IDisableableElementTag { }
    public interface INativeStateElementTag { }
    public interface IScrollableElementTag { }
    public interface IVirtualizedElementTag { }
    public interface IImageElementTag { }
    public interface IInputElementTag { }
    public interface IOverlayElementTag { }
    public interface ITooltipElementTag { }
    public interface IWindowControlElementTag { }
    public interface IContextMenuElementTag { }
    public interface IPopoverMenuElementTag { }
    public interface ITableElementTag { }
    public interface ISliderElementTag { }
    public interface IDrawingElementTag { }
    public interface IPathElementTag { }
    public interface IDynamicElementTag { }
    public interface IDockAreaElementTag { }
    public interface IDockContainerElementTag { }
    public interface IDockSplitElementTag { }
    public interface IDockTabsElementTag { }
    public interface IDockPanelElementTag { }
    public interface IDockRegionElementTag { }

    public readonly struct DivTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, IWindowControlElementTag { }
    public readonly struct TextTag : IStyledElementTag { }
    public readonly struct ButtonTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, IDisableableElementTag, IWindowControlElementTag { }
    public readonly struct CheckboxTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, ICheckableElementTag, IDisableableElementTag { }
    public readonly struct RadioTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, ICheckableElementTag, IDisableableElementTag { }
    public readonly struct BadgeTag : IStyledElementTag, IParentElementTag { }
    public readonly struct DividerTag : IStyledElementTag { }
    public readonly struct SpacerTag : IStyledElementTag { }
    public readonly struct ScrollTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, INativeStateElementTag, IScrollableElementTag { }
    public readonly struct ListTag : IStyledElementTag, INativeStateElementTag, IVirtualizedElementTag { }
    public readonly struct ImageTag : IStyledElementTag, IImageElementTag { }
    public readonly struct InputTag : IStyledElementTag, INativeStateElementTag, IInputElementTag { }
    public readonly struct OverlayTag : IParentElementTag, INativeStateElementTag, IOverlayElementTag { }
    public readonly struct TooltipTag : IParentElementTag, INativeStateElementTag, ITooltipElementTag { }
    public readonly struct ContextMenuTag : IStyledElementTag, IParentElementTag, INativeStateElementTag, IContextMenuElementTag { }
    public readonly struct PopoverMenuTag : IStyledElementTag, IParentElementTag, INativeStateElementTag, IPopoverMenuElementTag { }
    public readonly struct TableTag : IStyledElementTag, INativeStateElementTag, IVirtualizedElementTag, ITableElementTag { }
    public readonly struct SliderTag : IStyledElementTag, INativeStateElementTag, ISliderElementTag { }
    public readonly struct DrawingTag : IStyledElementTag, IParentElementTag, IDrawingElementTag { }
    public readonly struct PathTag : IPathElementTag { }
    public readonly struct DynamicTag : IParentElementTag, INativeStateElementTag, IDynamicElementTag { }
    public readonly struct DockAreaTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, INativeStateElementTag, IDockAreaElementTag { }
    public readonly struct DockSplitTag : IParentElementTag, IDockContainerElementTag, IDockSplitElementTag { }
    public readonly struct DockTabsTag : IParentElementTag, IDockContainerElementTag, IDockTabsElementTag { }
    public readonly struct DockPanelTag : IParentElementTag, IDockPanelElementTag { }
    public readonly struct DockRegionTag : IParentElementTag, IDockContainerElementTag, IDockRegionElementTag { }

    public readonly unsafe ref partial struct RenderContext
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<DivTag> Div(params ReadOnlySpan<Element> children)
        {
            var element = ArenaWriter.AddNode<DivTag>(_arena, ComponentId.Div);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<ButtonTag>(_arena, ComponentId.Button, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<ButtonTag>(_arena, ComponentId.Button, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Button(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Button(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Button(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Button(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<CheckboxTag>(_arena, ComponentId.Checkbox, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<CheckboxTag>(_arena, ComponentId.Checkbox, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Checkbox(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Checkbox(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Checkbox(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Checkbox(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<RadioTag>(_arena, ComponentId.Radio, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<RadioTag>(_arena, ComponentId.Radio, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Radio(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Radio(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Radio(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Radio(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<BadgeTag> Badge(params ReadOnlySpan<Element> children)
        {
            var element = ArenaWriter.AddNode<BadgeTag>(_arena, ComponentId.Badge);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<DividerTag> Divider() =>
            ArenaWriter.AddNode<DividerTag>(_arena, ComponentId.Divider);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<SpacerTag> Spacer() =>
            ArenaWriter.AddNode<SpacerTag>(_arena, ComponentId.Spacer);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<PathTag> Path() =>
            ArenaWriter.AddNode<PathTag>(_arena, ComponentId.Path);

    }

    public static partial class ElementExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Child<TTag>(this Element<TTag> parent, Element child)
            where TTag : unmanaged, IParentElementTag
        {
            Span<Element> one = [child];
            ArenaWriter.AddChildren(parent.Inner, one);
            return parent;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Children<TTag>(this Element<TTag> parent, params ReadOnlySpan<Element> children)
            where TTag : unmanaged, IParentElementTag
        {
            ArenaWriter.AddChildren(parent.Inner, children);
            return parent;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsCenter<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsCenter);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyCenter<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyCenter);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyBetween<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyBetween);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Grow<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.FlexGrow);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Gap<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.GapPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Padding<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Background<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.BackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Checked<TTag>(this Element<TTag> element, bool value)
            where TTag : unmanaged, ICheckableElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.Checked, value ? 1u : 0u);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> BorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.BorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> BorderWidth<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.BorderWidthPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Radius<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.RadiusPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> TextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.TextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> FontSize<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.FontSizePx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverBackground<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverBackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverTextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverTextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverBorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverBorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveBackground<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveBackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveTextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveTextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveBorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveBorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Disabled<TTag>(this Element<TTag> element, bool value)
            where TTag : unmanaged, IDisableableElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.Disabled, value ? 1u : 0u);
            return element;
        }

    }
}
