// <auto-generated />
using System.Runtime.CompilerServices;
using Gpui.Interop;

namespace Gpui
{
    public interface IStyledElementTag { }
    public interface IParentElementTag { }
    public interface ILayoutElementTag { }
    public interface IInteractiveElementTag { }
    public interface ICheckableElementTag { }
    public interface IDisableableElementTag { }
    public interface INativeStateElementTag { }
    public interface IScrollableElementTag { }
    public interface IVirtualizedElementTag { }
    public interface IImageElementTag { }
    public interface IInputElementTag { }
    public interface IOverlayElementTag { }
    public interface ITooltipElementTag { }
    public interface IWindowControlElementTag { }
    public interface IContextMenuElementTag { }
    public interface IPopoverMenuElementTag { }
    public interface ITableElementTag { }
    public interface ISliderElementTag { }
    public interface IDrawingElementTag { }
    public interface IPathElementTag { }
    public interface IDynamicElementTag { }
    public interface IDockAreaElementTag { }
    public interface IDockContainerElementTag { }
    public interface IDockSplitElementTag { }
    public interface IDockTabsElementTag { }
    public interface IDockPanelElementTag { }
    public interface IDockRegionElementTag { }
    public interface IExtensionElementTag { }
    public interface IKeyMouseElementTag { }

    public readonly struct DivTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, IWindowControlElementTag, IKeyMouseElementTag { }
    public readonly struct TextTag : IStyledElementTag { }
    public readonly struct ButtonTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, IDisableableElementTag, IWindowControlElementTag, IKeyMouseElementTag { }
    public readonly struct CheckboxTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, ICheckableElementTag, IDisableableElementTag, IKeyMouseElementTag { }
    public readonly struct RadioTag : IStyledElementTag, IParentElementTag, IInteractiveElementTag, ICheckableElementTag, IDisableableElementTag, IKeyMouseElementTag { }
    public readonly struct BadgeTag : IStyledElementTag, IParentElementTag { }
    public readonly struct DividerTag : IStyledElementTag { }
    public readonly struct SpacerTag : IStyledElementTag { }
    public readonly struct ScrollTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, INativeStateElementTag, IScrollableElementTag { }
    public readonly struct ListTag : IStyledElementTag, INativeStateElementTag, IVirtualizedElementTag { }
    public readonly struct ImageTag : IStyledElementTag, IImageElementTag { }
    public readonly struct InputTag : IStyledElementTag, INativeStateElementTag, IInputElementTag { }
    public readonly struct OverlayTag : IParentElementTag, INativeStateElementTag, IOverlayElementTag { }
    public readonly struct TooltipTag : IParentElementTag, INativeStateElementTag, ITooltipElementTag { }
    public readonly struct ContextMenuTag : IStyledElementTag, IParentElementTag, INativeStateElementTag, IContextMenuElementTag { }
    public readonly struct PopoverMenuTag : IStyledElementTag, IParentElementTag, INativeStateElementTag, IPopoverMenuElementTag { }
    public readonly struct TableTag : IStyledElementTag, INativeStateElementTag, IVirtualizedElementTag, ITableElementTag { }
    public readonly struct SliderTag : IStyledElementTag, INativeStateElementTag, ISliderElementTag { }
    public readonly struct DrawingTag : IStyledElementTag, IParentElementTag, IDrawingElementTag { }
    public readonly struct PathTag : IPathElementTag { }
    public readonly struct DynamicTag : IParentElementTag, INativeStateElementTag, IDynamicElementTag { }
    public readonly struct DockAreaTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, INativeStateElementTag, IDockAreaElementTag { }
    public readonly struct DockSplitTag : IParentElementTag, IDockContainerElementTag, IDockSplitElementTag { }
    public readonly struct DockTabsTag : IParentElementTag, IDockContainerElementTag, IDockTabsElementTag { }
    public readonly struct DockPanelTag : IParentElementTag, IDockPanelElementTag { }
    public readonly struct DockRegionTag : IParentElementTag, IDockContainerElementTag, IDockRegionElementTag { }
    public readonly struct NativeExtensionTag : IStyledElementTag, IParentElementTag, ILayoutElementTag, INativeStateElementTag, IExtensionElementTag { }

    public enum FlexWrap : uint
    {
        NoWrap = 0,
        Wrap = 1,
        WrapReverse = 2,
    }

    public enum TextAlignment : uint
    {
        Left = 0,
        Center = 1,
        Right = 2,
    }

    public enum MouseCursor : uint
    {
        Arrow = 0,
        IBeam = 1,
        Crosshair = 2,
        ClosedHand = 3,
        OpenHand = 4,
        PointingHand = 5,
        ResizeLeft = 6,
        ResizeRight = 7,
        ResizeLeftRight = 8,
        ResizeUp = 9,
        ResizeDown = 10,
        ResizeUpDown = 11,
        ResizeUpLeftDownRight = 12,
        ResizeUpRightDownLeft = 13,
        ResizeColumn = 14,
        ResizeRow = 15,
        IBeamCursorForVerticalLayout = 16,
        OperationNotAllowed = 17,
        DragLink = 18,
        DragCopy = 19,
        ContextualMenu = 20,
    }

    public enum WhiteSpace : uint
    {
        Normal = 0,
        Nowrap = 1,
    }

    public enum Visibility : uint
    {
        Visible = 0,
        Hidden = 1,
    }

    public enum InputEventKind : ushort
    {
        /// <summary>The input value changed.</summary>
        Changed = 1,
        /// <summary>The input value was submitted.</summary>
        Submitted = 2,
        /// <summary>Input focus changed.</summary>
        FocusChanged = 3,
    }

    public enum SliderEventKind : ushort
    {
        /// <summary>The slider value changed during interaction.</summary>
        Changed = 4,
        /// <summary>The slider interaction released.</summary>
        Released = 5,
    }

    public enum DockEventKind : ushort
    {
        /// <summary>Coarse structural signal. Fires for native interaction and for declarative or controller-driven structural changes. Carries no payload; debounce with the event revision.</summary>
        LayoutChanged = 6,
        /// <summary>Carries the exported layout document requested through the controller.</summary>
        LayoutExported = 7,
        /// <summary>A panel left the Dock natively or through the controller. Carries the panel id. Panels removed by declaration or pruned by layout import do not fire this event.</summary>
        PanelClosed = 8,
    }

    public enum KeyEventKind : ushort
    {
        /// <summary>A key was pressed while the bound element had focus or the event bubbled to it. Carries the UTF-8 key name; flags hold modifiers and the held-repeat bit. Observers only: never stops propagation.</summary>
        Down = 9,
        /// <summary>A key was released while the bound element had focus or the event bubbled to it. Carries the UTF-8 key name; flags hold modifiers. Observers only: never stops propagation.</summary>
        Up = 10,
    }

    public enum MouseEventKind : ushort
    {
        /// <summary>A mouse button was pressed over the bound element. Carries x, y, button, and click count; flags hold modifiers. Observers only: never stops propagation.</summary>
        Down = 11,
        /// <summary>A mouse button was released over the bound element. Carries x, y, button, and click count; flags hold modifiers. Observers only: never stops propagation.</summary>
        Up = 12,
        /// <summary>A mouse button was pressed outside the bound element. Same payload as mouse down. Observers only: never stops propagation.</summary>
        DownOut = 15,
        /// <summary>A mouse button was released outside the bound element. Same payload as mouse up. Observers only: never stops propagation.</summary>
        UpOut = 16,
        /// <summary>The mouse moved over the bound element. Carries x, y, and the pressed button (none when empty); flags hold modifiers. High-frequency: only published while bound, and handlers must stay cheap. Observers only: never stops propagation.</summary>
        Move = 17,
    }

    public enum ModifiersEventKind : ushort
    {
        /// <summary>Modifier keys changed while the bound element had focus or the event bubbled to it. Carries no payload; flags hold the current modifiers. This is the only event for modifier-only presses, which never produce key events. Observers only: never stops propagation.</summary>
        Changed = 13,
    }

    public enum HoverEventKind : ushort
    {
        /// <summary>Hover state changed over the bound element. Carries no payload; flags hold modifiers in bits 0-4 and the hovering state in bit 5. Fires on enter/exit transitions only, never per move. Observers only: never stops propagation.</summary>
        Changed = 14,
    }

    public enum ScrollEventKind : ushort
    {
        /// <summary>The scroll wheel moved over the bound element. Carries x, y, delta x/y, and pixel/line units; flags hold modifiers. High-frequency: only published while bound, and handlers must stay cheap. Does not replace retained Scroll resources. Observers only: never stops propagation.</summary>
        Wheel = 18,
    }

    public enum FileEventKind : ushort
    {
        /// <summary>OS files were dropped onto the bound element. Carries x, y followed by NUL-separated UTF-8 paths (lossy); flags hold modifiers. Only published while bound. Observers only: never stops propagation.</summary>
        Dropped = 19,
    }

    public readonly unsafe ref partial struct RenderContext
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<DivTag> Div(params ReadOnlySpan<Element> children)
        {
            var element = ArenaWriter.AddNode<DivTag>(_arena, ComponentId.Div);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<ButtonTag>(_arena, ComponentId.Button, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<ButtonTag>(_arena, ComponentId.Button, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Button(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Button(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Button(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<ButtonTag> Button(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Button(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<CheckboxTag>(_arena, ComponentId.Checkbox, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<CheckboxTag>(_arena, ComponentId.Checkbox, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Checkbox(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Checkbox(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Checkbox(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<CheckboxTag> Checkbox(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Checkbox(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)
        {
            if (id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(id));
            }
            var element = ArenaWriter.AddNode<RadioTag>(_arena, ComponentId.Radio, id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)
        {
            if (utf8Id.IsEmpty)
            {
                throw new ArgumentException("A non-empty element id is required.", nameof(utf8Id));
            }
            var element = ArenaWriter.AddNode<RadioTag>(_arena, ComponentId.Radio, utf8Id);
            AddInteractiveOwner(element.Inner);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Radio(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Radio(id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)
        {
            var child = Text(label);
            return Radio(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<RadioTag> Radio(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)
        {
            var child = Text(utf8Label);
            return Radio(utf8Id, child);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<BadgeTag> Badge(params ReadOnlySpan<Element> children)
        {
            var element = ArenaWriter.AddNode<BadgeTag>(_arena, ComponentId.Badge);
            ArenaWriter.AddChildren(element.Inner, children);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<DividerTag> Divider() =>
            ArenaWriter.AddNode<DividerTag>(_arena, ComponentId.Divider);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<SpacerTag> Spacer() =>
            ArenaWriter.AddNode<SpacerTag>(_arena, ComponentId.Spacer);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Element<PathTag> Path() =>
            ArenaWriter.AddNode<PathTag>(_arena, ComponentId.Path);

    }

    public static partial class ElementExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Child<TTag>(this Element<TTag> parent, Element child)
            where TTag : unmanaged, IParentElementTag
        {
            Span<Element> one = [child];
            ArenaWriter.AddChildren(parent.Inner, one);
            return parent;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Children<TTag>(this Element<TTag> parent, params ReadOnlySpan<Element> children)
            where TTag : unmanaged, IParentElementTag
        {
            ArenaWriter.AddChildren(parent.Inner, children);
            return parent;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsCenter<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsCenter);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyCenter<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyCenter);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyBetween<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyBetween);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Gap<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.GapPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Padding<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Background<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.BackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Checked<TTag>(this Element<TTag> element, bool value)
            where TTag : unmanaged, ICheckableElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.Checked, value ? 1u : 0u);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> BorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.BorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> BorderWidth<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.BorderWidthPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Radius<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.RadiusPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> TextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.TextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> FontSize<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.FontSizePx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverBackground<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverBackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverTextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverTextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> HoverBorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.HoverBorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveBackground<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveBackgroundRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveTextColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveTextRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ActiveBorderColor<TTag>(this Element<TTag> element, Color color)
            where TTag : unmanaged, IInteractiveElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.ActiveBorderRgba, color.Rgba);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Disabled<TTag>(this Element<TTag> element, bool value)
            where TTag : unmanaged, IDisableableElementTag
        {
            ArenaWriter.AddU32(element.Inner, OpCode.Disabled, value ? 1u : 0u);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Margin<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginX<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginXPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginY<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginYPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginTop<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginTopPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginBottom<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginBottomPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginLeft<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginLeftPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MarginRight<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MarginRightPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingX<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingXPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingY<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingYPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingTop<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingTopPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingBottom<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingBottomPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingLeft<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingLeftPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> PaddingRight<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.PaddingRightPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> GapX<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.GapXPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> GapY<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.GapYPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MinWidth<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MinWidthPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MinHeight<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MinHeightPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MaxWidth<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MaxWidthPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> MaxHeight<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.MaxHeightPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsStart<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsStart);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsEnd<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsEnd);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyStart<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyStart);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> JustifyEnd<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.JustifyEnd);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Relative<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.Relative);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Absolute<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.Absolute);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Top<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.TopPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Left<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.LeftPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Right<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.RightPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Bottom<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.BottomPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Inset<TTag>(this Element<TTag> element, Pixels value)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.InsetPx, value.Value);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> OverflowHidden<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.OverflowHidden);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> OverflowXHidden<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.OverflowXHidden);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> OverflowYHidden<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.OverflowYHidden);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsBaseline<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsBaseline);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemsStretch<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.ItemsStretch);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfStart<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfStart);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfEnd<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfEnd);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfFlexStart<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfFlexStart);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfFlexEnd<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfFlexEnd);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfCenter<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfCenter);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfBaseline<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfBaseline);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> SelfStretch<TTag>(this Element<TTag> element)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddNoArg(element.Inner, OpCode.SelfStretch);
            return element;
        }

        /// <summary>Declares the flex grow factor of an item. Defaults to 1.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Grow<TTag>(this Element<TTag> element, float factor = 1)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.FlexGrow, factor);
            return element;
        }

        /// <summary>Declares the flex shrink factor of an item. Must be finite and non-negative.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Shrink<TTag>(this Element<TTag> element, float factor)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.FlexShrink, factor);
            return element;
        }

        /// <summary>Declares the flex wrapping behavior of a container.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Wrap<TTag>(this Element<TTag> element, FlexWrap wrap)
            where TTag : unmanaged, IStyledElementTag
        {
            if ((uint)wrap > (uint)global::Gpui.FlexWrap.WrapReverse)
            {
                throw new ArgumentOutOfRangeException(nameof(wrap));
            }

            ArenaWriter.AddU32(element.Inner, OpCode.FlexWrap, (uint)wrap);
            return element;
        }

        /// <summary>Declares the opacity of an element, from 0 (transparent) to 1 (opaque).</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Opacity<TTag>(this Element<TTag> element, float opacity)
            where TTag : unmanaged, IStyledElementTag
        {
            ArenaWriter.AddF32(element.Inner, OpCode.Opacity, opacity);
            return element;
        }

        /// <summary>Declares the horizontal text alignment within an element.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> TextAlign<TTag>(this Element<TTag> element, TextAlignment align)
            where TTag : unmanaged, IStyledElementTag
        {
            if ((uint)align > (uint)global::Gpui.TextAlignment.Right)
            {
                throw new ArgumentOutOfRangeException(nameof(align));
            }

            ArenaWriter.AddU32(element.Inner, OpCode.TextAlign, (uint)align);
            return element;
        }

        /// <summary>Truncates text after the given number of lines. Must be at least 1.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> LineClamp<TTag>(this Element<TTag> element, uint lines)
            where TTag : unmanaged, IStyledElementTag
        {
            if (lines == 0)
            {
                throw new ArgumentOutOfRangeException(nameof(lines), "Line clamp must be at least 1.");
            }

            ArenaWriter.AddU32(element.Inner, OpCode.LineClamp, lines);
            return element;
        }

        /// <summary>Declares the mouse cursor shown while hovering an element.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Cursor<TTag>(this Element<TTag> element, MouseCursor cursor)
            where TTag : unmanaged, IStyledElementTag
        {
            if ((uint)cursor > (uint)global::Gpui.MouseCursor.ContextualMenu)
            {
                throw new ArgumentOutOfRangeException(nameof(cursor));
            }

            ArenaWriter.AddU32(element.Inner, OpCode.Cursor, (uint)cursor);
            return element;
        }

        /// <summary>Declares the stable model identity of a virtualized list row. IDs must be unique within one list; payload 0 is reserved.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> ItemId<TTag>(this Element<TTag> element, ulong itemId)
            where TTag : unmanaged, IStyledElementTag
        {
            if (itemId == 0)
            {
                throw new ArgumentOutOfRangeException(nameof(itemId), "Item ID 0 is reserved.");
            }

            ArenaWriter.AddU64(element.Inner, OpCode.ListItemId, itemId);
            return element;
        }

        /// <summary>Declares the preferred aspect ratio (width divided by height) of an item. Must be finite and positive.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> AspectRatio<TTag>(this Element<TTag> element, float ratio)
            where TTag : unmanaged, IStyledElementTag
        {
            if (!float.IsFinite(ratio) || ratio <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(ratio), "Aspect ratio must be finite and positive.");
            }

            ArenaWriter.AddF32(element.Inner, OpCode.AspectRatio, ratio);
            return element;
        }

        /// <summary>Declares the line-wrapping behavior of text within an element.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> WhiteSpace<TTag>(this Element<TTag> element, WhiteSpace whiteSpace)
            where TTag : unmanaged, IStyledElementTag
        {
            if ((uint)whiteSpace > (uint)global::Gpui.WhiteSpace.Nowrap)
            {
                throw new ArgumentOutOfRangeException(nameof(whiteSpace));
            }

            ArenaWriter.AddU32(element.Inner, OpCode.WhiteSpace, (uint)whiteSpace);
            return element;
        }

        /// <summary>Declares the draw visibility of an element. Hidden elements still occupy layout space.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Element<TTag> Visibility<TTag>(this Element<TTag> element, Visibility visibility)
            where TTag : unmanaged, IStyledElementTag
        {
            if ((uint)visibility > (uint)global::Gpui.Visibility.Hidden)
            {
                throw new ArgumentOutOfRangeException(nameof(visibility));
            }

            ArenaWriter.AddU32(element.Inner, OpCode.Visibility, (uint)visibility);
            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        /// <summary>Declares the width of an element, in pixels or percent.</summary>
        public static Element<TTag> Width<TTag>(this Element<TTag> element, Length value)
            where TTag : unmanaged, IStyledElementTag
        {
            switch (value.Unit)
            {
                case LengthUnit.Pixels:
                    ArenaWriter.AddF32(element.Inner, OpCode.WidthPx, value.Value);
                    break;
                case LengthUnit.Percent:
                    ArenaWriter.AddF32(element.Inner, OpCode.WidthPercent, value.Value);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(value));
            }

            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        /// <summary>Declares the height of an element, in pixels or percent.</summary>
        public static Element<TTag> Height<TTag>(this Element<TTag> element, Length value)
            where TTag : unmanaged, IStyledElementTag
        {
            switch (value.Unit)
            {
                case LengthUnit.Pixels:
                    ArenaWriter.AddF32(element.Inner, OpCode.HeightPx, value.Value);
                    break;
                case LengthUnit.Percent:
                    ArenaWriter.AddF32(element.Inner, OpCode.HeightPercent, value.Value);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(value));
            }

            return element;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        /// <summary>Declares the initial main size of a flex item, in pixels or percent.</summary>
        public static Element<TTag> Basis<TTag>(this Element<TTag> element, Length value)
            where TTag : unmanaged, IStyledElementTag
        {
            switch (value.Unit)
            {
                case LengthUnit.Pixels:
                    ArenaWriter.AddF32(element.Inner, OpCode.FlexBasisPx, value.Value);
                    break;
                case LengthUnit.Percent:
                    ArenaWriter.AddF32(element.Inner, OpCode.FlexBasisPercent, value.Value);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(value));
            }

            return element;
        }

    }
}
