// @generated by Gpui.Bindings.Generator. Do not edit.
#ifndef GPUI_MOON_BRIDGE_G_H
#define GPUI_MOON_BRIDGE_G_H
#include <stdint.h>
typedef int32_t (*GpuiMoonDispatch)(int32_t, uint64_t, uint64_t, uint64_t, uint32_t, uint32_t, int32_t, void *);
#define GPUI_MOON_CB_STARTED (1)
#define GPUI_MOON_CB_RENDER (2)
#define GPUI_MOON_CB_RENDER_COMPLETED (3)
#define GPUI_MOON_CB_CLICK (4)
#define GPUI_MOON_CB_RANGE (5)
#define GPUI_MOON_CB_ACCEPT_ARTIFACT (6)
#define GPUI_MOON_CB_RELEASE_ARTIFACT (7)
#define GPUI_MOON_CB_CONTROL (8)
#define GPUI_MOON_CB_DYNAMIC (9)
#define GPUI_MOON_CB_WINDOW_CLOSED (10)
#define GPUI_MOON_CB_MENU_ACTION (11)
#define GPUI_MOON_CB_MENU_APPLIED (12)
#define GPUI_MOON_ERR_ARGUMENT (-2000)
#define GPUI_MOON_ERR_MEMORY (-2001)
#define GPUI_MOON_ERR_ABI (-2002)
#define GPUI_MOON_ERR_SCHEMA (-2003)
#define GPUI_MOON_ERR_SYMBOL (-2004)
#define GPUI_MOON_ERR_LOAD (-2005)
#define GPUI_MOON_ERR_THREAD (-2006)
#define GPUI_MOON_ERR_PUBLICATION (-2007)
#define GPUI_MOON_ERR_PACKET (-2008)
#define GPUI_MOON_ERR_CALLBACK (-2009)
#define GPUI_MOON_ERR_LIMIT (-2010)
#define GPUI_MOON_ERR_STATE (-2011)
#define GPUI_MOON_ERR_RETIRED (-2012)
#define GPUI_MOON_ERR_RENDER_EFFECT (-2013)
#define GPUI_MOON_ERR_ELEMENT (-2014)
#define GPUI_MOON_PACKET_MAGIC (826428743)
#define GPUI_MOON_PACKET_HEADER_SIZE (32)
void * gpui_moon_host_new(void);
int32_t gpui_moon_host_is_null(void * host);
int32_t gpui_moon_host_load(void * host, const uint8_t * path, int32_t length, uint64_t schema_hash);
int32_t gpui_moon_host_run(void * host, uint64_t application, GpuiMoonDispatch dispatch);
void gpui_moon_host_free(void * host);
int32_t gpui_moon_host_error_length(void * host);
int32_t gpui_moon_host_error_copy(void * host, uint8_t * buffer, int32_t length);
int32_t gpui_moon_reply(void * request, const uint8_t * packet, int32_t length, uint64_t publication);
float gpui_moon_event_x(void * request);
float gpui_moon_event_y(void * request);
uint32_t gpui_moon_event_buttons(void * request);
uint32_t gpui_moon_event_modifiers(void * request);
int32_t gpui_moon_event_data_length(void * request);
int32_t gpui_moon_event_data_copy(void * request, uint8_t * buffer, int32_t length);
int32_t gpui_moon_notify(void * host, uint64_t session);
int32_t gpui_moon_application_command(void * host, uint64_t application, uint64_t window, int32_t command, int32_t flags, const uint8_t * data, int32_t length, float left, float top, float width, float height);
int32_t gpui_moon_resource_command(void * host, uint64_t session, uint32_t owner, int32_t resource, int32_t command, const uint8_t * key, int32_t key_length, const uint8_t * data, int32_t data_length, uint64_t a, uint64_t b);
int32_t gpui_moon_supports_extension(void * host, const uint8_t * id, int32_t length, uint32_t version, uint64_t schema_hash);
int32_t gpui_moon_extension_command(void * host, uint64_t session, uint32_t owner, int32_t command, int32_t flags, uint32_t version, uint64_t schema_hash, uint64_t revision, const uint8_t * extension, int32_t extension_length, const uint8_t * component, int32_t component_length, const uint8_t * key, int32_t key_length, const uint8_t * data, int32_t data_length);
int32_t gpui_moon_invalidate_artifacts(void * host, uint64_t session, const uint8_t * keys, int32_t length);
int32_t gpui_moon_menu(void * host, uint64_t application, uint64_t generation, const uint8_t * packet, int32_t length);
#endif
