// @generated by Gpui.Bindings.Generator. Do not edit.
pub const EXTENSION_ID: &str = "gpui.net.components";
pub const SCHEMA_VERSION: u32 = 12;
pub const SCHEMA_HASH: u64 = 0x1819D8A9591D88B9;

pub const COMPONENT_ATTACHMENT: &str = "attachment";
pub const ATTACHMENT_EVENT_CLICKED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttachmentSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttachmentAxis {
    Horizontal,
    Vertical,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttachmentStatus {
    Pending,
    Uploading,
    Processing,
    Failed,
    Complete,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AttachmentConfiguration<'a> {
    pub size: AttachmentSize,
    pub axis: AttachmentAxis,
    pub status: AttachmentStatus,
    pub title: &'a str,
    pub description: String,
    pub preview_source: &'a str,
    pub media_child: bool,
    pub content_child: bool,
    pub has_actions: bool,
    pub clicked_event: u64,
}

impl<'a> AttachmentConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => AttachmentSize::Xsmall, "small" => AttachmentSize::Small, "medium" => AttachmentSize::Medium, "large" => AttachmentSize::Large, _ => return None };
        let axis = match fields.next()? { "horizontal" => AttachmentAxis::Horizontal, "vertical" => AttachmentAxis::Vertical, _ => return None };
        let status = match fields.next()? { "pending" => AttachmentStatus::Pending, "uploading" => AttachmentStatus::Uploading, "processing" => AttachmentStatus::Processing, "failed" => AttachmentStatus::Failed, "complete" => AttachmentStatus::Complete, _ => return None };
        let title = fields.next()?;
        let description = serde_json::from_str::<String>(fields.next()?).ok()?;
        let preview_source = fields.next()?;
        let media_child = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let content_child = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_actions = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let clicked_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        if description.contains('\0') {
            return None;
        }
        Some(Self {
            size,
            axis,
            status,
            title,
            description,
            preview_source,
            media_child,
            content_child,
            has_actions,
            clicked_event,
        })
    }
}

pub const COMPONENT_SPINNER: &str = "spinner";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerIcon {
    Loader,
    LoaderCircle,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerEase {
    Linear,
    EaseInOut,
    EaseOutQuint,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpinnerConfiguration<'a> {
    pub size: SpinnerSize,
    pub icon: SpinnerIcon,
    pub ease: SpinnerEase,
    pub color: &'a str,
}

impl<'a> SpinnerConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => SpinnerSize::Xsmall, "small" => SpinnerSize::Small, "medium" => SpinnerSize::Medium, "large" => SpinnerSize::Large, _ => return None };
        let icon = match fields.next()? { "loader" => SpinnerIcon::Loader, "loader_circle" => SpinnerIcon::LoaderCircle, _ => return None };
        let ease = match fields.next()? { "linear" => SpinnerEase::Linear, "ease_in_out" => SpinnerEase::EaseInOut, "ease_out_quint" => SpinnerEase::EaseOutQuint, _ => return None };
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            icon,
            ease,
            color,
        })
    }
}

pub const COMPONENT_SKELETON: &str = "skeleton";

#[derive(Clone, Debug, PartialEq)]
pub struct SkeletonConfiguration {
    pub secondary: bool,
}

impl SkeletonConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let secondary = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            secondary,
        })
    }
}

pub const COMPONENT_SEPARATOR: &str = "separator";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeparatorOrientation {
    Horizontal,
    Vertical,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SeparatorConfiguration<'a> {
    pub orientation: SeparatorOrientation,
    pub dashed: bool,
    pub label: &'a str,
    pub color: &'a str,
}

impl<'a> SeparatorConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let orientation = match fields.next()? { "horizontal" => SeparatorOrientation::Horizontal, "vertical" => SeparatorOrientation::Vertical, _ => return None };
        let dashed = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            orientation,
            dashed,
            label,
            color,
        })
    }
}

pub const COMPONENT_BADGE: &str = "badge";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BadgeSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BadgeConfiguration<'a> {
    pub size: BadgeSize,
    pub dot: bool,
    pub count: u32,
    pub max: u32,
    pub color: &'a str,
}

impl<'a> BadgeConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => BadgeSize::Xsmall, "small" => BadgeSize::Small, "medium" => BadgeSize::Medium, "large" => BadgeSize::Large, _ => return None };
        let dot = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let count = fields.next()?.parse::<u32>().ok()?;
        let max = fields.next()?.parse::<u32>().ok()?;
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            dot,
            count,
            max,
            color,
        })
    }
}

pub const COMPONENT_TAG: &str = "tag";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TagSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TagVariant {
    Primary,
    Secondary,
    Danger,
    Success,
    Warning,
    Info,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TagConfiguration {
    pub size: TagSize,
    pub variant: TagVariant,
    pub outline: bool,
    pub rounded_full: bool,
}

impl TagConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => TagSize::Xsmall, "small" => TagSize::Small, "medium" => TagSize::Medium, "large" => TagSize::Large, _ => return None };
        let variant = match fields.next()? { "primary" => TagVariant::Primary, "secondary" => TagVariant::Secondary, "danger" => TagVariant::Danger, "success" => TagVariant::Success, "warning" => TagVariant::Warning, "info" => TagVariant::Info, _ => return None };
        let outline = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let rounded_full = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            outline,
            rounded_full,
        })
    }
}

pub const COMPONENT_PROGRESS: &str = "progress";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProgressSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProgressConfiguration<'a> {
    pub size: ProgressSize,
    pub value: f32,
    pub loading: bool,
    pub color: &'a str,
    pub accessibility_label: &'a str,
}

impl<'a> ProgressConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ProgressSize::Xsmall, "small" => ProgressSize::Small, "medium" => ProgressSize::Medium, "large" => ProgressSize::Large, _ => return None };
        let value = fields.next()?.parse::<f32>().ok()?;
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let accessibility_label = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        if !value.is_finite() {
            return None;
        }
        Some(Self {
            size,
            value,
            loading,
            color,
            accessibility_label,
        })
    }
}

pub const COMPONENT_PROGRESS_CIRCLE: &str = "progress_circle";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProgressCircleSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProgressCircleConfiguration<'a> {
    pub size: ProgressCircleSize,
    pub diameter: f32,
    pub value: f32,
    pub loading: bool,
    pub color: &'a str,
    pub accessibility_label: &'a str,
}

impl<'a> ProgressCircleConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ProgressCircleSize::Xsmall, "small" => ProgressCircleSize::Small, "medium" => ProgressCircleSize::Medium, "large" => ProgressCircleSize::Large, _ => return None };
        let diameter = fields.next()?.parse::<f32>().ok()?;
        let value = fields.next()?.parse::<f32>().ok()?;
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let accessibility_label = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        if !diameter.is_finite() {
            return None;
        }
        if !value.is_finite() {
            return None;
        }
        Some(Self {
            size,
            diameter,
            value,
            loading,
            color,
            accessibility_label,
        })
    }
}

pub const COMPONENT_RATING: &str = "rating";
pub const RATING_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RatingSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RatingConfiguration<'a> {
    pub size: RatingSize,
    pub value: u32,
    pub max: u32,
    pub disabled: bool,
    pub color: &'a str,
    pub changed_event: u64,
}

impl<'a> RatingConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => RatingSize::Xsmall, "small" => RatingSize::Small, "medium" => RatingSize::Medium, "large" => RatingSize::Large, _ => return None };
        let value = fields.next()?.parse::<u32>().ok()?;
        let max = fields.next()?.parse::<u32>().ok()?;
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            value,
            max,
            disabled,
            color,
            changed_event,
        })
    }
}

pub const COMPONENT_BUTTON: &str = "button";
pub const BUTTON_EVENT_CLICKED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonVariant {
    Default,
    Primary,
    Secondary,
    Danger,
    Success,
    Warning,
    Info,
    Ghost,
    Link,
    Text,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ButtonConfiguration<'a> {
    pub size: ButtonSize,
    pub variant: ButtonVariant,
    pub label: &'a str,
    pub accessibility_label: &'a str,
    pub disabled: bool,
    pub selected: bool,
    pub loading: bool,
    pub outline: bool,
    pub compact: bool,
    pub icon_asset_path: &'a str,
    pub clicked_event: u64,
}

impl<'a> ButtonConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ButtonSize::Xsmall, "small" => ButtonSize::Small, "medium" => ButtonSize::Medium, "large" => ButtonSize::Large, _ => return None };
        let variant = match fields.next()? { "default" => ButtonVariant::Default, "primary" => ButtonVariant::Primary, "secondary" => ButtonVariant::Secondary, "danger" => ButtonVariant::Danger, "success" => ButtonVariant::Success, "warning" => ButtonVariant::Warning, "info" => ButtonVariant::Info, "ghost" => ButtonVariant::Ghost, "link" => ButtonVariant::Link, "text" => ButtonVariant::Text, _ => return None };
        let label = fields.next()?;
        let accessibility_label = fields.next()?;
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let selected = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let outline = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let compact = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let icon_asset_path = fields.next()?;
        let clicked_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            label,
            accessibility_label,
            disabled,
            selected,
            loading,
            outline,
            compact,
            icon_asset_path,
            clicked_event,
        })
    }
}

pub const COMPONENT_ALERT: &str = "alert";
pub const ALERT_EVENT_CLOSED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AlertSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AlertVariant {
    Default,
    Info,
    Success,
    Warning,
    Error,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AlertConfiguration<'a> {
    pub size: AlertSize,
    pub variant: AlertVariant,
    pub title: &'a str,
    pub message: String,
    pub banner: bool,
    pub closed_event: u64,
}

impl<'a> AlertConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => AlertSize::Xsmall, "small" => AlertSize::Small, "medium" => AlertSize::Medium, "large" => AlertSize::Large, _ => return None };
        let variant = match fields.next()? { "default" => AlertVariant::Default, "info" => AlertVariant::Info, "success" => AlertVariant::Success, "warning" => AlertVariant::Warning, "error" => AlertVariant::Error, _ => return None };
        let title = fields.next()?;
        let message = serde_json::from_str::<String>(fields.next()?).ok()?;
        let banner = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let closed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        if message.contains('\0') {
            return None;
        }
        Some(Self {
            size,
            variant,
            title,
            message,
            banner,
            closed_event,
        })
    }
}

pub const COMPONENT_GROUP_BOX: &str = "group_box";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GroupBoxVariant {
    Normal,
    Fill,
    Outline,
}

#[derive(Clone, Debug, PartialEq)]
pub struct GroupBoxConfiguration<'a> {
    pub variant: GroupBoxVariant,
    pub title: &'a str,
}

impl<'a> GroupBoxConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let variant = match fields.next()? { "normal" => GroupBoxVariant::Normal, "fill" => GroupBoxVariant::Fill, "outline" => GroupBoxVariant::Outline, _ => return None };
        let title = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            variant,
            title,
        })
    }
}

pub const COMPONENT_LABEL: &str = "label";

#[derive(Clone, Debug, PartialEq)]
pub struct LabelConfiguration<'a> {
    pub text: &'a str,
    pub secondary: &'a str,
    pub masked: bool,
    pub highlight: &'a str,
    pub highlight_prefix: bool,
}

impl<'a> LabelConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let text = fields.next()?;
        let secondary = fields.next()?;
        let masked = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let highlight = fields.next()?;
        let highlight_prefix = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            text,
            secondary,
            masked,
            highlight,
            highlight_prefix,
        })
    }
}

pub const COMPONENT_KBD: &str = "kbd";

#[derive(Clone, Debug, PartialEq)]
pub struct KbdConfiguration<'a> {
    pub keystroke: &'a str,
    pub appearance: bool,
    pub outline: bool,
}

impl<'a> KbdConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let keystroke = fields.next()?;
        let appearance = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let outline = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            keystroke,
            appearance,
            outline,
        })
    }
}

pub const COMPONENT_LINK: &str = "link";
pub const LINK_EVENT_CLICKED: u16 = 1;

#[derive(Clone, Debug, PartialEq)]
pub struct LinkConfiguration<'a> {
    pub href: &'a str,
    pub clicked_event: u64,
}

impl<'a> LinkConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let href = fields.next()?;
        let clicked_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            href,
            clicked_event,
        })
    }
}

pub const COMPONENT_AVATAR: &str = "avatar";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AvatarSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AvatarConfiguration<'a> {
    pub size: AvatarSize,
    pub name: &'a str,
    pub source: &'a str,
}

impl<'a> AvatarConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => AvatarSize::Xsmall, "small" => AvatarSize::Small, "medium" => AvatarSize::Medium, "large" => AvatarSize::Large, _ => return None };
        let name = fields.next()?;
        let source = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            name,
            source,
        })
    }
}

pub const COMPONENT_SHIMMER_TEXT: &str = "shimmer_text";

#[derive(Clone, Debug, PartialEq)]
pub struct ShimmerTextConfiguration<'a> {
    pub text: &'a str,
    pub duration_ms: u32,
    pub reverse: bool,
    pub once: bool,
    pub color: &'a str,
}

impl<'a> ShimmerTextConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let text = fields.next()?;
        let duration_ms = fields.next()?.parse::<u32>().ok()?;
        let reverse = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let once = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            text,
            duration_ms,
            reverse,
            once,
            color,
        })
    }
}

pub const COMPONENT_SWITCH: &str = "switch";
pub const SWITCH_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SwitchSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SwitchConfiguration<'a> {
    pub size: SwitchSize,
    pub checked: bool,
    pub disabled: bool,
    pub label: &'a str,
    pub accessibility_label: &'a str,
    pub tooltip: &'a str,
    pub color: &'a str,
    pub changed_event: u64,
}

impl<'a> SwitchConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => SwitchSize::Xsmall, "small" => SwitchSize::Small, "medium" => SwitchSize::Medium, "large" => SwitchSize::Large, _ => return None };
        let checked = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let accessibility_label = fields.next()?;
        let tooltip = fields.next()?;
        let color = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            checked,
            disabled,
            label,
            accessibility_label,
            tooltip,
            color,
            changed_event,
        })
    }
}

pub const COMPONENT_CHECKBOX: &str = "checkbox";
pub const CHECKBOX_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CheckboxSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CheckboxConfiguration<'a> {
    pub size: CheckboxSize,
    pub checked: bool,
    pub disabled: bool,
    pub label: &'a str,
    pub accessibility_label: &'a str,
    pub tooltip: &'a str,
    pub changed_event: u64,
}

impl<'a> CheckboxConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => CheckboxSize::Xsmall, "small" => CheckboxSize::Small, "medium" => CheckboxSize::Medium, "large" => CheckboxSize::Large, _ => return None };
        let checked = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let accessibility_label = fields.next()?;
        let tooltip = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            checked,
            disabled,
            label,
            accessibility_label,
            tooltip,
            changed_event,
        })
    }
}

pub const COMPONENT_RADIO: &str = "radio";
pub const RADIO_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RadioSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RadioConfiguration<'a> {
    pub size: RadioSize,
    pub checked: bool,
    pub disabled: bool,
    pub label: &'a str,
    pub accessibility_label: &'a str,
    pub tooltip: &'a str,
    pub changed_event: u64,
}

impl<'a> RadioConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => RadioSize::Xsmall, "small" => RadioSize::Small, "medium" => RadioSize::Medium, "large" => RadioSize::Large, _ => return None };
        let checked = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let accessibility_label = fields.next()?;
        let tooltip = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            checked,
            disabled,
            label,
            accessibility_label,
            tooltip,
            changed_event,
        })
    }
}

pub const COMPONENT_TOGGLE: &str = "toggle";
pub const TOGGLE_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ToggleSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ToggleVariant {
    Ghost,
    Outline,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ToggleConfiguration<'a> {
    pub size: ToggleSize,
    pub variant: ToggleVariant,
    pub checked: bool,
    pub disabled: bool,
    pub label: &'a str,
    pub tooltip: &'a str,
    pub changed_event: u64,
}

impl<'a> ToggleConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ToggleSize::Xsmall, "small" => ToggleSize::Small, "medium" => ToggleSize::Medium, "large" => ToggleSize::Large, _ => return None };
        let variant = match fields.next()? { "ghost" => ToggleVariant::Ghost, "outline" => ToggleVariant::Outline, _ => return None };
        let checked = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let tooltip = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            checked,
            disabled,
            label,
            tooltip,
            changed_event,
        })
    }
}

pub const COMPONENT_PAGINATION: &str = "pagination";
pub const PAGINATION_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PaginationSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PaginationConfiguration {
    pub size: PaginationSize,
    pub current_page: u32,
    pub total_pages: u32,
    pub visible_pages: u32,
    pub disabled: bool,
    pub compact: bool,
    pub changed_event: u64,
}

impl PaginationConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => PaginationSize::Xsmall, "small" => PaginationSize::Small, "medium" => PaginationSize::Medium, "large" => PaginationSize::Large, _ => return None };
        let current_page = fields.next()?.parse::<u32>().ok()?;
        let total_pages = fields.next()?.parse::<u32>().ok()?;
        let visible_pages = fields.next()?.parse::<u32>().ok()?;
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let compact = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            current_page,
            total_pages,
            visible_pages,
            disabled,
            compact,
            changed_event,
        })
    }
}

pub const COMPONENT_COLLAPSIBLE: &str = "collapsible";

#[derive(Clone, Debug, PartialEq)]
pub struct CollapsibleConfiguration {
    pub open: bool,
    pub animated: bool,
}

impl CollapsibleConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let open = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let animated = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            open,
            animated,
        })
    }
}

pub const COMPONENT_EMPTY: &str = "empty";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EmptyMediaVariant {
    Default,
    Icon,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EmptyConfiguration<'a> {
    pub media_variant: EmptyMediaVariant,
    pub title: &'a str,
    pub description: String,
    pub has_media: bool,
    pub has_content: bool,
    pub has_footer: bool,
}

impl<'a> EmptyConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let media_variant = match fields.next()? { "default" => EmptyMediaVariant::Default, "icon" => EmptyMediaVariant::Icon, _ => return None };
        let title = fields.next()?;
        let description = serde_json::from_str::<String>(fields.next()?).ok()?;
        let has_media = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_content = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_footer = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        if description.contains('\0') {
            return None;
        }
        Some(Self {
            media_variant,
            title,
            description,
            has_media,
            has_content,
            has_footer,
        })
    }
}

pub const COMPONENT_TOOLBAR: &str = "toolbar";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ToolbarSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ToolbarConfiguration {
    pub size: ToolbarSize,
    pub disabled: bool,
}

impl ToolbarConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ToolbarSize::Xsmall, "small" => ToolbarSize::Small, "medium" => ToolbarSize::Medium, "large" => ToolbarSize::Large, _ => return None };
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            disabled,
        })
    }
}

pub const COMPONENT_TOOLBAR_GROUP: &str = "toolbar_group";

#[derive(Clone, Debug, PartialEq)]
pub struct ToolbarGroupConfiguration<'a> {
    pub label: &'a str,
}

impl<'a> ToolbarGroupConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let label = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            label,
        })
    }
}

pub const COMPONENT_STATUS_BAR: &str = "status_bar";

#[derive(Clone, Debug, PartialEq)]
pub struct StatusBarConfiguration {
    pub has_left: bool,
    pub has_center: bool,
    pub has_right: bool,
}

impl StatusBarConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let has_left = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_center = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_right = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            has_left,
            has_center,
            has_right,
        })
    }
}

pub const COMPONENT_BUBBLE: &str = "bubble";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BubbleVariant {
    Filled,
    Secondary,
    Muted,
    Tinted,
    Outline,
    Ghost,
    Destructive,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BubbleAlignment {
    Inherit,
    Start,
    End,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BubbleReactionSide {
    Top,
    Bottom,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BubbleReactionAlignment {
    Start,
    End,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BubbleConfiguration {
    pub variant: BubbleVariant,
    pub alignment: BubbleAlignment,
    pub reaction_side: BubbleReactionSide,
    pub reaction_alignment: BubbleReactionAlignment,
    pub has_content: bool,
    pub has_reactions: bool,
}

impl BubbleConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let variant = match fields.next()? { "filled" => BubbleVariant::Filled, "secondary" => BubbleVariant::Secondary, "muted" => BubbleVariant::Muted, "tinted" => BubbleVariant::Tinted, "outline" => BubbleVariant::Outline, "ghost" => BubbleVariant::Ghost, "destructive" => BubbleVariant::Destructive, _ => return None };
        let alignment = match fields.next()? { "inherit" => BubbleAlignment::Inherit, "start" => BubbleAlignment::Start, "end" => BubbleAlignment::End, _ => return None };
        let reaction_side = match fields.next()? { "top" => BubbleReactionSide::Top, "bottom" => BubbleReactionSide::Bottom, _ => return None };
        let reaction_alignment = match fields.next()? { "start" => BubbleReactionAlignment::Start, "end" => BubbleReactionAlignment::End, _ => return None };
        let has_content = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_reactions = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            variant,
            alignment,
            reaction_side,
            reaction_alignment,
            has_content,
            has_reactions,
        })
    }
}

pub const COMPONENT_BUBBLE_GROUP: &str = "bubble_group";

#[derive(Clone, Debug, PartialEq)]
pub struct BubbleGroupConfiguration {
}

impl BubbleGroupConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        if value.is_empty() { Some(Self {}) } else { None }
    }
}

pub const COMPONENT_MESSAGE: &str = "message";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MessageAlignment {
    Start,
    End,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MessageConfiguration {
    pub alignment: MessageAlignment,
    pub accessible_list_item: bool,
    pub content_has_ghost_surface: bool,
    pub has_avatar: bool,
    pub has_header: bool,
    pub has_content: bool,
    pub has_footer: bool,
}

impl MessageConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let alignment = match fields.next()? { "start" => MessageAlignment::Start, "end" => MessageAlignment::End, _ => return None };
        let accessible_list_item = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let content_has_ghost_surface = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_avatar = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_header = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_content = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_footer = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            alignment,
            accessible_list_item,
            content_has_ghost_surface,
            has_avatar,
            has_header,
            has_content,
            has_footer,
        })
    }
}

pub const COMPONENT_MESSAGE_GROUP: &str = "message_group";

#[derive(Clone, Debug, PartialEq)]
pub struct MessageGroupConfiguration {
}

impl MessageGroupConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        if value.is_empty() { Some(Self {}) } else { None }
    }
}

pub const COMPONENT_MARKER: &str = "marker";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MarkerVariant {
    Plain,
    Separator,
    Border,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MarkerAlignment {
    Inherit,
    Start,
    Center,
    End,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MarkerLoadingStyle {
    Spinner,
    Shimmer,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MarkerConfiguration<'a> {
    pub variant: MarkerVariant,
    pub alignment: MarkerAlignment,
    pub loading: bool,
    pub loading_style: MarkerLoadingStyle,
    pub status_role: bool,
    pub text: &'a str,
    pub has_icon: bool,
    pub has_extra: bool,
}

impl<'a> MarkerConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let variant = match fields.next()? { "plain" => MarkerVariant::Plain, "separator" => MarkerVariant::Separator, "border" => MarkerVariant::Border, _ => return None };
        let alignment = match fields.next()? { "inherit" => MarkerAlignment::Inherit, "start" => MarkerAlignment::Start, "center" => MarkerAlignment::Center, "end" => MarkerAlignment::End, _ => return None };
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let loading_style = match fields.next()? { "spinner" => MarkerLoadingStyle::Spinner, "shimmer" => MarkerLoadingStyle::Shimmer, _ => return None };
        let status_role = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let text = fields.next()?;
        let has_icon = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let has_extra = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            variant,
            alignment,
            loading,
            loading_style,
            status_role,
            text,
            has_icon,
            has_extra,
        })
    }
}

pub const COMPONENT_ICON: &str = "icon";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IconSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IconConfiguration<'a> {
    pub size: IconSize,
    pub asset_path: &'a str,
    pub color: &'a str,
}

impl<'a> IconConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => IconSize::Xsmall, "small" => IconSize::Small, "medium" => IconSize::Medium, "large" => IconSize::Large, _ => return None };
        let asset_path = fields.next()?;
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            asset_path,
            color,
        })
    }
}

pub const COMPONENT_DESCRIPTION_LIST: &str = "description_list";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DescriptionListSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DescriptionListAxis {
    Horizontal,
    Vertical,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DescriptionListConfiguration {
    pub size: DescriptionListSize,
    pub axis: DescriptionListAxis,
    pub label_width_pixels: f32,
    pub bordered: bool,
    pub columns: u32,
    pub entry_spans: Vec<u32>,
}

impl DescriptionListConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => DescriptionListSize::Xsmall, "small" => DescriptionListSize::Small, "medium" => DescriptionListSize::Medium, "large" => DescriptionListSize::Large, _ => return None };
        let axis = match fields.next()? { "horizontal" => DescriptionListAxis::Horizontal, "vertical" => DescriptionListAxis::Vertical, _ => return None };
        let label_width_pixels = fields.next()?.parse::<f32>().ok()?;
        let bordered = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let columns = fields.next()?.parse::<u32>().ok()?;
        let entry_spans_source = fields.next()?;
        let entry_spans = if entry_spans_source.is_empty() { Vec::new() } else { entry_spans_source.split(',').map(|item| item.parse::<u32>().ok()).collect::<Option<Vec<_>>>()? };
        if fields.next().is_some() {
            return None;
        }
        if !label_width_pixels.is_finite() {
            return None;
        }
        Some(Self {
            size,
            axis,
            label_width_pixels,
            bordered,
            columns,
            entry_spans,
        })
    }
}

pub const COMPONENT_TABS: &str = "tabs";
pub const TABS_EVENT_SELECTED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TabsSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TabsVariant {
    Tab,
    Outline,
    Pill,
    Segmented,
    Underline,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TabsConfiguration {
    pub size: TabsSize,
    pub variant: TabsVariant,
    pub labels: Vec<String>,
    pub item_ids: Vec<u32>,
    pub item_disabled: Vec<u32>,
    pub selected_id: u32,
    pub has_selection: bool,
    pub overflow_menu: bool,
    pub selected_event: u64,
}

impl TabsConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => TabsSize::Xsmall, "small" => TabsSize::Small, "medium" => TabsSize::Medium, "large" => TabsSize::Large, _ => return None };
        let variant = match fields.next()? { "tab" => TabsVariant::Tab, "outline" => TabsVariant::Outline, "pill" => TabsVariant::Pill, "segmented" => TabsVariant::Segmented, "underline" => TabsVariant::Underline, _ => return None };
        let labels = serde_json::from_str::<Vec<String>>(fields.next()?).ok()?;
        let item_ids_source = fields.next()?;
        let item_ids = if item_ids_source.is_empty() { Vec::new() } else { item_ids_source.split(',').map(|item| item.parse::<u32>().ok()).collect::<Option<Vec<_>>>()? };
        let item_disabled_source = fields.next()?;
        let item_disabled = if item_disabled_source.is_empty() { Vec::new() } else { item_disabled_source.split(',').map(|item| item.parse::<u32>().ok()).collect::<Option<Vec<_>>>()? };
        let selected_id = fields.next()?.parse::<u32>().ok()?;
        let has_selection = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let overflow_menu = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let selected_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            labels,
            item_ids,
            item_disabled,
            selected_id,
            has_selection,
            overflow_menu,
            selected_event,
        })
    }
}

pub const COMPONENT_BREADCRUMB: &str = "breadcrumb";
pub const BREADCRUMB_EVENT_CLICKED: u16 = 1;

#[derive(Clone, Debug, PartialEq)]
pub struct BreadcrumbConfiguration {
    pub labels: Vec<String>,
    pub item_ids: Vec<u32>,
    pub item_disabled: Vec<u32>,
    pub clicked_event: u64,
}

impl BreadcrumbConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let labels = serde_json::from_str::<Vec<String>>(fields.next()?).ok()?;
        let item_ids_source = fields.next()?;
        let item_ids = if item_ids_source.is_empty() { Vec::new() } else { item_ids_source.split(',').map(|item| item.parse::<u32>().ok()).collect::<Option<Vec<_>>>()? };
        let item_disabled_source = fields.next()?;
        let item_disabled = if item_disabled_source.is_empty() { Vec::new() } else { item_disabled_source.split(',').map(|item| item.parse::<u32>().ok()).collect::<Option<Vec<_>>>()? };
        let clicked_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            labels,
            item_ids,
            item_disabled,
            clicked_event,
        })
    }
}
