// @generated by Gpui.Bindings.Generator. Do not edit.
pub const EXTENSION_ID: &str = "gpui.net.components";
pub const SCHEMA_VERSION: u32 = 1;
pub const SCHEMA_HASH: u64 = 0x96D6AEE59A1C9B2C;

pub const COMPONENT_SPINNER: &str = "spinner";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerIcon {
    Loader,
    LoaderCircle,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SpinnerEase {
    Linear,
    EaseInOut,
    EaseOutQuint,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpinnerConfiguration<'a> {
    pub size: SpinnerSize,
    pub icon: SpinnerIcon,
    pub ease: SpinnerEase,
    pub color: &'a str,
}

impl<'a> SpinnerConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => SpinnerSize::Xsmall, "small" => SpinnerSize::Small, "medium" => SpinnerSize::Medium, "large" => SpinnerSize::Large, _ => return None };
        let icon = match fields.next()? { "loader" => SpinnerIcon::Loader, "loader_circle" => SpinnerIcon::LoaderCircle, _ => return None };
        let ease = match fields.next()? { "linear" => SpinnerEase::Linear, "ease_in_out" => SpinnerEase::EaseInOut, "ease_out_quint" => SpinnerEase::EaseOutQuint, _ => return None };
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            icon,
            ease,
            color,
        })
    }
}

pub const COMPONENT_SKELETON: &str = "skeleton";

#[derive(Clone, Debug, PartialEq)]
pub struct SkeletonConfiguration {
    pub secondary: bool,
}

impl SkeletonConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let secondary = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            secondary,
        })
    }
}

pub const COMPONENT_SEPARATOR: &str = "separator";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeparatorOrientation {
    Horizontal,
    Vertical,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SeparatorConfiguration<'a> {
    pub orientation: SeparatorOrientation,
    pub dashed: bool,
    pub label: &'a str,
    pub color: &'a str,
}

impl<'a> SeparatorConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let orientation = match fields.next()? { "horizontal" => SeparatorOrientation::Horizontal, "vertical" => SeparatorOrientation::Vertical, _ => return None };
        let dashed = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let label = fields.next()?;
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            orientation,
            dashed,
            label,
            color,
        })
    }
}

pub const COMPONENT_BADGE: &str = "badge";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BadgeSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BadgeConfiguration<'a> {
    pub size: BadgeSize,
    pub dot: bool,
    pub count: u32,
    pub max: u32,
    pub color: &'a str,
}

impl<'a> BadgeConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => BadgeSize::Xsmall, "small" => BadgeSize::Small, "medium" => BadgeSize::Medium, "large" => BadgeSize::Large, _ => return None };
        let dot = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let count = fields.next()?.parse::<u32>().ok()?;
        let max = fields.next()?.parse::<u32>().ok()?;
        let color = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            dot,
            count,
            max,
            color,
        })
    }
}

pub const COMPONENT_TAG: &str = "tag";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TagSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TagVariant {
    Primary,
    Secondary,
    Danger,
    Success,
    Warning,
    Info,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TagConfiguration {
    pub size: TagSize,
    pub variant: TagVariant,
    pub outline: bool,
    pub rounded_full: bool,
}

impl TagConfiguration {
    pub fn parse(value: &str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => TagSize::Xsmall, "small" => TagSize::Small, "medium" => TagSize::Medium, "large" => TagSize::Large, _ => return None };
        let variant = match fields.next()? { "primary" => TagVariant::Primary, "secondary" => TagVariant::Secondary, "danger" => TagVariant::Danger, "success" => TagVariant::Success, "warning" => TagVariant::Warning, "info" => TagVariant::Info, _ => return None };
        let outline = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let rounded_full = match fields.next()? { "0" => false, "1" => true, _ => return None };
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            outline,
            rounded_full,
        })
    }
}

pub const COMPONENT_PROGRESS: &str = "progress";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProgressSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProgressConfiguration<'a> {
    pub size: ProgressSize,
    pub value: f32,
    pub loading: bool,
    pub color: &'a str,
    pub accessibility_label: &'a str,
}

impl<'a> ProgressConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ProgressSize::Xsmall, "small" => ProgressSize::Small, "medium" => ProgressSize::Medium, "large" => ProgressSize::Large, _ => return None };
        let value = fields.next()?.parse::<f32>().ok()?;
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let accessibility_label = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        if !value.is_finite() {
            return None;
        }
        Some(Self {
            size,
            value,
            loading,
            color,
            accessibility_label,
        })
    }
}

pub const COMPONENT_PROGRESS_CIRCLE: &str = "progress_circle";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProgressCircleSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProgressCircleConfiguration<'a> {
    pub size: ProgressCircleSize,
    pub value: f32,
    pub loading: bool,
    pub color: &'a str,
    pub accessibility_label: &'a str,
}

impl<'a> ProgressCircleConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ProgressCircleSize::Xsmall, "small" => ProgressCircleSize::Small, "medium" => ProgressCircleSize::Medium, "large" => ProgressCircleSize::Large, _ => return None };
        let value = fields.next()?.parse::<f32>().ok()?;
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let accessibility_label = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        if !value.is_finite() {
            return None;
        }
        Some(Self {
            size,
            value,
            loading,
            color,
            accessibility_label,
        })
    }
}

pub const COMPONENT_RATING: &str = "rating";
pub const RATING_EVENT_CHANGED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RatingSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RatingConfiguration<'a> {
    pub size: RatingSize,
    pub value: u32,
    pub max: u32,
    pub disabled: bool,
    pub color: &'a str,
    pub changed_event: u64,
}

impl<'a> RatingConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => RatingSize::Xsmall, "small" => RatingSize::Small, "medium" => RatingSize::Medium, "large" => RatingSize::Large, _ => return None };
        let value = fields.next()?.parse::<u32>().ok()?;
        let max = fields.next()?.parse::<u32>().ok()?;
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let color = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            value,
            max,
            disabled,
            color,
            changed_event,
        })
    }
}

pub const COMPONENT_BUTTON: &str = "button";
pub const BUTTON_EVENT_CLICKED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonVariant {
    Default,
    Primary,
    Secondary,
    Danger,
    Success,
    Warning,
    Info,
    Ghost,
    Link,
    Text,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ButtonConfiguration<'a> {
    pub size: ButtonSize,
    pub variant: ButtonVariant,
    pub label: &'a str,
    pub accessibility_label: &'a str,
    pub disabled: bool,
    pub selected: bool,
    pub loading: bool,
    pub outline: bool,
    pub compact: bool,
    pub clicked_event: u64,
}

impl<'a> ButtonConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => ButtonSize::Xsmall, "small" => ButtonSize::Small, "medium" => ButtonSize::Medium, "large" => ButtonSize::Large, _ => return None };
        let variant = match fields.next()? { "default" => ButtonVariant::Default, "primary" => ButtonVariant::Primary, "secondary" => ButtonVariant::Secondary, "danger" => ButtonVariant::Danger, "success" => ButtonVariant::Success, "warning" => ButtonVariant::Warning, "info" => ButtonVariant::Info, "ghost" => ButtonVariant::Ghost, "link" => ButtonVariant::Link, "text" => ButtonVariant::Text, _ => return None };
        let label = fields.next()?;
        let accessibility_label = fields.next()?;
        let disabled = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let selected = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let loading = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let outline = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let compact = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let clicked_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            label,
            accessibility_label,
            disabled,
            selected,
            loading,
            outline,
            compact,
            clicked_event,
        })
    }
}

pub const COMPONENT_ALERT: &str = "alert";
pub const ALERT_EVENT_CLOSED: u16 = 1;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AlertSize {
    Xsmall,
    Small,
    Medium,
    Large,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AlertVariant {
    Default,
    Info,
    Success,
    Warning,
    Error,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AlertConfiguration<'a> {
    pub size: AlertSize,
    pub variant: AlertVariant,
    pub title: &'a str,
    pub message: &'a str,
    pub banner: bool,
    pub closed_event: u64,
}

impl<'a> AlertConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let size = match fields.next()? { "xsmall" => AlertSize::Xsmall, "small" => AlertSize::Small, "medium" => AlertSize::Medium, "large" => AlertSize::Large, _ => return None };
        let variant = match fields.next()? { "default" => AlertVariant::Default, "info" => AlertVariant::Info, "success" => AlertVariant::Success, "warning" => AlertVariant::Warning, "error" => AlertVariant::Error, _ => return None };
        let title = fields.next()?;
        let message = fields.next()?;
        let banner = match fields.next()? { "0" => false, "1" => true, _ => return None };
        let closed_event = fields.next()?.parse::<u64>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            size,
            variant,
            title,
            message,
            banner,
            closed_event,
        })
    }
}

pub const COMPONENT_GROUP_BOX: &str = "group_box";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GroupBoxVariant {
    Normal,
    Fill,
    Outline,
}

#[derive(Clone, Debug, PartialEq)]
pub struct GroupBoxConfiguration<'a> {
    pub variant: GroupBoxVariant,
    pub title: &'a str,
}

impl<'a> GroupBoxConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let variant = match fields.next()? { "normal" => GroupBoxVariant::Normal, "fill" => GroupBoxVariant::Fill, "outline" => GroupBoxVariant::Outline, _ => return None };
        let title = fields.next()?;
        if fields.next().is_some() {
            return None;
        }
        Some(Self {
            variant,
            title,
        })
    }
}
