<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Deterministic>true</Deterministic>
        <Version>0.2.0-preview.1</Version>
        <Authors>Akito Inoue</Authors>
        <Copyright>Copyright (c) 2026 Akito Inoue</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://github.com/akeit0/gpui-dotnet</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/akeit0/gpui-dotnet</RepositoryUrl>
    </PropertyGroup>
</Project>
