// @generated by Gpui.Bindings.Generator. Do not edit.
pub const EXTENSION_ID: &str = "gpui.net.editor";
pub const SCHEMA_VERSION: u32 = 3;
pub const SCHEMA_HASH: u64 = 0x7274911E03D21DF5;

pub const COMPONENT_EDITOR: &str = "editor";
pub const EDITOR_FLAG_DISABLED: u32 = 1 << 0;
pub const EDITOR_FLAG_READ_ONLY: u32 = 1 << 1;
pub const EDITOR_FLAG_LINE_NUMBERS: u32 = 1 << 2;
pub const EDITOR_FLAG_FOLDING: u32 = 1 << 3;
pub const EDITOR_FLAG_SHOW_WHITESPACE: u32 = 1 << 4;
pub const EDITOR_COMMAND_BOOTSTRAP: u16 = 1;
pub const EDITOR_EVENT_CHANGED: u16 = 1;
pub const EDITOR_KNOWN_FLAGS: u32 = EDITOR_FLAG_DISABLED
    | EDITOR_FLAG_READ_ONLY
    | EDITOR_FLAG_LINE_NUMBERS
    | EDITOR_FLAG_FOLDING
    | EDITOR_FLAG_SHOW_WHITESPACE;
