// @generated by Gpui.Bindings.Generator. Do not edit.
pub const EXTENSION_ID: &str = "gpui.net.editor";
pub const SCHEMA_VERSION: u32 = 6;
pub const SCHEMA_HASH: u64 = 0x5441198555E07694;

pub const COMPONENT_EDITOR: &str = "editor";
pub const EDITOR_FLAG_DISABLED: u32 = 1 << 0;
pub const EDITOR_FLAG_READ_ONLY: u32 = 1 << 1;
pub const EDITOR_FLAG_LINE_NUMBERS: u32 = 1 << 2;
pub const EDITOR_FLAG_FOLDING: u32 = 1 << 3;
pub const EDITOR_FLAG_SHOW_WHITESPACE: u32 = 1 << 4;
pub const EDITOR_COMMAND_BOOTSTRAP: u16 = 1;
pub const EDITOR_COMMAND_FOCUS: u16 = 2;
pub const EDITOR_COMMAND_SET_SELECTION: u16 = 3;
pub const EDITOR_COMMAND_REPLACE_DOCUMENT: u16 = 4;
pub const EDITOR_COMMAND_APPLY_EDIT: u16 = 5;
pub const EDITOR_EVENT_CHANGED: u16 = 1;
pub const EDITOR_EVENT_COMMAND_REJECTED: u16 = 2;
pub const EDITOR_KNOWN_FLAGS: u32 = EDITOR_FLAG_DISABLED
    | EDITOR_FLAG_READ_ONLY
    | EDITOR_FLAG_LINE_NUMBERS
    | EDITOR_FLAG_FOLDING
    | EDITOR_FLAG_SHOW_WHITESPACE;

#[derive(Clone, Debug, PartialEq)]
pub struct EditorConfiguration<'a> {
    pub flags: u32,
    pub language: &'a str,
    pub changed_event: u64,
    pub command_rejected_event: u64,
    pub line_number_width: f32,
}

impl<'a> EditorConfiguration<'a> {
    pub fn parse(value: &'a str) -> Option<Self> {
        let mut fields = value.split('\n');
        let flags = fields.next()?.parse::<u32>().ok()?;
        let language = fields.next()?;
        let changed_event = fields.next()?.parse::<u64>().ok()?;
        let command_rejected_event = fields.next()?.parse::<u64>().ok()?;
        let line_number_width = fields.next()?.parse::<f32>().ok()?;
        if fields.next().is_some() {
            return None;
        }
        if flags & !EDITOR_KNOWN_FLAGS != 0 {
            return None;
        }
        if !line_number_width.is_finite() {
            return None;
        }
        Some(Self {
            flags,
            language,
            changed_event,
            command_rejected_event,
            line_number_width,
        })
    }
}
