// @generated by Gpui.Bindings.Generator. Do not edit.
#![allow(dead_code)]
pub const SCHEMA_VERSION: u32 = 1;
pub const SCHEMA_HASH: u64 = 0xB0995FB52F136566;

pub const CAPABILITY_ACCESSIBLE: u64 = 0x0000000000000001;
pub const CAPABILITY_CHECKABLE: u64 = 0x0000000000000002;
pub const CAPABILITY_CONTEXT_MENU: u64 = 0x0000000000000004;
pub const CAPABILITY_DISABLEABLE: u64 = 0x0000000000000008;
pub const CAPABILITY_DOCK_AREA: u64 = 0x0000000000000010;
pub const CAPABILITY_DOCK_CONTAINER: u64 = 0x0000000000000020;
pub const CAPABILITY_DOCK_PANEL: u64 = 0x0000000000000040;
pub const CAPABILITY_DOCK_REGION: u64 = 0x0000000000000080;
pub const CAPABILITY_DOCK_SPLIT: u64 = 0x0000000000000100;
pub const CAPABILITY_DOCK_TABS: u64 = 0x0000000000000200;
pub const CAPABILITY_DRAWING: u64 = 0x0000000000000400;
pub const CAPABILITY_DYNAMIC: u64 = 0x0000000000000800;
pub const CAPABILITY_EXTENSION: u64 = 0x0000000000001000;
pub const CAPABILITY_FOCUS_TARGET: u64 = 0x0000000000002000;
pub const CAPABILITY_IMAGE: u64 = 0x0000000000004000;
pub const CAPABILITY_INPUT: u64 = 0x0000000000008000;
pub const CAPABILITY_INTERACTIVE: u64 = 0x0000000000010000;
pub const CAPABILITY_KEY_MOUSE: u64 = 0x0000000000020000;
pub const CAPABILITY_LAYOUT: u64 = 0x0000000000040000;
pub const CAPABILITY_NATIVE_STATE: u64 = 0x0000000000080000;
pub const CAPABILITY_OVERLAY: u64 = 0x0000000000100000;
pub const CAPABILITY_PARENT: u64 = 0x0000000000200000;
pub const CAPABILITY_PATH: u64 = 0x0000000000400000;
pub const CAPABILITY_POPOVER_MENU: u64 = 0x0000000000800000;
pub const CAPABILITY_SCROLLABLE: u64 = 0x0000000001000000;
pub const CAPABILITY_SHORTCUT_SCOPE: u64 = 0x0000000002000000;
pub const CAPABILITY_SLIDER: u64 = 0x0000000004000000;
pub const CAPABILITY_STYLED: u64 = 0x0000000008000000;
pub const CAPABILITY_TABLE: u64 = 0x0000000010000000;
pub const CAPABILITY_TOOLTIP: u64 = 0x0000000020000000;
pub const CAPABILITY_TOOLTIP_OPTIONS: u64 = 0x0000000040000000;
pub const CAPABILITY_VIRTUALIZED: u64 = 0x0000000080000000;
pub const CAPABILITY_WINDOW_CONTROL: u64 = 0x0000000100000000;

pub const COMPONENT_DIV: u16 = 1;
pub const COMPONENT_TEXT: u16 = 2;
pub const COMPONENT_SPACER: u16 = 3;
pub const COMPONENT_DIVIDER: u16 = 4;
pub const COMPONENT_BADGE: u16 = 5;
pub const COMPONENT_BUTTON: u16 = 6;
pub const COMPONENT_CHECKBOX: u16 = 7;
pub const COMPONENT_RADIO: u16 = 8;
pub const COMPONENT_SCROLL: u16 = 9;
pub const COMPONENT_LIST: u16 = 10;
pub const COMPONENT_TABLE: u16 = 11;
pub const COMPONENT_INPUT: u16 = 12;
pub const COMPONENT_SLIDER: u16 = 13;
pub const COMPONENT_IMAGE: u16 = 14;
pub const COMPONENT_DRAWING: u16 = 15;
pub const COMPONENT_PATH: u16 = 16;
pub const COMPONENT_DYNAMIC: u16 = 17;
pub const COMPONENT_OVERLAY: u16 = 18;
pub const COMPONENT_TOOLTIP: u16 = 19;
pub const COMPONENT_CONTEXT_MENU: u16 = 20;
pub const COMPONENT_POPOVER_MENU: u16 = 21;
pub const COMPONENT_DOCK_AREA: u16 = 22;
pub const COMPONENT_DOCK_SPLIT: u16 = 23;
pub const COMPONENT_DOCK_TABS: u16 = 24;
pub const COMPONENT_DOCK_PANEL: u16 = 25;
pub const COMPONENT_DOCK_REGION: u16 = 26;
pub const COMPONENT_NATIVE_EXTENSION: u16 = 27;

pub const OP_ELEMENT_OWNER: u16 = 1;
pub const OP_RESOURCE_OWNER: u16 = 2;
pub const OP_ALIGN_CONTENT: u16 = 100;
pub const OP_DISPLAY_NONE: u16 = 101;
pub const OP_FLEX: u16 = 102;
pub const OP_FLEX_BASIS_PERCENT: u16 = 103;
pub const OP_FLEX_BASIS_PX: u16 = 104;
pub const OP_FLEX_GROW: u16 = 105;
pub const OP_FLEX_SHRINK: u16 = 106;
pub const OP_FLEX_WRAP: u16 = 107;
pub const OP_ITEMS_BASELINE: u16 = 108;
pub const OP_ITEMS_CENTER: u16 = 109;
pub const OP_ITEMS_END: u16 = 110;
pub const OP_ITEMS_START: u16 = 111;
pub const OP_ITEMS_STRETCH: u16 = 112;
pub const OP_JUSTIFY_BETWEEN: u16 = 113;
pub const OP_JUSTIFY_CENTER: u16 = 114;
pub const OP_JUSTIFY_END: u16 = 115;
pub const OP_JUSTIFY_START: u16 = 116;
pub const OP_SELF_BASELINE: u16 = 117;
pub const OP_SELF_CENTER: u16 = 118;
pub const OP_SELF_END: u16 = 119;
pub const OP_SELF_FLEX_END: u16 = 120;
pub const OP_SELF_FLEX_START: u16 = 121;
pub const OP_SELF_START: u16 = 122;
pub const OP_SELF_STRETCH: u16 = 123;
pub const OP_V_STACK: u16 = 124;
pub const OP_ABSOLUTE: u16 = 200;
pub const OP_ASPECT_RATIO: u16 = 201;
pub const OP_BOTTOM_PERCENT: u16 = 202;
pub const OP_BOTTOM_PX: u16 = 203;
pub const OP_HEIGHT_PERCENT: u16 = 204;
pub const OP_HEIGHT_PX: u16 = 205;
pub const OP_INSET_PERCENT: u16 = 206;
pub const OP_INSET_PX: u16 = 207;
pub const OP_LEFT_PERCENT: u16 = 208;
pub const OP_LEFT_PX: u16 = 209;
pub const OP_MAX_HEIGHT_PERCENT: u16 = 210;
pub const OP_MAX_HEIGHT_PX: u16 = 211;
pub const OP_MAX_WIDTH_PERCENT: u16 = 212;
pub const OP_MAX_WIDTH_PX: u16 = 213;
pub const OP_MIN_HEIGHT_PERCENT: u16 = 214;
pub const OP_MIN_HEIGHT_PX: u16 = 215;
pub const OP_MIN_WIDTH_PERCENT: u16 = 216;
pub const OP_MIN_WIDTH_PX: u16 = 217;
pub const OP_RELATIVE: u16 = 218;
pub const OP_RIGHT_PERCENT: u16 = 219;
pub const OP_RIGHT_PX: u16 = 220;
pub const OP_TOP_PERCENT: u16 = 221;
pub const OP_TOP_PX: u16 = 222;
pub const OP_WIDTH_PERCENT: u16 = 223;
pub const OP_WIDTH_PX: u16 = 224;
pub const OP_GAP_PERCENT: u16 = 300;
pub const OP_GAP_PX: u16 = 301;
pub const OP_GAP_X_PERCENT: u16 = 302;
pub const OP_GAP_X_PX: u16 = 303;
pub const OP_GAP_Y_PERCENT: u16 = 304;
pub const OP_GAP_Y_PX: u16 = 305;
pub const OP_MARGIN_BOTTOM_PERCENT: u16 = 306;
pub const OP_MARGIN_BOTTOM_PX: u16 = 307;
pub const OP_MARGIN_LEFT_PERCENT: u16 = 308;
pub const OP_MARGIN_LEFT_PX: u16 = 309;
pub const OP_MARGIN_PERCENT: u16 = 310;
pub const OP_MARGIN_PX: u16 = 311;
pub const OP_MARGIN_RIGHT_PERCENT: u16 = 312;
pub const OP_MARGIN_RIGHT_PX: u16 = 313;
pub const OP_MARGIN_TOP_PERCENT: u16 = 314;
pub const OP_MARGIN_TOP_PX: u16 = 315;
pub const OP_MARGIN_X_PERCENT: u16 = 316;
pub const OP_MARGIN_X_PX: u16 = 317;
pub const OP_MARGIN_Y_PERCENT: u16 = 318;
pub const OP_MARGIN_Y_PX: u16 = 319;
pub const OP_PADDING_BOTTOM_PERCENT: u16 = 320;
pub const OP_PADDING_BOTTOM_PX: u16 = 321;
pub const OP_PADDING_LEFT_PERCENT: u16 = 322;
pub const OP_PADDING_LEFT_PX: u16 = 323;
pub const OP_PADDING_PERCENT: u16 = 324;
pub const OP_PADDING_PX: u16 = 325;
pub const OP_PADDING_RIGHT_PERCENT: u16 = 326;
pub const OP_PADDING_RIGHT_PX: u16 = 327;
pub const OP_PADDING_TOP_PERCENT: u16 = 328;
pub const OP_PADDING_TOP_PX: u16 = 329;
pub const OP_PADDING_X_PERCENT: u16 = 330;
pub const OP_PADDING_X_PX: u16 = 331;
pub const OP_PADDING_Y_PERCENT: u16 = 332;
pub const OP_PADDING_Y_PX: u16 = 333;
pub const OP_COL_END: u16 = 400;
pub const OP_COL_END_AUTO: u16 = 401;
pub const OP_COL_SPAN: u16 = 402;
pub const OP_COL_SPAN_FULL: u16 = 403;
pub const OP_COL_START: u16 = 404;
pub const OP_COL_START_AUTO: u16 = 405;
pub const OP_DISPLAY_GRID: u16 = 406;
pub const OP_GRID_COLS: u16 = 407;
pub const OP_GRID_COLS_MAX_CONTENT: u16 = 408;
pub const OP_GRID_COLS_MIN_CONTENT: u16 = 409;
pub const OP_GRID_ROWS: u16 = 410;
pub const OP_GRID_ROWS_MAX_CONTENT: u16 = 411;
pub const OP_GRID_ROWS_MIN_CONTENT: u16 = 412;
pub const OP_ROW_END: u16 = 413;
pub const OP_ROW_END_AUTO: u16 = 414;
pub const OP_ROW_SPAN: u16 = 415;
pub const OP_ROW_SPAN_FULL: u16 = 416;
pub const OP_ROW_START: u16 = 417;
pub const OP_ROW_START_AUTO: u16 = 418;
pub const OP_BACKGROUND_RGBA: u16 = 500;
pub const OP_BORDER_RGBA: u16 = 501;
pub const OP_BORDER_STYLE: u16 = 502;
pub const OP_BORDER_WIDTH_PX: u16 = 503;
pub const OP_OPACITY: u16 = 504;
pub const OP_OVERFLOW_HIDDEN: u16 = 505;
pub const OP_OVERFLOW_X_HIDDEN: u16 = 506;
pub const OP_OVERFLOW_Y_HIDDEN: u16 = 507;
pub const OP_RADIUS_BOTTOM_LEFT_PX: u16 = 508;
pub const OP_RADIUS_BOTTOM_RIGHT_PX: u16 = 509;
pub const OP_RADIUS_PX: u16 = 510;
pub const OP_RADIUS_TOP_LEFT_PX: u16 = 511;
pub const OP_RADIUS_TOP_RIGHT_PX: u16 = 512;
pub const OP_SHADOW_BLUR: u16 = 513;
pub const OP_SHADOW_COLOR: u16 = 514;
pub const OP_SHADOW_OFFSET: u16 = 515;
pub const OP_SHADOW_SPREAD: u16 = 516;
pub const OP_VISIBILITY: u16 = 517;
pub const OP_FONT_FALLBACKS: u16 = 600;
pub const OP_FONT_FAMILY: u16 = 601;
pub const OP_FONT_FEATURES: u16 = 602;
pub const OP_FONT_SIZE_PX: u16 = 603;
pub const OP_FONT_STYLE: u16 = 604;
pub const OP_FONT_WEIGHT: u16 = 605;
pub const OP_LINE_CLAMP: u16 = 606;
pub const OP_LINE_HEIGHT_PERCENT: u16 = 607;
pub const OP_LINE_HEIGHT_PX: u16 = 608;
pub const OP_LINE_THROUGH: u16 = 609;
pub const OP_TEXT_ALIGN: u16 = 610;
pub const OP_TEXT_BACKGROUND: u16 = 611;
pub const OP_TEXT_DECORATION_COLOR: u16 = 612;
pub const OP_TEXT_DECORATION_NONE: u16 = 613;
pub const OP_TEXT_DECORATION_SOLID: u16 = 614;
pub const OP_TEXT_DECORATION_WAVY: u16 = 615;
pub const OP_TEXT_ELLIPSIS: u16 = 616;
pub const OP_TEXT_RGBA: u16 = 617;
pub const OP_TEXT_TRUNCATE: u16 = 618;
pub const OP_UNDERLINE: u16 = 619;
pub const OP_WHITE_SPACE: u16 = 620;
pub const OP_ACTIVE_BACKGROUND_RGBA: u16 = 700;
pub const OP_ACTIVE_BORDER_RGBA: u16 = 701;
pub const OP_ACTIVE_TEXT_RGBA: u16 = 702;
pub const OP_CHECKED: u16 = 703;
pub const OP_CURSOR: u16 = 704;
pub const OP_DISABLED: u16 = 705;
pub const OP_HOVER_BACKGROUND_RGBA: u16 = 706;
pub const OP_HOVER_BORDER_RGBA: u16 = 707;
pub const OP_HOVER_TEXT_RGBA: u16 = 708;
pub const OP_ISOLATE_SHORTCUTS: u16 = 709;
pub const OP_ON_CLICK: u16 = 710;
pub const OP_ON_FILE_DROP: u16 = 711;
pub const OP_ON_HOVER: u16 = 712;
pub const OP_ON_KEY_DOWN: u16 = 713;
pub const OP_ON_KEY_UP: u16 = 714;
pub const OP_ON_MODIFIERS_CHANGED: u16 = 715;
pub const OP_ON_MOUSE_DOWN: u16 = 716;
pub const OP_ON_MOUSE_DOWN_OUT: u16 = 717;
pub const OP_ON_MOUSE_MOVE: u16 = 718;
pub const OP_ON_MOUSE_UP: u16 = 719;
pub const OP_ON_MOUSE_UP_OUT: u16 = 720;
pub const OP_ON_SCROLL_WHEEL: u16 = 721;
pub const OP_ON_SHORTCUT: u16 = 722;
pub const OP_WINDOW_CONTROL_AREA: u16 = 723;
pub const OP_ACCESSIBLE_DESCRIPTION: u16 = 800;
pub const OP_ACCESSIBLE_NAME: u16 = 801;
pub const OP_FOCUS_TAB_STOP: u16 = 900;
pub const OP_FOCUS_TARGET: u16 = 901;
pub const OP_SCROLL_AXIS: u16 = 1000;
pub const OP_SCROLLBAR_GUTTER: u16 = 1001;
pub const OP_SCROLLBAR_WIDTH: u16 = 1002;
pub const OP_SHOW_SCROLLBAR: u16 = 1003;
pub const OP_SMOOTH_SCROLL: u16 = 1004;
pub const OP_LIST_ALIGNMENT: u16 = 1100;
pub const OP_LIST_BATCH_SIZE: u16 = 1101;
pub const OP_LIST_CONTENT_REVISION: u16 = 1102;
pub const OP_LIST_ESTIMATED_ITEM_HEIGHT_PX: u16 = 1103;
pub const OP_LIST_ITEM_COUNT: u16 = 1104;
pub const OP_LIST_ITEM_ID: u16 = 1105;
pub const OP_LIST_ON_ACTIVATED: u16 = 1106;
pub const OP_LIST_ON_CONTEXT_MENU_REQUESTED: u16 = 1107;
pub const OP_LIST_ON_SELECTION_REQUESTED: u16 = 1108;
pub const OP_LIST_ON_TOOLTIP_REQUESTED: u16 = 1109;
pub const OP_LIST_OVERDRAW_PX: u16 = 1110;
pub const OP_LIST_PROJECTION_REVISION: u16 = 1111;
pub const OP_LIST_RENDERER: u16 = 1112;
pub const OP_ROW_TOOLTIP_TARGET: u16 = 1113;
pub const OP_TABLE_CELL_COLUMN: u16 = 1200;
pub const OP_TABLE_COLUMN: u16 = 1201;
pub const OP_TABLE_HEADER_BACKGROUND_RGBA: u16 = 1202;
pub const OP_TABLE_HEADER_BORDER_RGBA: u16 = 1203;
pub const OP_TABLE_HEADER_TEXT_RGBA: u16 = 1204;
pub const OP_TABLE_SHOW_HEADER: u16 = 1205;
pub const OP_INPUT_CARET_RGBA: u16 = 1300;
pub const OP_INPUT_DISABLED: u16 = 1301;
pub const OP_INPUT_ON_CHANGED: u16 = 1302;
pub const OP_INPUT_ON_FOCUS_CHANGED: u16 = 1303;
pub const OP_INPUT_ON_SUBMITTED: u16 = 1304;
pub const OP_INPUT_ON_WRITE_COMPLETED: u16 = 1305;
pub const OP_INPUT_PASSWORD: u16 = 1306;
pub const OP_INPUT_PLACEHOLDER_RGBA: u16 = 1307;
pub const OP_INPUT_READ_ONLY: u16 = 1308;
pub const OP_INPUT_SELECTION_RGBA: u16 = 1309;
pub const OP_SLIDER_AXIS: u16 = 1400;
pub const OP_SLIDER_DISABLED: u16 = 1401;
pub const OP_SLIDER_FILL_RGBA: u16 = 1402;
pub const OP_SLIDER_MAX: u16 = 1403;
pub const OP_SLIDER_MIN: u16 = 1404;
pub const OP_SLIDER_ON_CHANGED: u16 = 1405;
pub const OP_SLIDER_ON_RELEASED: u16 = 1406;
pub const OP_SLIDER_RANGE_END: u16 = 1407;
pub const OP_SLIDER_RANGE_START: u16 = 1408;
pub const OP_SLIDER_SCALE: u16 = 1409;
pub const OP_SLIDER_STEP: u16 = 1410;
pub const OP_SLIDER_THUMB_BORDER_RGBA: u16 = 1411;
pub const OP_SLIDER_THUMB_RGBA: u16 = 1412;
pub const OP_SLIDER_TRACK_RGBA: u16 = 1413;
pub const OP_SLIDER_VALUE: u16 = 1414;
pub const OP_OVERLAY_BACKDROP_RGBA: u16 = 1500;
pub const OP_OVERLAY_DISMISS_ON_BACKDROP: u16 = 1501;
pub const OP_OVERLAY_DISMISS_ON_ESCAPE: u16 = 1502;
pub const OP_OVERLAY_MARGIN_PX: u16 = 1503;
pub const OP_OVERLAY_MODAL: u16 = 1504;
pub const OP_OVERLAY_ON_DISMISS: u16 = 1505;
pub const OP_OVERLAY_PLACEMENT: u16 = 1506;
pub const OP_OVERLAY_PRIORITY: u16 = 1507;
pub const OP_TOOLTIP_ALIGNMENT: u16 = 1600;
pub const OP_TOOLTIP_GAP_PX: u16 = 1601;
pub const OP_TOOLTIP_HIDE_DELAY_MS: u16 = 1602;
pub const OP_TOOLTIP_MARGIN_PX: u16 = 1603;
pub const OP_TOOLTIP_PLACEMENT: u16 = 1604;
pub const OP_TOOLTIP_ROW_ANCHOR: u16 = 1605;
pub const OP_TOOLTIP_SHOW_DELAY_MS: u16 = 1606;
pub const OP_CONTEXT_MENU_MARGIN_PX: u16 = 1700;
pub const OP_CONTEXT_MENU_PRIORITY: u16 = 1701;
pub const OP_CONTEXT_MENU_ROW_ANCHOR: u16 = 1702;
pub const OP_POPOVER_MENU_MARGIN_PX: u16 = 1703;
pub const OP_POPOVER_MENU_PRIORITY: u16 = 1704;
pub const OP_IMAGE_GRAYSCALE: u16 = 1800;
pub const OP_IMAGE_OBJECT_FIT: u16 = 1801;
pub const OP_DRAWING_VIEW_BOX_ORIGIN: u16 = 1900;
pub const OP_DRAWING_VIEW_BOX_SIZE: u16 = 1901;
pub const OP_PATH_ARC_FLAGS: u16 = 1902;
pub const OP_PATH_ARC_RADII: u16 = 1903;
pub const OP_PATH_ARC_ROTATION: u16 = 1904;
pub const OP_PATH_ARC_TO: u16 = 1905;
pub const OP_PATH_CIRCLE_CENTER: u16 = 1906;
pub const OP_PATH_CIRCLE_RADIUS: u16 = 1907;
pub const OP_PATH_CLOSE: u16 = 1908;
pub const OP_PATH_CUBIC_CONTROL_A: u16 = 1909;
pub const OP_PATH_CUBIC_CONTROL_B: u16 = 1910;
pub const OP_PATH_CUBIC_TO: u16 = 1911;
pub const OP_PATH_DASH_PX: u16 = 1912;
pub const OP_PATH_FILL_RGBA: u16 = 1913;
pub const OP_PATH_FILL_RULE: u16 = 1914;
pub const OP_PATH_LINE_TO: u16 = 1915;
pub const OP_PATH_MOVE_TO: u16 = 1916;
pub const OP_PATH_QUADRATIC_CONTROL: u16 = 1917;
pub const OP_PATH_QUADRATIC_TO: u16 = 1918;
pub const OP_PATH_STROKE_RGBA: u16 = 1919;
pub const OP_PATH_STROKE_WIDTH_PX: u16 = 1920;
pub const OP_DOCK_ACTIVE_INDEX: u16 = 2000;
pub const OP_DOCK_AXIS: u16 = 2001;
pub const OP_DOCK_INITIAL_SIZE_PX: u16 = 2002;
pub const OP_DOCK_LOCKED: u16 = 2003;
pub const OP_DOCK_ON_CLOSED: u16 = 2004;
pub const OP_DOCK_ON_LAYOUT: u16 = 2005;
pub const OP_DOCK_PANEL_CLOSABLE: u16 = 2006;
pub const OP_DOCK_PANEL_INNER_PADDING: u16 = 2007;
pub const OP_DOCK_PANEL_ZOOMABLE: u16 = 2008;
pub const OP_DOCK_REGION_COLLAPSIBLE: u16 = 2009;
pub const OP_DOCK_REGION_OPEN: u16 = 2010;
pub const OP_DOCK_REGION_SIDE: u16 = 2011;
pub const OP_DYNAMIC_ACTIVE: u16 = 2100;

pub const RESOURCE_SCROLL: u16 = 1;
pub const COMMAND_SCROLL_TO_OFFSET: u16 = 100;
pub const COMMAND_SCROLL_TO_TOP: u16 = 101;
pub const COMMAND_SCROLL_TO_BOTTOM: u16 = 102;
pub const RESOURCE_LIST: u16 = 2;
pub const COMMAND_LIST_SCROLL_TO_ITEM: u16 = 200;
pub const COMMAND_LIST_SPLICE: u16 = 201;
pub const COMMAND_LIST_RESET: u16 = 202;
pub const COMMAND_LIST_REFRESH: u16 = 203;
pub const RESOURCE_INPUT: u16 = 3;
pub const COMMAND_INPUT_FOCUS: u16 = 300;
pub const COMMAND_INPUT_BLUR: u16 = 301;
pub const COMMAND_INPUT_SET_VALUE: u16 = 302;
pub const COMMAND_INPUT_SELECT_ALL: u16 = 303;
pub const COMMAND_INPUT_SET_VALUE_IF_CURRENT: u16 = 304;
pub const COMMAND_INPUT_SET_VALUE_IF_CURRENT_WITH_RESULT: u16 = 305;
pub const RESOURCE_SLIDER: u16 = 4;
pub const COMMAND_SLIDER_SET_VALUE: u16 = 400;
pub const RESOURCE_DOCK: u16 = 5;
pub const COMMAND_DOCK_CLOSE_PANEL: u16 = 500;
pub const COMMAND_DOCK_SET_REGION_OPEN: u16 = 501;
pub const COMMAND_DOCK_IMPORT_LAYOUT: u16 = 502;
pub const COMMAND_DOCK_EXPORT_LAYOUT: u16 = 503;
pub const RESOURCE_FOCUS: u16 = 6;
pub const COMMAND_FOCUS_FOCUS: u16 = 600;
pub const COMMAND_FOCUS_BLUR: u16 = 601;

pub const EVENT_INPUT_CHANGED: u16 = 100;
pub const EVENT_INPUT_FOCUS_CHANGED: u16 = 101;
pub const EVENT_INPUT_SUBMITTED: u16 = 102;
pub const EVENT_INPUT_WRITE_COMPLETED: u16 = 200;
pub const EVENT_LIST_ACTIVATED: u16 = 300;
pub const EVENT_LIST_CONTEXT_MENU_REQUESTED: u16 = 301;
pub const EVENT_LIST_SELECTION_REQUESTED: u16 = 302;
pub const EVENT_LIST_TOOLTIP_REQUESTED: u16 = 303;
pub const EVENT_SLIDER_CHANGED: u16 = 400;
pub const EVENT_SLIDER_RELEASED: u16 = 401;
pub const EVENT_DOCK_LAYOUT_CHANGED: u16 = 500;
pub const EVENT_DOCK_LAYOUT_EXPORTED: u16 = 501;
pub const EVENT_DOCK_PANEL_CLOSED: u16 = 502;
pub const EVENT_KEY_DOWN: u16 = 600;
pub const EVENT_KEY_UP: u16 = 601;
pub const EVENT_MOUSE_DOWN: u16 = 700;
pub const EVENT_MOUSE_DOWN_OUT: u16 = 701;
pub const EVENT_MOUSE_MOVE: u16 = 702;
pub const EVENT_MOUSE_UP: u16 = 703;
pub const EVENT_MOUSE_UP_OUT: u16 = 704;
pub const EVENT_MODIFIERS_CHANGED: u16 = 800;
pub const EVENT_HOVER: u16 = 900;
pub const EVENT_SCROLL_WHEEL: u16 = 1000;
pub const EVENT_FILE_DROPPED: u16 = 1100;
pub const EVENT_SHORTCUT_INVOKED: u16 = 1200;

#[repr(u16)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ValueKind {
    None = 0,
    F32 = 1,
    U32 = 2,
    Callback = 3,
    U64 = 4,
    F32x2 = 5,
    Data = 6,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DataKind {
    None,
    Utf8,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NativeAdapter {
    Div,
    Text,
    Spacer,
    Divider,
    Badge,
    Button,
    Checkbox,
    Radio,
    Scroll,
    List,
    Table,
    Input,
    Slider,
    Image,
    Drawing,
    Path,
    Dynamic,
    Overlay,
    Tooltip,
    ContextMenu,
    PopoverMenu,
    DockArea,
    DockSplit,
    DockTabs,
    DockPanel,
    DockRegion,
    NativeExtension,
}

#[derive(Clone, Copy, Debug)]
pub struct ComponentMetadata {
    pub id: u16,
    pub name: &'static str,
    pub data_kind: DataKind,
    pub data_required: bool,
    pub allows_children: bool,
    pub capabilities: u64,
    pub adapter: NativeAdapter,
}

#[derive(Clone, Copy, Debug)]
pub struct OperationMetadata {
    pub id: u16,
    pub name: &'static str,
    pub value_kind: ValueKind,
    pub required_capability: u64,
}

impl OperationMetadata {
    pub fn applies_to(self, component: u16) -> bool {
        component_metadata(component).is_some_and(|metadata| {
            metadata.capabilities & self.required_capability == self.required_capability
        })
    }
}

pub const COMPONENTS: &[ComponentMetadata] = &[
    ComponentMetadata {
        id: COMPONENT_DIV,
        name: "div",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x000000010A2E2000,
        adapter: NativeAdapter::Div,
    },
    ComponentMetadata {
        id: COMPONENT_TEXT,
        name: "text",
        data_kind: DataKind::Utf8,
        data_required: false,
        allows_children: false,
        capabilities: 0x0000000008000000,
        adapter: NativeAdapter::Text,
    },
    ComponentMetadata {
        id: COMPONENT_SPACER,
        name: "spacer",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: false,
        capabilities: 0x0000000008000000,
        adapter: NativeAdapter::Spacer,
    },
    ComponentMetadata {
        id: COMPONENT_DIVIDER,
        name: "divider",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: false,
        capabilities: 0x0000000008000000,
        adapter: NativeAdapter::Divider,
    },
    ComponentMetadata {
        id: COMPONENT_BADGE,
        name: "badge",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x0000000008200000,
        adapter: NativeAdapter::Badge,
    },
    ComponentMetadata {
        id: COMPONENT_BUTTON,
        name: "button",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000108230009,
        adapter: NativeAdapter::Button,
    },
    ComponentMetadata {
        id: COMPONENT_CHECKBOX,
        name: "checkbox",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x000000000823000B,
        adapter: NativeAdapter::Checkbox,
    },
    ComponentMetadata {
        id: COMPONENT_RADIO,
        name: "radio",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x000000000823000B,
        adapter: NativeAdapter::Radio,
    },
    ComponentMetadata {
        id: COMPONENT_SCROLL,
        name: "scroll",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x00000000092C0000,
        adapter: NativeAdapter::Scroll,
    },
    ComponentMetadata {
        id: COMPONENT_LIST,
        name: "list",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: false,
        capabilities: 0x00000000C8080000,
        adapter: NativeAdapter::List,
    },
    ComponentMetadata {
        id: COMPONENT_TABLE,
        name: "table",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x00000000D8280000,
        adapter: NativeAdapter::Table,
    },
    ComponentMetadata {
        id: COMPONENT_INPUT,
        name: "input",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: false,
        capabilities: 0x0000000008088001,
        adapter: NativeAdapter::Input,
    },
    ComponentMetadata {
        id: COMPONENT_SLIDER,
        name: "slider",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: false,
        capabilities: 0x000000000C080001,
        adapter: NativeAdapter::Slider,
    },
    ComponentMetadata {
        id: COMPONENT_IMAGE,
        name: "image",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: false,
        capabilities: 0x0000000008004000,
        adapter: NativeAdapter::Image,
    },
    ComponentMetadata {
        id: COMPONENT_DRAWING,
        name: "drawing",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x0000000008200400,
        adapter: NativeAdapter::Drawing,
    },
    ComponentMetadata {
        id: COMPONENT_PATH,
        name: "path",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: false,
        capabilities: 0x0000000000400000,
        adapter: NativeAdapter::Path,
    },
    ComponentMetadata {
        id: COMPONENT_DYNAMIC,
        name: "dynamic",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x0000000000280800,
        adapter: NativeAdapter::Dynamic,
    },
    ComponentMetadata {
        id: COMPONENT_OVERLAY,
        name: "overlay",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000002380000,
        adapter: NativeAdapter::Overlay,
    },
    ComponentMetadata {
        id: COMPONENT_TOOLTIP,
        name: "tooltip",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000060280000,
        adapter: NativeAdapter::Tooltip,
    },
    ComponentMetadata {
        id: COMPONENT_CONTEXT_MENU,
        name: "context_menu",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000008280004,
        adapter: NativeAdapter::ContextMenu,
    },
    ComponentMetadata {
        id: COMPONENT_POPOVER_MENU,
        name: "popover_menu",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000008A80000,
        adapter: NativeAdapter::PopoverMenu,
    },
    ComponentMetadata {
        id: COMPONENT_DOCK_AREA,
        name: "dock_area",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x00000000082C0010,
        adapter: NativeAdapter::DockArea,
    },
    ComponentMetadata {
        id: COMPONENT_DOCK_SPLIT,
        name: "dock_split",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x0000000000200120,
        adapter: NativeAdapter::DockSplit,
    },
    ComponentMetadata {
        id: COMPONENT_DOCK_TABS,
        name: "dock_tabs",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x0000000000200220,
        adapter: NativeAdapter::DockTabs,
    },
    ComponentMetadata {
        id: COMPONENT_DOCK_PANEL,
        name: "dock_panel",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x0000000000200040,
        adapter: NativeAdapter::DockPanel,
    },
    ComponentMetadata {
        id: COMPONENT_DOCK_REGION,
        name: "dock_region",
        data_kind: DataKind::None,
        data_required: false,
        allows_children: true,
        capabilities: 0x00000000002000A0,
        adapter: NativeAdapter::DockRegion,
    },
    ComponentMetadata {
        id: COMPONENT_NATIVE_EXTENSION,
        name: "native_extension",
        data_kind: DataKind::Utf8,
        data_required: true,
        allows_children: true,
        capabilities: 0x00000000082C1000,
        adapter: NativeAdapter::NativeExtension,
    },
];

pub const OPERATIONS: &[OperationMetadata] = &[
    OperationMetadata {
        id: OP_ELEMENT_OWNER,
        name: "element_owner",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_RESOURCE_OWNER,
        name: "resource_owner",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000080000,
    },
    OperationMetadata {
        id: OP_ALIGN_CONTENT,
        name: "align_content",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_DISPLAY_NONE,
        name: "display_none",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FLEX,
        name: "flex",
        value_kind: ValueKind::None,
        required_capability: 0x0000000000040000,
    },
    OperationMetadata {
        id: OP_FLEX_BASIS_PERCENT,
        name: "flex_basis_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FLEX_BASIS_PX,
        name: "flex_basis_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FLEX_GROW,
        name: "flex_grow",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FLEX_SHRINK,
        name: "flex_shrink",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FLEX_WRAP,
        name: "flex_wrap",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ITEMS_BASELINE,
        name: "items_baseline",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ITEMS_CENTER,
        name: "items_center",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ITEMS_END,
        name: "items_end",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ITEMS_START,
        name: "items_start",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ITEMS_STRETCH,
        name: "items_stretch",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_JUSTIFY_BETWEEN,
        name: "justify_between",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_JUSTIFY_CENTER,
        name: "justify_center",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_JUSTIFY_END,
        name: "justify_end",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_JUSTIFY_START,
        name: "justify_start",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_BASELINE,
        name: "self_baseline",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_CENTER,
        name: "self_center",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_END,
        name: "self_end",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_FLEX_END,
        name: "self_flex_end",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_FLEX_START,
        name: "self_flex_start",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_START,
        name: "self_start",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SELF_STRETCH,
        name: "self_stretch",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_V_STACK,
        name: "v_stack",
        value_kind: ValueKind::None,
        required_capability: 0x0000000000040000,
    },
    OperationMetadata {
        id: OP_ABSOLUTE,
        name: "absolute",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ASPECT_RATIO,
        name: "aspect_ratio",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BOTTOM_PERCENT,
        name: "bottom_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BOTTOM_PX,
        name: "bottom_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_HEIGHT_PERCENT,
        name: "height_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_HEIGHT_PX,
        name: "height_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_INSET_PERCENT,
        name: "inset_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_INSET_PX,
        name: "inset_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LEFT_PERCENT,
        name: "left_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LEFT_PX,
        name: "left_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MAX_HEIGHT_PERCENT,
        name: "max_height_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MAX_HEIGHT_PX,
        name: "max_height_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MAX_WIDTH_PERCENT,
        name: "max_width_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MAX_WIDTH_PX,
        name: "max_width_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MIN_HEIGHT_PERCENT,
        name: "min_height_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MIN_HEIGHT_PX,
        name: "min_height_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MIN_WIDTH_PERCENT,
        name: "min_width_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MIN_WIDTH_PX,
        name: "min_width_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RELATIVE,
        name: "relative",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RIGHT_PERCENT,
        name: "right_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RIGHT_PX,
        name: "right_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TOP_PERCENT,
        name: "top_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TOP_PX,
        name: "top_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_WIDTH_PERCENT,
        name: "width_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_WIDTH_PX,
        name: "width_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_PERCENT,
        name: "gap_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_PX,
        name: "gap_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_X_PERCENT,
        name: "gap_x_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_X_PX,
        name: "gap_x_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_Y_PERCENT,
        name: "gap_y_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GAP_Y_PX,
        name: "gap_y_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_BOTTOM_PERCENT,
        name: "margin_bottom_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_BOTTOM_PX,
        name: "margin_bottom_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_LEFT_PERCENT,
        name: "margin_left_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_LEFT_PX,
        name: "margin_left_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_PERCENT,
        name: "margin_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_PX,
        name: "margin_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_RIGHT_PERCENT,
        name: "margin_right_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_RIGHT_PX,
        name: "margin_right_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_TOP_PERCENT,
        name: "margin_top_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_TOP_PX,
        name: "margin_top_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_X_PERCENT,
        name: "margin_x_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_X_PX,
        name: "margin_x_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_Y_PERCENT,
        name: "margin_y_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_MARGIN_Y_PX,
        name: "margin_y_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_BOTTOM_PERCENT,
        name: "padding_bottom_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_BOTTOM_PX,
        name: "padding_bottom_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_LEFT_PERCENT,
        name: "padding_left_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_LEFT_PX,
        name: "padding_left_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_PERCENT,
        name: "padding_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_PX,
        name: "padding_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_RIGHT_PERCENT,
        name: "padding_right_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_RIGHT_PX,
        name: "padding_right_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_TOP_PERCENT,
        name: "padding_top_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_TOP_PX,
        name: "padding_top_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_X_PERCENT,
        name: "padding_x_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_X_PX,
        name: "padding_x_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_Y_PERCENT,
        name: "padding_y_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_PADDING_Y_PX,
        name: "padding_y_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_END,
        name: "col_end",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_END_AUTO,
        name: "col_end_auto",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_SPAN,
        name: "col_span",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_SPAN_FULL,
        name: "col_span_full",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_START,
        name: "col_start",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_COL_START_AUTO,
        name: "col_start_auto",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_DISPLAY_GRID,
        name: "display_grid",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_COLS,
        name: "grid_cols",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_COLS_MAX_CONTENT,
        name: "grid_cols_max_content",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_COLS_MIN_CONTENT,
        name: "grid_cols_min_content",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_ROWS,
        name: "grid_rows",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_ROWS_MAX_CONTENT,
        name: "grid_rows_max_content",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_GRID_ROWS_MIN_CONTENT,
        name: "grid_rows_min_content",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_END,
        name: "row_end",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_END_AUTO,
        name: "row_end_auto",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_SPAN,
        name: "row_span",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_SPAN_FULL,
        name: "row_span_full",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_START,
        name: "row_start",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ROW_START_AUTO,
        name: "row_start_auto",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BACKGROUND_RGBA,
        name: "background_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BORDER_RGBA,
        name: "border_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BORDER_STYLE,
        name: "border_style",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_BORDER_WIDTH_PX,
        name: "border_width_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_OPACITY,
        name: "opacity",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_OVERFLOW_HIDDEN,
        name: "overflow_hidden",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_OVERFLOW_X_HIDDEN,
        name: "overflow_x_hidden",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_OVERFLOW_Y_HIDDEN,
        name: "overflow_y_hidden",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RADIUS_BOTTOM_LEFT_PX,
        name: "radius_bottom_left_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RADIUS_BOTTOM_RIGHT_PX,
        name: "radius_bottom_right_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RADIUS_PX,
        name: "radius_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RADIUS_TOP_LEFT_PX,
        name: "radius_top_left_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_RADIUS_TOP_RIGHT_PX,
        name: "radius_top_right_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SHADOW_BLUR,
        name: "shadow_blur",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SHADOW_COLOR,
        name: "shadow_color",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SHADOW_OFFSET,
        name: "shadow_offset",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_SHADOW_SPREAD,
        name: "shadow_spread",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_VISIBILITY,
        name: "visibility",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_FALLBACKS,
        name: "font_fallbacks",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_FAMILY,
        name: "font_family",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_FEATURES,
        name: "font_features",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_SIZE_PX,
        name: "font_size_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_STYLE,
        name: "font_style",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_FONT_WEIGHT,
        name: "font_weight",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LINE_CLAMP,
        name: "line_clamp",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LINE_HEIGHT_PERCENT,
        name: "line_height_percent",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LINE_HEIGHT_PX,
        name: "line_height_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LINE_THROUGH,
        name: "line_through",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_ALIGN,
        name: "text_align",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_BACKGROUND,
        name: "text_background",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_DECORATION_COLOR,
        name: "text_decoration_color",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_DECORATION_NONE,
        name: "text_decoration_none",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_DECORATION_SOLID,
        name: "text_decoration_solid",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_DECORATION_WAVY,
        name: "text_decoration_wavy",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_ELLIPSIS,
        name: "text_ellipsis",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_RGBA,
        name: "text_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TEXT_TRUNCATE,
        name: "text_truncate",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_UNDERLINE,
        name: "underline",
        value_kind: ValueKind::None,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_WHITE_SPACE,
        name: "white_space",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_ACTIVE_BACKGROUND_RGBA,
        name: "active_background_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_ACTIVE_BORDER_RGBA,
        name: "active_border_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_ACTIVE_TEXT_RGBA,
        name: "active_text_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_CHECKED,
        name: "checked",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000002,
    },
    OperationMetadata {
        id: OP_CURSOR,
        name: "cursor",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_DISABLED,
        name: "disabled",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000008,
    },
    OperationMetadata {
        id: OP_HOVER_BACKGROUND_RGBA,
        name: "hover_background_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_HOVER_BORDER_RGBA,
        name: "hover_border_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_HOVER_TEXT_RGBA,
        name: "hover_text_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_ISOLATE_SHORTCUTS,
        name: "isolate_shortcuts",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000002000000,
    },
    OperationMetadata {
        id: OP_ON_CLICK,
        name: "on_click",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000010000,
    },
    OperationMetadata {
        id: OP_ON_FILE_DROP,
        name: "on_file_drop",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_HOVER,
        name: "on_hover",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_KEY_DOWN,
        name: "on_key_down",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_KEY_UP,
        name: "on_key_up",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MODIFIERS_CHANGED,
        name: "on_modifiers_changed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MOUSE_DOWN,
        name: "on_mouse_down",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MOUSE_DOWN_OUT,
        name: "on_mouse_down_out",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MOUSE_MOVE,
        name: "on_mouse_move",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MOUSE_UP,
        name: "on_mouse_up",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_MOUSE_UP_OUT,
        name: "on_mouse_up_out",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_SCROLL_WHEEL,
        name: "on_scroll_wheel",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000020000,
    },
    OperationMetadata {
        id: OP_ON_SHORTCUT,
        name: "on_shortcut",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000002000000,
    },
    OperationMetadata {
        id: OP_WINDOW_CONTROL_AREA,
        name: "window_control_area",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000100000000,
    },
    OperationMetadata {
        id: OP_ACCESSIBLE_DESCRIPTION,
        name: "accessible_description",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000000000001,
    },
    OperationMetadata {
        id: OP_ACCESSIBLE_NAME,
        name: "accessible_name",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000000000001,
    },
    OperationMetadata {
        id: OP_FOCUS_TAB_STOP,
        name: "focus_tab_stop",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000002000,
    },
    OperationMetadata {
        id: OP_FOCUS_TARGET,
        name: "focus_target",
        value_kind: ValueKind::Data,
        required_capability: 0x0000000000002000,
    },
    OperationMetadata {
        id: OP_SCROLL_AXIS,
        name: "scroll_axis",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000001000000,
    },
    OperationMetadata {
        id: OP_SCROLLBAR_GUTTER,
        name: "scrollbar_gutter",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000080000,
    },
    OperationMetadata {
        id: OP_SCROLLBAR_WIDTH,
        name: "scrollbar_width",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000080000,
    },
    OperationMetadata {
        id: OP_SHOW_SCROLLBAR,
        name: "show_scrollbar",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000080000,
    },
    OperationMetadata {
        id: OP_SMOOTH_SCROLL,
        name: "smooth_scroll",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000080000,
    },
    OperationMetadata {
        id: OP_LIST_ALIGNMENT,
        name: "list_alignment",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_BATCH_SIZE,
        name: "list_batch_size",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_CONTENT_REVISION,
        name: "list_content_revision",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ESTIMATED_ITEM_HEIGHT_PX,
        name: "list_estimated_item_height_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ITEM_COUNT,
        name: "list_item_count",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ITEM_ID,
        name: "list_item_id",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_LIST_ON_ACTIVATED,
        name: "list_on_activated",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ON_CONTEXT_MENU_REQUESTED,
        name: "list_on_context_menu_requested",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ON_SELECTION_REQUESTED,
        name: "list_on_selection_requested",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_ON_TOOLTIP_REQUESTED,
        name: "list_on_tooltip_requested",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_OVERDRAW_PX,
        name: "list_overdraw_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_PROJECTION_REVISION,
        name: "list_projection_revision",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_LIST_RENDERER,
        name: "list_renderer",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000080000000,
    },
    OperationMetadata {
        id: OP_ROW_TOOLTIP_TARGET,
        name: "row_tooltip_target",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TABLE_CELL_COLUMN,
        name: "table_cell_column",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000008000000,
    },
    OperationMetadata {
        id: OP_TABLE_COLUMN,
        name: "table_column",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000010000000,
    },
    OperationMetadata {
        id: OP_TABLE_HEADER_BACKGROUND_RGBA,
        name: "table_header_background_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000010000000,
    },
    OperationMetadata {
        id: OP_TABLE_HEADER_BORDER_RGBA,
        name: "table_header_border_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000010000000,
    },
    OperationMetadata {
        id: OP_TABLE_HEADER_TEXT_RGBA,
        name: "table_header_text_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000010000000,
    },
    OperationMetadata {
        id: OP_TABLE_SHOW_HEADER,
        name: "table_show_header",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000010000000,
    },
    OperationMetadata {
        id: OP_INPUT_CARET_RGBA,
        name: "input_caret_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_DISABLED,
        name: "input_disabled",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_ON_CHANGED,
        name: "input_on_changed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_ON_FOCUS_CHANGED,
        name: "input_on_focus_changed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_ON_SUBMITTED,
        name: "input_on_submitted",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_ON_WRITE_COMPLETED,
        name: "input_on_write_completed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_PASSWORD,
        name: "input_password",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_PLACEHOLDER_RGBA,
        name: "input_placeholder_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_READ_ONLY,
        name: "input_read_only",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_INPUT_SELECTION_RGBA,
        name: "input_selection_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000008000,
    },
    OperationMetadata {
        id: OP_SLIDER_AXIS,
        name: "slider_axis",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_DISABLED,
        name: "slider_disabled",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_FILL_RGBA,
        name: "slider_fill_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_MAX,
        name: "slider_max",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_MIN,
        name: "slider_min",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_ON_CHANGED,
        name: "slider_on_changed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_ON_RELEASED,
        name: "slider_on_released",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_RANGE_END,
        name: "slider_range_end",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_RANGE_START,
        name: "slider_range_start",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_SCALE,
        name: "slider_scale",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_STEP,
        name: "slider_step",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_THUMB_BORDER_RGBA,
        name: "slider_thumb_border_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_THUMB_RGBA,
        name: "slider_thumb_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_TRACK_RGBA,
        name: "slider_track_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_SLIDER_VALUE,
        name: "slider_value",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000004000000,
    },
    OperationMetadata {
        id: OP_OVERLAY_BACKDROP_RGBA,
        name: "overlay_backdrop_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_DISMISS_ON_BACKDROP,
        name: "overlay_dismiss_on_backdrop",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_DISMISS_ON_ESCAPE,
        name: "overlay_dismiss_on_escape",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_MARGIN_PX,
        name: "overlay_margin_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_MODAL,
        name: "overlay_modal",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_ON_DISMISS,
        name: "overlay_on_dismiss",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_PLACEMENT,
        name: "overlay_placement",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_OVERLAY_PRIORITY,
        name: "overlay_priority",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000100000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_ALIGNMENT,
        name: "tooltip_alignment",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_GAP_PX,
        name: "tooltip_gap_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_HIDE_DELAY_MS,
        name: "tooltip_hide_delay_ms",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_MARGIN_PX,
        name: "tooltip_margin_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_PLACEMENT,
        name: "tooltip_placement",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_ROW_ANCHOR,
        name: "tooltip_row_anchor",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000020000000,
    },
    OperationMetadata {
        id: OP_TOOLTIP_SHOW_DELAY_MS,
        name: "tooltip_show_delay_ms",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000040000000,
    },
    OperationMetadata {
        id: OP_CONTEXT_MENU_MARGIN_PX,
        name: "context_menu_margin_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000000004,
    },
    OperationMetadata {
        id: OP_CONTEXT_MENU_PRIORITY,
        name: "context_menu_priority",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000004,
    },
    OperationMetadata {
        id: OP_CONTEXT_MENU_ROW_ANCHOR,
        name: "context_menu_row_anchor",
        value_kind: ValueKind::U64,
        required_capability: 0x0000000000000004,
    },
    OperationMetadata {
        id: OP_POPOVER_MENU_MARGIN_PX,
        name: "popover_menu_margin_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000800000,
    },
    OperationMetadata {
        id: OP_POPOVER_MENU_PRIORITY,
        name: "popover_menu_priority",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000800000,
    },
    OperationMetadata {
        id: OP_IMAGE_GRAYSCALE,
        name: "image_grayscale",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000004000,
    },
    OperationMetadata {
        id: OP_IMAGE_OBJECT_FIT,
        name: "image_object_fit",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000004000,
    },
    OperationMetadata {
        id: OP_DRAWING_VIEW_BOX_ORIGIN,
        name: "drawing_view_box_origin",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000000400,
    },
    OperationMetadata {
        id: OP_DRAWING_VIEW_BOX_SIZE,
        name: "drawing_view_box_size",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000000400,
    },
    OperationMetadata {
        id: OP_PATH_ARC_FLAGS,
        name: "path_arc_flags",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_ARC_RADII,
        name: "path_arc_radii",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_ARC_ROTATION,
        name: "path_arc_rotation",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_ARC_TO,
        name: "path_arc_to",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CIRCLE_CENTER,
        name: "path_circle_center",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CIRCLE_RADIUS,
        name: "path_circle_radius",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CLOSE,
        name: "path_close",
        value_kind: ValueKind::None,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CUBIC_CONTROL_A,
        name: "path_cubic_control_a",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CUBIC_CONTROL_B,
        name: "path_cubic_control_b",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_CUBIC_TO,
        name: "path_cubic_to",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_DASH_PX,
        name: "path_dash_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_FILL_RGBA,
        name: "path_fill_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_FILL_RULE,
        name: "path_fill_rule",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_LINE_TO,
        name: "path_line_to",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_MOVE_TO,
        name: "path_move_to",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_QUADRATIC_CONTROL,
        name: "path_quadratic_control",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_QUADRATIC_TO,
        name: "path_quadratic_to",
        value_kind: ValueKind::F32x2,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_STROKE_RGBA,
        name: "path_stroke_rgba",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_PATH_STROKE_WIDTH_PX,
        name: "path_stroke_width_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000400000,
    },
    OperationMetadata {
        id: OP_DOCK_ACTIVE_INDEX,
        name: "dock_active_index",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000200,
    },
    OperationMetadata {
        id: OP_DOCK_AXIS,
        name: "dock_axis",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000100,
    },
    OperationMetadata {
        id: OP_DOCK_INITIAL_SIZE_PX,
        name: "dock_initial_size_px",
        value_kind: ValueKind::F32,
        required_capability: 0x0000000000000020,
    },
    OperationMetadata {
        id: OP_DOCK_LOCKED,
        name: "dock_locked",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000010,
    },
    OperationMetadata {
        id: OP_DOCK_ON_CLOSED,
        name: "dock_on_closed",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000000010,
    },
    OperationMetadata {
        id: OP_DOCK_ON_LAYOUT,
        name: "dock_on_layout",
        value_kind: ValueKind::Callback,
        required_capability: 0x0000000000000010,
    },
    OperationMetadata {
        id: OP_DOCK_PANEL_CLOSABLE,
        name: "dock_panel_closable",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000040,
    },
    OperationMetadata {
        id: OP_DOCK_PANEL_INNER_PADDING,
        name: "dock_panel_inner_padding",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000040,
    },
    OperationMetadata {
        id: OP_DOCK_PANEL_ZOOMABLE,
        name: "dock_panel_zoomable",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000040,
    },
    OperationMetadata {
        id: OP_DOCK_REGION_COLLAPSIBLE,
        name: "dock_region_collapsible",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000080,
    },
    OperationMetadata {
        id: OP_DOCK_REGION_OPEN,
        name: "dock_region_open",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000080,
    },
    OperationMetadata {
        id: OP_DOCK_REGION_SIDE,
        name: "dock_region_side",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000080,
    },
    OperationMetadata {
        id: OP_DYNAMIC_ACTIVE,
        name: "dynamic_active",
        value_kind: ValueKind::U32,
        required_capability: 0x0000000000000800,
    },
];

pub fn component_metadata(id: u16) -> Option<&'static ComponentMetadata> {
    COMPONENTS.iter().find(|metadata| metadata.id == id)
}

pub fn operation_metadata(id: u16) -> Option<&'static OperationMetadata> {
    OPERATIONS.iter().find(|metadata| metadata.id == id)
}

pub fn allows_payload(operation: u16) -> bool {
    match operation {
        OP_ON_CLICK => true,
        OP_ON_SHORTCUT => true,
        OP_OVERLAY_ON_DISMISS => true,
        _ => false,
    }
}

fn f32_payload_in_range(a: u64, min: f32, max: f32) -> bool {
    let value = f32::from_bits(a as u32);
    value >= min && value <= max
}

fn valid_packed_table_column(a: u64) -> bool {
    a >> 36 == 0
        && (a >> 32) & 0b11 <= 1
        && (a >> 34) & 0b11 <= 2
        && f32::from_bits(a as u32).is_finite()
        && f32::from_bits(a as u32) > 0.0
        && ((a >> 32) & 0b11 != 1 || f32::from_bits(a as u32) <= 1.0)
}

fn valid_packed_shortcut(b: u64) -> bool {
    (b >> 27) == 0
        && (b & 0xffff) >= 1
        && (b & 0xffff) <= 86
        && ((b >> 16) & 0xff) <= 63
        && (((b & 0xffff) > 36 && (b & 0xffff) < 76 && (b & 0xffff) != 42)
            || (b & (41u64 << 16)) != 0)
        && ((b & (32u64 << 16)) == 0 || (b & (9u64 << 16)) == 0)
}

pub fn payload_error(operation: u16, a: u64, b: u64) -> i32 {
    match operation {
        OP_ELEMENT_OWNER if !(a >= 1u64) => -25,
        OP_RESOURCE_OWNER if !(a >= 1u64) => -25,
        OP_ALIGN_CONTENT if !(a <= 7u64) => -54,
        OP_FLEX_GROW if !(f32::from_bits(a as u32) >= 0f32) => -46,
        OP_FLEX_SHRINK if !(f32::from_bits(a as u32) >= 0f32) => -44,
        OP_FLEX_WRAP if !(a <= 2u64) => -45,
        OP_ASPECT_RATIO if !(f32::from_bits(a as u32) > 0f32) => -51,
        OP_BORDER_STYLE if !(a <= 1u64) => -56,
        OP_OPACITY if !(f32_payload_in_range(a, 0f32, 1f32)) => -47,
        OP_VISIBILITY if !(a <= 1u64) => -53,
        OP_FONT_STYLE if !(a <= 1u64) => -22,
        OP_FONT_WEIGHT if !(f32_payload_in_range(a, 100f32, 900f32)) => -55,
        OP_LINE_CLAMP if !(a >= 1u64) => -49,
        OP_TEXT_ALIGN if !(a <= 2u64) => -48,
        OP_WHITE_SPACE if !(a <= 1u64) => -52,
        OP_CHECKED if !(a <= 1) => -21,
        OP_CURSOR if !(a <= 20u64) => -50,
        OP_DISABLED if !(a <= 1) => -21,
        OP_ISOLATE_SHORTCUTS if !(a <= 1) => -21,
        OP_ON_SHORTCUT if !(valid_packed_shortcut(b)) => -66,
        OP_WINDOW_CONTROL_AREA if !(a <= 3u64) => -39,
        OP_FOCUS_TAB_STOP if !(a <= 1) => -21,
        OP_SCROLL_AXIS if !(a <= 2u64) => -26,
        OP_SCROLLBAR_GUTTER if !(a <= 1) => -21,
        OP_SCROLLBAR_WIDTH if !(f32_payload_in_range(a, 3f32, 32f32)) => -29,
        OP_SHOW_SCROLLBAR if !(a <= 1) => -21,
        OP_SMOOTH_SCROLL if !(a <= 1) => -21,
        OP_LIST_ALIGNMENT if !(a <= 1u64) => -28,
        OP_LIST_BATCH_SIZE if !(a >= 1u64 && a <= 512u64) => -27,
        OP_LIST_ESTIMATED_ITEM_HEIGHT_PX if !(f32::from_bits(a as u32) > 0f32) => -29,
        OP_LIST_OVERDRAW_PX if !(f32::from_bits(a as u32) >= 0f32) => -29,
        OP_ROW_TOOLTIP_TARGET if !(a <= 1) => -21,
        OP_TABLE_COLUMN if !(valid_packed_table_column(a)) => -57,
        OP_INPUT_DISABLED if !(a <= 1) => -21,
        OP_INPUT_PASSWORD if !(a <= 1) => -21,
        OP_INPUT_READ_ONLY if !(a <= 1) => -21,
        OP_SLIDER_AXIS if !(a <= 1u64) => -43,
        OP_SLIDER_DISABLED if !(a <= 1) => -21,
        OP_SLIDER_SCALE if !(a <= 1u64) => -43,
        OP_OVERLAY_DISMISS_ON_BACKDROP if !(a <= 1) => -21,
        OP_OVERLAY_DISMISS_ON_ESCAPE if !(a <= 1) => -21,
        OP_OVERLAY_MARGIN_PX if !(f32::from_bits(a as u32) >= 0f32) => -34,
        OP_OVERLAY_MODAL if !(a <= 1) => -21,
        OP_OVERLAY_PLACEMENT if !(a <= 8u64) => -33,
        OP_TOOLTIP_ALIGNMENT if !(a <= 2u64) => -36,
        OP_TOOLTIP_GAP_PX if !(f32::from_bits(a as u32) >= 0f32) => -37,
        OP_TOOLTIP_MARGIN_PX if !(f32::from_bits(a as u32) >= 0f32) => -37,
        OP_TOOLTIP_PLACEMENT if !(a <= 4u64) => -35,
        OP_CONTEXT_MENU_MARGIN_PX if !(f32::from_bits(a as u32) >= 0f32) => -40,
        OP_POPOVER_MENU_MARGIN_PX if !(f32::from_bits(a as u32) >= 0f32) => -40,
        OP_IMAGE_GRAYSCALE if !(a <= 1) => -21,
        OP_IMAGE_OBJECT_FIT if !(a <= 4u64) => -30,
        OP_PATH_ARC_FLAGS if !(a <= 3u64) => -59,
        OP_PATH_CIRCLE_RADIUS if !(f32::from_bits(a as u32) > 0f32) => -59,
        OP_PATH_DASH_PX if !(f32::from_bits(a as u32) > 0f32) => -59,
        OP_PATH_FILL_RULE if !(a <= 1u64) => -59,
        OP_PATH_STROKE_WIDTH_PX if !(f32::from_bits(a as u32) > 0f32) => -59,
        OP_DOCK_AXIS if !(a <= 1u64) => -60,
        OP_DOCK_INITIAL_SIZE_PX if !(f32::from_bits(a as u32) > 0f32) => -60,
        OP_DOCK_LOCKED if !(a <= 1) => -21,
        OP_DOCK_PANEL_CLOSABLE if !(a <= 1) => -21,
        OP_DOCK_PANEL_INNER_PADDING if !(a <= 1) => -21,
        OP_DOCK_PANEL_ZOOMABLE if !(a <= 1) => -21,
        OP_DOCK_REGION_COLLAPSIBLE if !(a <= 1) => -21,
        OP_DOCK_REGION_OPEN if !(a <= 1) => -21,
        OP_DOCK_REGION_SIDE if !(a <= 2u64) => -61,
        OP_DYNAMIC_ACTIVE if !(a <= 1) => -21,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn generated_registry_has_unique_ids_and_resolvable_capabilities() {
        let component_ids: HashSet<_> = COMPONENTS.iter().map(|item| item.id).collect();
        let operation_ids: HashSet<_> = OPERATIONS.iter().map(|item| item.id).collect();
        assert_eq!(component_ids.len(), COMPONENTS.len());
        assert_eq!(operation_ids.len(), OPERATIONS.len());
        assert!(OPERATIONS.iter().all(|operation| {
            COMPONENTS
                .iter()
                .any(|component| operation.applies_to(component.id))
        }));
    }

    #[test]
    fn value_kind_layout_matches_the_wire_contract() {
        assert_eq!(ValueKind::None as u16, 0);
        assert_eq!(ValueKind::F32 as u16, 1);
        assert_eq!(ValueKind::U32 as u16, 2);
        assert_eq!(ValueKind::Callback as u16, 3);
        assert_eq!(ValueKind::U64 as u16, 4);
        assert_eq!(ValueKind::F32x2 as u16, 5);
        assert_eq!(ValueKind::Data as u16, 6);
    }
}
