using System.Globalization;
using System.Text;

internal static partial class BindingGenerator
{
    private static string GenerateRust(BindingSchema schema, ulong hash)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// @generated by Gpui.Bindings.Generator. Do not edit.");
        builder.AppendLine("#![allow(dead_code)]");
        builder.AppendLine($"pub const SCHEMA_VERSION: u32 = {schema.SchemaVersion};");
        builder.AppendLine($"pub const SCHEMA_HASH: u64 = 0x{hash:X16};");
        builder.AppendLine();
        foreach (var capability in schema.Capabilities)
        {
            builder.AppendLine(
                $"pub const CAPABILITY_{UpperSnake(capability)}: u64 = 0x{CapabilityBit(schema, capability):X16};"
            );
        }
        builder.AppendLine();
        foreach (var component in schema.Components)
        {
            builder.AppendLine(
                $"pub const COMPONENT_{UpperSnake(component.Name)}: u16 = {component.Id};"
            );
        }
        builder.AppendLine();
        foreach (var operation in schema.Operations)
        {
            builder.AppendLine($"pub const OP_{UpperSnake(operation.Name)}: u16 = {operation.Id};");
        }
        builder.AppendLine();
        foreach (var resource in schema.Resources)
        {
            builder.AppendLine(
                $"pub const RESOURCE_{UpperSnake(resource.Name)}: u16 = {resource.Id};"
            );
            foreach (var command in resource.Commands)
            {
                builder.AppendLine(
                    $"pub const COMMAND_{UpperSnake(resource.Name)}_{UpperSnake(command.Name)}: u16 = {command.Id};"
                );
            }
        }
        builder.AppendLine();
        foreach (var controlEvent in schema.ControlEvents)
        {
            builder.AppendLine(
                $"pub const EVENT_{UpperSnake(controlEvent.Name)}: u16 = {controlEvent.Id};"
            );
        }
        builder.AppendLine();
        builder.AppendLine("#[repr(u16)]");
        builder.AppendLine("#[derive(Clone, Copy, Debug, Eq, PartialEq)]");
        builder.AppendLine("pub enum ValueKind {");
        builder.AppendLine("    None = 0,");
        builder.AppendLine("    F32 = 1,");
        builder.AppendLine("    U32 = 2,");
        builder.AppendLine("    Callback = 3,");
        builder.AppendLine("    U64 = 4,");
        builder.AppendLine("    F32x2 = 5,");
        builder.AppendLine("    Data = 6,");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#[derive(Clone, Copy, Debug, Eq, PartialEq)]");
        builder.AppendLine("pub enum DataKind {");
        builder.AppendLine("    None,");
        builder.AppendLine("    Utf8,");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#[derive(Clone, Copy, Debug, Eq, PartialEq)]");
        builder.AppendLine("pub enum NativeAdapter {");
        foreach (
            var adapter in schema
                .Components.Select(component => component.NativeAdapter)
                .Distinct(StringComparer.Ordinal)
        )
        {
            builder.AppendLine($"    {Pascal(adapter)},");
        }
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#[derive(Clone, Copy, Debug)]");
        builder.AppendLine("pub struct ComponentMetadata {");
        builder.AppendLine("    pub id: u16,");
        builder.AppendLine("    pub name: &'static str,");
        builder.AppendLine("    pub data_kind: DataKind,");
        builder.AppendLine("    pub data_required: bool,");
        builder.AppendLine("    pub allows_children: bool,");
        builder.AppendLine("    pub capabilities: u64,");
        builder.AppendLine("    pub adapter: NativeAdapter,");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#[derive(Clone, Copy, Debug)]");
        builder.AppendLine("pub struct OperationMetadata {");
        builder.AppendLine("    pub id: u16,");
        builder.AppendLine("    pub name: &'static str,");
        builder.AppendLine("    pub value_kind: ValueKind,");
        builder.AppendLine("    pub required_capability: u64,");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("impl OperationMetadata {");
        builder.AppendLine("    pub fn applies_to(self, component: u16) -> bool {");
        builder.AppendLine("        component_metadata(component).is_some_and(|metadata| {");
        builder.AppendLine(
            "            metadata.capabilities & self.required_capability == self.required_capability"
        );
        builder.AppendLine("        })");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("pub const COMPONENTS: &[ComponentMetadata] = &[");
        foreach (var component in schema.Components)
        {
            builder.AppendLine("    ComponentMetadata {");
            builder.AppendLine($"        id: COMPONENT_{UpperSnake(component.Name)},");
            builder.AppendLine($"        name: \"{component.Name}\",");
            builder.AppendLine($"        data_kind: DataKind::{Pascal(component.Data)},");
            builder.AppendLine(
                $"        data_required: {component.DataRequired.ToString().ToLowerInvariant()},"
            );
            builder.AppendLine(
                $"        allows_children: {component.Children.ToString().ToLowerInvariant()},"
            );
            builder.AppendLine(
                $"        capabilities: 0x{CapabilityMask(schema, component.Capabilities):X16},"
            );
            builder.AppendLine(
                $"        adapter: NativeAdapter::{Pascal(component.NativeAdapter)},"
            );
            builder.AppendLine("    },");
        }
        builder.AppendLine("];");
        builder.AppendLine();
        builder.AppendLine("pub const OPERATIONS: &[OperationMetadata] = &[");
        foreach (var operation in schema.Operations)
        {
            builder.AppendLine("    OperationMetadata {");
            builder.AppendLine($"        id: OP_{UpperSnake(operation.Name)},");
            builder.AppendLine($"        name: \"{operation.Name}\",");
            builder.AppendLine($"        value_kind: ValueKind::{Pascal(operation.Value)},");
            builder.AppendLine(
                $"        required_capability: 0x{CapabilityBit(schema, operation.Requires):X16},"
            );
            builder.AppendLine("    },");
        }
        builder.AppendLine("];");
        builder.AppendLine();
        builder.AppendLine(
            "pub fn component_metadata(id: u16) -> Option<&'static ComponentMetadata> {"
        );
        builder.AppendLine("    COMPONENTS.iter().find(|metadata| metadata.id == id)");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine(
            "pub fn operation_metadata(id: u16) -> Option<&'static OperationMetadata> {"
        );
        builder.AppendLine("    OPERATIONS.iter().find(|metadata| metadata.id == id)");
        builder.AppendLine("}");
        builder.AppendLine();
        var payloadOperations = schema
            .Operations.Where(operation => operation.Payload == "event")
            .Select(operation => $"OP_{UpperSnake(operation.Name)}")
            .ToArray();
        builder.AppendLine("pub fn allows_payload(operation: u16) -> bool {");
        builder.AppendLine("    match operation {");
        foreach (var operation in payloadOperations)
            builder.AppendLine($"        {operation} => true,");
        builder.AppendLine("        _ => false,");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("fn f32_payload_in_range(a: u64, min: f32, max: f32) -> bool {");
        builder.AppendLine("    let value = f32::from_bits(a as u32);");
        builder.AppendLine("    value >= min && value <= max");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("fn valid_packed_table_column(a: u64) -> bool {");
        builder.AppendLine("    a >> 36 == 0");
        builder.AppendLine("        && (a >> 32) & 0b11 <= 1");
        builder.AppendLine("        && (a >> 34) & 0b11 <= 2");
        builder.AppendLine("        && f32::from_bits(a as u32).is_finite()");
        builder.AppendLine("        && f32::from_bits(a as u32) > 0.0");
        builder.AppendLine("        && ((a >> 32) & 0b11 != 1 || f32::from_bits(a as u32) <= 1.0)");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("fn valid_packed_shortcut(b: u64) -> bool {");
        builder.AppendLine("    (b >> 27) == 0");
        builder.AppendLine("        && (b & 0xffff) >= 1");
        builder.AppendLine("        && (b & 0xffff) <= 86");
        builder.AppendLine("        && ((b >> 16) & 0xff) <= 63");
        builder.AppendLine(
            "        && (((b & 0xffff) > 36 && (b & 0xffff) < 76 && (b & 0xffff) != 42)"
        );
        builder.AppendLine("            || (b & (41u64 << 16)) != 0)");
        builder.AppendLine("        && ((b & (32u64 << 16)) == 0 || (b & (9u64 << 16)) == 0)");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("pub fn payload_error(operation: u16, a: u64, b: u64) -> i32 {");
        builder.AppendLine("    match operation {");
        foreach (
            var operation in schema.Operations.Where(operation => operation.Validation is not null)
        )
        {
            builder.AppendLine(
                $"        OP_{UpperSnake(operation.Name)} if !({RustValidationExpression(operation.Validation!)}) => {operation.Validation!.Status},"
            );
        }
        builder.AppendLine("        _ => 0,");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#[cfg(test)]");
        builder.AppendLine("mod tests {");
        builder.AppendLine("    use super::*;");
        builder.AppendLine("    use std::collections::HashSet;");
        builder.AppendLine();
        builder.AppendLine("    #[test]");
        builder.AppendLine(
            "    fn generated_registry_has_unique_ids_and_resolvable_capabilities() {"
        );
        builder.AppendLine(
            "        let component_ids: HashSet<_> = COMPONENTS.iter().map(|item| item.id).collect();"
        );
        builder.AppendLine(
            "        let operation_ids: HashSet<_> = OPERATIONS.iter().map(|item| item.id).collect();"
        );
        builder.AppendLine("        assert_eq!(component_ids.len(), COMPONENTS.len());");
        builder.AppendLine("        assert_eq!(operation_ids.len(), OPERATIONS.len());");
        builder.AppendLine("        assert!(OPERATIONS.iter().all(|operation| {");
        builder.AppendLine("            COMPONENTS");
        builder.AppendLine("                .iter()");
        builder.AppendLine("                .any(|component| operation.applies_to(component.id))");
        builder.AppendLine("        }));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    #[test]");
        builder.AppendLine("    fn value_kind_layout_matches_the_wire_contract() {");
        builder.AppendLine("        assert_eq!(ValueKind::None as u16, 0);");
        builder.AppendLine("        assert_eq!(ValueKind::F32 as u16, 1);");
        builder.AppendLine("        assert_eq!(ValueKind::U32 as u16, 2);");
        builder.AppendLine("        assert_eq!(ValueKind::Callback as u16, 3);");
        builder.AppendLine("        assert_eq!(ValueKind::U64 as u16, 4);");
        builder.AppendLine("        assert_eq!(ValueKind::F32x2 as u16, 5);");
        builder.AppendLine("        assert_eq!(ValueKind::Data as u16, 6);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RustValidationExpression(Validation validation) =>
        validation.Kind switch
        {
            "packedCommandShortcut" => "valid_packed_shortcut(b)",
            "bool" => "a <= 1",
            "u32Min" => $"a >= {RustUnsignedLiteral(validation.Min!.Value)}",
            "u32Max" => $"a <= {RustUnsignedLiteral(validation.Max!.Value)}",
            "u32Range" =>
                $"a >= {RustUnsignedLiteral(validation.Min!.Value)} && a <= {RustUnsignedLiteral(validation.Max!.Value)}",
            "f32Min" =>
                $"f32::from_bits(a as u32) {(validation.MinExclusive ? ">" : ">=")} {RustFloatLiteral(validation.Min!.Value)}",
            "f32Range" =>
                $"f32_payload_in_range(a, {RustFloatLiteral(validation.Min!.Value)}, {RustFloatLiteral(validation.Max!.Value)})",
            "packedTableColumn" => "valid_packed_table_column(a)",
            _ => throw new InvalidOperationException(
                $"Unknown validation kind '{validation.Kind}'."
            ),
        };

    private static string RustUnsignedLiteral(double value) => $"{checked((ulong)value)}u64";

    private static string RustFloatLiteral(double value) =>
        $"{value.ToString("R", CultureInfo.InvariantCulture)}f32";
}
