using System.Globalization;
using System.Text;

internal static partial class BindingGenerator
{
    private static string GenerateCSharpProtocol(BindingSchema schema, ulong hash)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace Gpui.Interop");
        builder.AppendLine("{");
        builder.AppendLine("    internal enum ComponentId : ushort");
        builder.AppendLine("    {");
        foreach (var component in schema.Components)
        {
            builder.AppendLine($"        {component.CSharp} = {component.Id},");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal enum OpCode : ushort");
        builder.AppendLine("    {");
        foreach (var operation in schema.Operations)
        {
            builder.AppendLine($"        {Pascal(operation.Name)} = {operation.Id},");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal enum ValueKind : ushort");
        builder.AppendLine("    {");
        builder.AppendLine("        None = 0,");
        builder.AppendLine("        F32 = 1,");
        builder.AppendLine("        U32 = 2,");
        builder.AppendLine("        Callback = 3,");
        builder.AppendLine("        U64 = 4,");
        builder.AppendLine("        F32x2 = 5,");
        builder.AppendLine("        Data = 6,");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal enum ResourceKind : ushort");
        builder.AppendLine("    {");
        foreach (var resource in schema.Resources)
        {
            builder.AppendLine($"        {resource.CSharp} = {resource.Id},");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal enum ResourceCommandKind : ushort");
        builder.AppendLine("    {");
        foreach (var resource in schema.Resources)
        {
            foreach (var command in resource.Commands)
            {
                if (command.Doc is { } commandDoc)
                {
                    builder.AppendLine($"        /// <summary>{XmlDoc(commandDoc)}</summary>");
                }
                builder.AppendLine($"        {command.CSharp} = {command.Id},");
            }
        }
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static class SemanticRegistry");
        builder.AppendLine("    {");
        builder.AppendLine($"        internal const uint SchemaVersion = {schema.SchemaVersion};");
        builder.AppendLine($"        internal const ulong SchemaHash = 0x{hash:X16}UL;");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static bool IsKnownComponent(ComponentId component) => component switch"
        );
        builder.AppendLine("        {");
        foreach (var component in schema.Components)
        {
            builder.AppendLine($"            ComponentId.{component.CSharp} => true,");
        }
        builder.AppendLine("            _ => false,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static bool IsDataRequired(ComponentId component) => component switch"
        );
        builder.AppendLine("        {");
        foreach (var component in schema.Components.Where(c => c.DataRequired))
        {
            builder.AppendLine($"            ComponentId.{component.CSharp} => true,");
        }
        builder.AppendLine("            _ => false,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static ValueKind? ExpectedValueKind(OpCode operation) => operation switch"
        );
        builder.AppendLine("        {");
        foreach (var operation in schema.Operations)
        {
            builder.AppendLine(
                $"            OpCode.{Pascal(operation.Name)} => ValueKind.{Pascal(operation.Value)},"
            );
        }
        builder.AppendLine("            _ => null,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        private static ulong Capabilities(ComponentId component) => component switch"
        );
        builder.AppendLine("        {");
        foreach (var component in schema.Components)
        {
            builder.AppendLine(
                $"            ComponentId.{component.CSharp} => 0x{CapabilityMask(schema, component.Capabilities):X16}UL,"
            );
        }
        builder.AppendLine("            _ => 0,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        private static ulong RequiredCapability(OpCode operation) => operation switch"
        );
        builder.AppendLine("        {");
        foreach (var operation in schema.Operations)
        {
            builder.AppendLine(
                $"            OpCode.{Pascal(operation.Name)} => 0x{CapabilityBit(schema, operation.Requires):X16}UL,"
            );
        }
        builder.AppendLine("            _ => 0,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static bool IsAllowed(ComponentId component, OpCode operation)"
        );
        builder.AppendLine("        {");
        builder.AppendLine("            var required = RequiredCapability(operation);");
        builder.AppendLine(
            "            return required != 0 && (Capabilities(component) & required) == required;"
        );
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static bool AllowsPayload(OpCode operation) => operation switch"
        );
        builder.AppendLine("        {");
        foreach (
            var operation in schema.Operations.Where(operation => operation.Payload == "event")
        )
        {
            builder.AppendLine($"            OpCode.{Pascal(operation.Name)} => true,");
        }
        builder.AppendLine("            _ => false,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine(
            "        internal static int PayloadError(OpCode operation, ulong a, ulong b) => operation switch"
        );
        builder.AppendLine("        {");
        foreach (
            var operation in schema.Operations.Where(operation => operation.Validation is not null)
        )
        {
            builder.AppendLine(
                $"            OpCode.{Pascal(operation.Name)} when !({CSharpValidationExpression(operation.Validation!)}) => {operation.Validation!.Status},"
            );
        }
        builder.AppendLine("            _ => 0,");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GenerateCSharpElements(BindingSchema schema)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using Gpui.Interop;");
        builder.AppendLine();
        builder.AppendLine("namespace Gpui");
        builder.AppendLine("{");
        foreach (var capability in schema.Capabilities)
        {
            builder.AppendLine($"    public interface {CapabilityInterface(capability)} {{ }}");
        }
        builder.AppendLine();
        foreach (var component in schema.Components)
        {
            var interfaces = string.Join(", ", component.Capabilities.Select(CapabilityInterface));
            builder.AppendLine(
                $"    public readonly struct {component.CSharp}Tag : {interfaces} {{ }}"
            );
        }
        builder.AppendLine();
        foreach (var enumSchema in schema.Enums)
        {
            builder.AppendLine($"    public enum {enumSchema.CSharp} : uint");
            builder.AppendLine("    {");
            foreach (var variant in enumSchema.Variants)
            {
                builder.AppendLine($"        {variant.CSharp} = {variant.Value},");
            }
            builder.AppendLine("    }");
            builder.AppendLine();
        }
        foreach (
            var group in schema.ControlEvents.Select(controlEvent => controlEvent.Group).Distinct()
        )
        {
            builder.AppendLine($"    public enum {Pascal(group)}EventKind : ushort");
            builder.AppendLine("    {");
            foreach (
                var controlEvent in schema.ControlEvents.Where(controlEvent =>
                    controlEvent.Group == group
                )
            )
            {
                if (controlEvent.Doc is { } eventDoc)
                {
                    builder.AppendLine($"        /// <summary>{XmlDoc(eventDoc)}</summary>");
                }
                builder.AppendLine($"        {controlEvent.CSharp} = {controlEvent.Id},");
            }
            builder.AppendLine("    }");
            builder.AppendLine();
        }
        builder.AppendLine("    public readonly unsafe ref partial struct RenderContext");
        builder.AppendLine("    {");
        foreach (
            var component in schema.Components.Where(component =>
                component.ManagedFactory != "manual"
            )
        )
        {
            AppendManagedFactory(builder, component);
        }
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static partial class ElementExtensions");
        builder.AppendLine("    {");
        AppendParentApis(builder);
        foreach (
            var operation in schema.Operations.Where(operation =>
                operation.ManagedApi is not null and not "click"
            )
        )
        {
            AppendManagedApi(builder, operation);
        }
        foreach (
            var operation in schema.Operations.Where(operation =>
                operation.ManagedMethod is not null
            )
        )
        {
            AppendManagedMethod(builder, schema, operation);
        }
        foreach (var method in schema.LengthMethods)
        {
            AppendLengthMethod(builder, schema, method);
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendManagedFactory(StringBuilder builder, Component component)
    {
        var elementType = $"Element<{component.CSharp}Tag>";
        var componentId = $"ComponentId.{component.CSharp}";
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        switch (component.ManagedFactory)
        {
            case "container":
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(params ReadOnlySpan<Element> children)"
                );
                builder.AppendLine("        {");
                builder.AppendLine(
                    $"            var element = ArenaWriter.AddNode<{component.CSharp}Tag>(_arena, {componentId});"
                );
                builder.AppendLine("            ArenaWriter.AddChildren(element.Inner, children);");
                builder.AppendLine("            return element;");
                builder.AppendLine("        }");
                break;
            case "idContainer":
            {
                // dataRequired components reject empty ids before the FFI boundary; the
                // native validator would otherwise fail the whole snapshot at decode time.
                var guard = component.DataRequired;
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<char> id, params ReadOnlySpan<Element> children)"
                );
                builder.AppendLine("        {");
                if (guard)
                {
                    builder.AppendLine("            if (id.IsEmpty)");
                    builder.AppendLine("            {");
                    builder.AppendLine(
                        "                throw new ArgumentException(\"A non-empty element id is required.\", nameof(id));"
                    );
                    builder.AppendLine("            }");
                }
                builder.AppendLine(
                    $"            var element = ArenaWriter.AddNode<{component.CSharp}Tag>(_arena, {componentId}, id);"
                );
                AppendInteractiveOwner(builder, component);
                builder.AppendLine("            ArenaWriter.AddChildren(element.Inner, children);");
                builder.AppendLine("            return element;");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<byte> utf8Id, params ReadOnlySpan<Element> children)"
                );
                builder.AppendLine("        {");
                if (guard)
                {
                    builder.AppendLine("            if (utf8Id.IsEmpty)");
                    builder.AppendLine("            {");
                    builder.AppendLine(
                        "                throw new ArgumentException(\"A non-empty element id is required.\", nameof(utf8Id));"
                    );
                    builder.AppendLine("            }");
                }
                builder.AppendLine(
                    $"            var element = ArenaWriter.AddNode<{component.CSharp}Tag>(_arena, {componentId}, utf8Id);"
                );
                AppendInteractiveOwner(builder, component);
                builder.AppendLine("            ArenaWriter.AddChildren(element.Inner, children);");
                builder.AppendLine("            return element;");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<char> id, ReadOnlySpan<char> label)"
                );
                builder.AppendLine("        {");
                builder.AppendLine("            var child = Text(label);");
                builder.AppendLine($"            return {component.CSharp}(id, child);");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<char> id, ReadOnlySpan<byte> utf8Label)"
                );
                builder.AppendLine("        {");
                builder.AppendLine("            var child = Text(utf8Label);");
                builder.AppendLine($"            return {component.CSharp}(id, child);");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<char> label)"
                );
                builder.AppendLine("        {");
                builder.AppendLine("            var child = Text(label);");
                builder.AppendLine($"            return {component.CSharp}(utf8Id, child);");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                builder.AppendLine(
                    $"        public {elementType} {component.CSharp}(ReadOnlySpan<byte> utf8Id, ReadOnlySpan<byte> utf8Label)"
                );
                builder.AppendLine("        {");
                builder.AppendLine("            var child = Text(utf8Label);");
                builder.AppendLine($"            return {component.CSharp}(utf8Id, child);");
                builder.AppendLine("        }");
                break;
            }
            case "leaf":
                builder.AppendLine($"        public {elementType} {component.CSharp}() =>");
                builder.AppendLine(
                    $"            ArenaWriter.AddNode<{component.CSharp}Tag>(_arena, {componentId});"
                );
                break;
            default:
                throw new InvalidOperationException();
        }
        builder.AppendLine();
    }

    private static void AppendInteractiveOwner(StringBuilder builder, Component component)
    {
        if (component.Capabilities.Contains("interactive", StringComparer.Ordinal))
        {
            builder.AppendLine("            AddInteractiveOwner(element.Inner);");
        }
    }

    private static void AppendParentApis(StringBuilder builder)
    {
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine(
            "        public static Element<TTag> Child<TTag>(this Element<TTag> parent, Element child)"
        );
        builder.AppendLine("            where TTag : unmanaged, IParentElementTag");
        builder.AppendLine("        {");
        builder.AppendLine("            Span<Element> one = [child];");
        builder.AppendLine("            ArenaWriter.AddChildren(parent.Inner, one);");
        builder.AppendLine("            return parent;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine(
            "        public static Element<TTag> Children<TTag>(this Element<TTag> parent, params ReadOnlySpan<Element> children)"
        );
        builder.AppendLine("            where TTag : unmanaged, IParentElementTag");
        builder.AppendLine("        {");
        builder.AppendLine("            ArenaWriter.AddChildren(parent.Inner, children);");
        builder.AppendLine("            return parent;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void AppendManagedMethod(
        StringBuilder builder,
        BindingSchema schema,
        Operation operation
    )
    {
        var method = operation.ManagedMethod!;
        if (method.Kind is "strings" or "pairs")
        {
            AppendListMethod(builder, operation, method);
            builder.AppendLine();
            return;
        }
        if (method.Kind == "string")
        {
            AppendStringMethod(builder, operation, method, utf8: false);
            builder.AppendLine();
            AppendStringMethod(builder, operation, method, utf8: true);
            builder.AppendLine();
            return;
        }
        var parameter = method.Kind switch
        {
            "f32" => $", float {method.Param}{FormatOptionalDefault(method.Default)}",
            "f32x2" => $", float {method.Param}X, float {method.Param}Y",
            "u16" => $", ushort {method.Param}",
            "i16" => $", short {method.Param}",
            "u32" => $", uint {method.Param}",
            "u64" => $", ulong {method.Param}",
            "color" => $", Color {method.Param}",
            "enum" => $", {EnumCSharp(schema, method.Enum!)} {method.Param}",
            _ => throw new InvalidOperationException(),
        };
        var opCode = Pascal(operation.Name);
        var statement = method.Kind switch
        {
            "f32" => $"ArenaWriter.AddF32(element.Inner, OpCode.{opCode}, {method.Param});",
            "f32x2" =>
                $"ArenaWriter.AddF32x2(element.Inner, OpCode.{opCode}, {method.Param}X, {method.Param}Y);",
            "u16" => $"ArenaWriter.AddU32(element.Inner, OpCode.{opCode}, {method.Param});",
            "i16" =>
                $"ArenaWriter.AddU32(element.Inner, OpCode.{opCode}, (uint)(ushort){method.Param});",
            "u32" => $"ArenaWriter.AddU32(element.Inner, OpCode.{opCode}, {method.Param});",
            "u64" => $"ArenaWriter.AddU64(element.Inner, OpCode.{opCode}, {method.Param});",
            "color" => $"ArenaWriter.AddU32(element.Inner, OpCode.{opCode}, {method.Param}.Rgba);",
            "enum" => $"ArenaWriter.AddU32(element.Inner, OpCode.{opCode}, (uint){method.Param});",
            _ => throw new InvalidOperationException(),
        };

        builder.AppendLine($"        /// <summary>{XmlDoc(method.Doc)}</summary>");
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine(
            $"        public static Element<TTag> {method.Method}<TTag>(this Element<TTag> element{parameter})"
        );
        builder.AppendLine(
            $"            where TTag : unmanaged, {CapabilityInterface(operation.Requires)}"
        );
        builder.AppendLine("        {");
        AppendMethodGuard(builder, method, schema);
        builder.AppendLine($"            {statement}");
        builder.AppendLine("            return element;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void AppendListMethod(
        StringBuilder builder,
        Operation operation,
        ManagedMethod method
    )
    {
        var opCode = Pascal(operation.Name);
        var parameterType = method.Kind == "pairs" ? "(string Tag, uint Value)" : "string";
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        /// <summary>{XmlDoc(method.Doc)}</summary>");
        builder.AppendLine(
            $"        public static Element<TTag> {method.Method}<TTag>(this Element<TTag> element, params ReadOnlySpan<{parameterType}> {method.Param})"
        );
        builder.AppendLine(
            $"            where TTag : unmanaged, {CapabilityInterface(operation.Requires)}"
        );
        builder.AppendLine("        {");
        builder.AppendLine($"            if ({method.Param}.IsEmpty)");
        builder.AppendLine("            {");
        builder.AppendLine(
            $"                throw new ArgumentException(\"At least one entry is required.\", nameof({method.Param}));"
        );
        builder.AppendLine("            }");
        builder.AppendLine();
        if (method.Kind == "pairs")
        {
            builder.AppendLine($"            foreach (var (tag, _) in {method.Param})");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                var validTag = tag is not null && tag.Length > 0 && tag.Length <= 4;"
            );
            builder.AppendLine("                for (var i = 0; validTag && i < tag.Length; i++)");
            builder.AppendLine("                {");
            builder.AppendLine("                    validTag = char.IsAsciiLetterOrDigit(tag[i]);");
            builder.AppendLine("                }");
            builder.AppendLine("                if (!validTag)");
            builder.AppendLine("                {");
            builder.AppendLine(
                $"                    throw new ArgumentException(\"Feature tags must be 1-4 ASCII letters or digits.\", nameof({method.Param}));"
            );
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine(
                $"            ArenaWriter.AddFeatureData(element.Inner, OpCode.{opCode}, {method.Param});"
            );
        }
        else
        {
            builder.AppendLine($"            foreach (var entry in {method.Param})");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                if (string.IsNullOrEmpty(entry) || entry.Contains(','))"
            );
            builder.AppendLine("                {");
            builder.AppendLine(
                $"                    throw new ArgumentException(\"Entries must be non-empty and contain no commas.\", nameof({method.Param}));"
            );
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine(
                $"            ArenaWriter.AddJoinedData(element.Inner, OpCode.{opCode}, {method.Param}, ',');"
            );
        }
        builder.AppendLine("            return element;");
        builder.AppendLine("        }");
    }

    private static void AppendStringMethod(
        StringBuilder builder,
        Operation operation,
        ManagedMethod method,
        bool utf8
    )
    {
        var opCode = Pascal(operation.Name);
        var parameter = utf8
            ? $"utf8{char.ToUpperInvariant(method.Param[0]) + method.Param[1..]}"
            : method.Param;
        var parameterType = utf8 ? "ReadOnlySpan<byte>" : "ReadOnlySpan<char>";
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        /// <summary>{XmlDoc(method.Doc)}</summary>");
        builder.AppendLine(
            $"        public static Element<TTag> {method.Method}<TTag>(this Element<TTag> element, {parameterType} {parameter})"
        );
        builder.AppendLine(
            $"            where TTag : unmanaged, {CapabilityInterface(operation.Requires)}"
        );
        builder.AppendLine("        {");
        builder.AppendLine($"            if ({parameter}.IsEmpty)");
        builder.AppendLine("            {");
        builder.AppendLine(
            $"                throw new ArgumentException(\"A non-empty value is required.\", nameof({parameter}));"
        );
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine(
            $"            ArenaWriter.AddData(element.Inner, OpCode.{opCode}, {parameter});"
        );
        builder.AppendLine("            return element;");
        builder.AppendLine("        }");
    }

    private static void AppendMethodGuard(
        StringBuilder builder,
        ManagedMethod method,
        BindingSchema schema
    )
    {
        if (method.Guard == "positive")
        {
            builder.AppendLine(
                $"            if (!float.IsFinite({method.Param}) || {method.Param} <= 0)"
            );
            builder.AppendLine("            {");
            builder.AppendLine(
                $"                throw new ArgumentOutOfRangeException(nameof({method.Param}), \"{XmlDoc(method.GuardMessage!)}\");"
            );
            builder.AppendLine("            }");
            builder.AppendLine();
        }
        else if (method.Guard == "nonZero")
        {
            builder.AppendLine($"            if ({method.Param} == 0)");
            builder.AppendLine("            {");
            builder.AppendLine(
                $"                throw new ArgumentOutOfRangeException(nameof({method.Param}), \"{XmlDoc(method.GuardMessage!)}\");"
            );
            builder.AppendLine("            }");
            builder.AppendLine();
        }
        else if (method.Kind == "enum")
        {
            var max = MaxEnumVariant(schema, method.Enum!);
            builder.AppendLine(
                $"            if ((uint){method.Param} > (uint)global::Gpui.{EnumCSharp(schema, method.Enum!)}.{max})"
            );
            builder.AppendLine("            {");
            builder.AppendLine(
                $"                throw new ArgumentOutOfRangeException(nameof({method.Param}));"
            );
            builder.AppendLine("            }");
            builder.AppendLine();
        }
    }

    private static void AppendLengthMethod(
        StringBuilder builder,
        BindingSchema schema,
        LengthMethod method
    )
    {
        var px = schema.Operations.First(operation => operation.Name == method.Px);
        var percent = schema.Operations.First(operation => operation.Name == method.Percent);
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        /// <summary>{XmlDoc(method.Doc)}</summary>");
        builder.AppendLine(
            $"        public static Element<TTag> {method.Method}<TTag>(this Element<TTag> element, Length value)"
        );
        builder.AppendLine(
            $"            where TTag : unmanaged, {CapabilityInterface(px.Requires)}"
        );
        builder.AppendLine("        {");
        builder.AppendLine("            switch (value.Unit)");
        builder.AppendLine("            {");
        builder.AppendLine("                case LengthUnit.Pixels:");
        builder.AppendLine(
            $"                    ArenaWriter.AddF32(element.Inner, OpCode.{Pascal(px.Name)}, value.Value);"
        );
        builder.AppendLine("                    break;");
        builder.AppendLine("                case LengthUnit.Percent:");
        builder.AppendLine(
            $"                    ArenaWriter.AddF32(element.Inner, OpCode.{Pascal(percent.Name)}, value.Value);"
        );
        builder.AppendLine("                    break;");
        builder.AppendLine("                default:");
        builder.AppendLine(
            "                    throw new ArgumentOutOfRangeException(nameof(value));"
        );
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return element;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static string EnumCSharp(BindingSchema schema, string name) =>
        schema.Enums.First(e => e.Name == name).CSharp;

    private static string MaxEnumVariant(BindingSchema schema, string name) =>
        schema
            .Enums.First(e => e.Name == name)
            .Variants.OrderByDescending(variant => variant.Value)
            .First()
            .CSharp;

    private static string FormatOptionalDefault(double? value)
    {
        if (value is not double defaultValue)
        {
            return string.Empty;
        }
        var literal =
            defaultValue == Math.Truncate(defaultValue)
                ? $"{checked((long)defaultValue)}"
                : CSharpFloatLiteral(defaultValue);
        return $" = {literal}";
    }

    private static void AppendManagedApi(StringBuilder builder, Operation operation)
    {
        var parameter = operation.ManagedApi switch
        {
            "pixels" => ", Pixels value",
            "color" => ", Color color",
            "bool" => ", bool value",
            "click" => ", Callback<ClickEvent> callback",
            _ => string.Empty,
        };
        var statement = operation.ManagedApi switch
        {
            "extension" => $"ArenaWriter.AddNoArg(element.Inner, OpCode.{Pascal(operation.Name)});",
            "pixels" =>
                $"ArenaWriter.AddF32(element.Inner, OpCode.{Pascal(operation.Name)}, value.Value);",
            "color" =>
                $"ArenaWriter.AddU32(element.Inner, OpCode.{Pascal(operation.Name)}, color.Rgba);",
            "bool" =>
                $"ArenaWriter.AddU32(element.Inner, OpCode.{Pascal(operation.Name)}, value ? 1u : 0u);",
            "click" =>
                $"ArenaWriter.AddCallback(element.Inner, OpCode.{Pascal(operation.Name)}, callback.Token);",
            _ => throw new InvalidOperationException(),
        };

        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine(
            $"        public static Element<TTag> {operation.CSharp}<TTag>(this Element<TTag> element{parameter})"
        );
        builder.AppendLine(
            $"            where TTag : unmanaged, {CapabilityInterface(operation.Requires)}"
        );
        builder.AppendLine("        {");
        if (operation.ManagedApi == "click")
        {
            builder.AppendLine("            if (callback.IsDefault)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new ArgumentException(\"Event token 0 is reserved.\", nameof(callback));"
            );
            builder.AppendLine("            }");
            builder.AppendLine();
        }
        builder.AppendLine($"            {statement}");
        builder.AppendLine("            return element;");
        builder.AppendLine("        }");
        builder.AppendLine();

        if (operation.ManagedApi == "click")
        {
            builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            builder.AppendLine(
                $"        public static Element<TTag> {operation.CSharp}<TTag>(this Element<TTag> element, Callback<ClickEvent> callback, ulong payload)"
            );
            builder.AppendLine(
                $"            where TTag : unmanaged, {CapabilityInterface(operation.Requires)}"
            );
            builder.AppendLine("        {");
            builder.AppendLine("            if (callback.IsDefault)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new ArgumentException(\"Event token 0 is reserved.\", nameof(callback));"
            );
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine(
                $"            ArenaWriter.AddCallback(element.Inner, OpCode.{Pascal(operation.Name)}, callback.Token, payload);"
            );
            builder.AppendLine("            return element;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
    }

    private static string CSharpValidationExpression(Validation validation) =>
        validation.Kind switch
        {
            "packedCommandShortcut" =>
                "(b >> 27) == 0 && (b & 0xffff) >= 1 && (b & 0xffff) <= 86 && ((b >> 16) & 0xff) <= 63 && (((b & 0xffff) > 36 && (b & 0xffff) < 76 && (b & 0xffff) != 42) || (b & (41UL << 16)) != 0) && ((b & (32UL << 16)) == 0 || (b & (9UL << 16)) == 0)",
            "bool" => "a <= 1UL",
            "u32Min" => $"a >= {CSharpUnsignedLiteral(validation.Min!.Value)}",
            "u32Max" => $"a <= {CSharpUnsignedLiteral(validation.Max!.Value)}",
            "u32Range" =>
                $"a >= {CSharpUnsignedLiteral(validation.Min!.Value)} && a <= {CSharpUnsignedLiteral(validation.Max!.Value)}",
            "f32Min" =>
                $"BitConverter.UInt32BitsToSingle((uint)a) {(validation.MinExclusive ? ">" : ">=")} {CSharpFloatLiteral(validation.Min!.Value)}",
            "f32Range" =>
                $"BitConverter.UInt32BitsToSingle((uint)a) >= {CSharpFloatLiteral(validation.Min!.Value)} && BitConverter.UInt32BitsToSingle((uint)a) <= {CSharpFloatLiteral(validation.Max!.Value)}",
            "packedTableColumn" =>
                "(a >> 36) == 0 && ((a >> 32) & 0b11) <= 1 && ((a >> 34) & 0b11) <= 2 && float.IsFinite(BitConverter.UInt32BitsToSingle((uint)a)) && BitConverter.UInt32BitsToSingle((uint)a) > 0f && (((a >> 32) & 0b11) != 1 || BitConverter.UInt32BitsToSingle((uint)a) <= 1f)",
            _ => throw new InvalidOperationException(
                $"Unknown validation kind '{validation.Kind}'."
            ),
        };

    private static string CSharpUnsignedLiteral(double value) => $"{checked((ulong)value)}UL";

    private static string CSharpFloatLiteral(double value) =>
        $"{value.ToString("R", CultureInfo.InvariantCulture)}f";
}
