[package]
name = "gpui-dotnet-editor-provider"
version.workspace = true
edition = "2024"
publish = false

[lib]
name = "gpui_dotnet_editor_provider"
crate-type = ["rlib"]

[dependencies]
gpui = { package = "gpui-pre", version = "0.3.1" }
gpui-component = { path = "../../../../external/gpui-kit/crates/component", features = ["tree-sitter-rust"] }
gpui-dotnet = { path = "../.." }
ropey = "=2.0.0-beta.1"

[dev-dependencies]
gpui = { package = "gpui-pre", version = "0.3.1", features = ["test-support"] }

[lints]
workspace = true
