<Project>
    <PropertyGroup>
        <_GpuiIsWindowsTarget
            Condition="
                '$(TargetPlatformIdentifier)' == 'Windows'
                or $([MSBuild]::IsOSPlatform('Windows'))
                or $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win-'))">true</_GpuiIsWindowsTarget>
    </PropertyGroup>

    <PropertyGroup
        Condition="
            '$(_GpuiIsWindowsTarget)' == 'true'
            and ('$(OutputType)' == 'Exe' or '$(OutputType)' == 'WinExe')
            and '$(ApplicationManifest)' == ''
            and '$(NoWin32Manifest)' != 'true'">
        <ApplicationManifest>$(MSBuildThisFileDirectory)GPUI.NET.Windows.manifest</ApplicationManifest>
    </PropertyGroup>
</Project>
