fn main() {
    println!("cargo:rerun-if-changed=src/abi.rs");
    println!("cargo:rerun-if-changed=src/lib.rs");

    csbindgen::Builder::default()
        .input_extern_file("src/lib.rs")
        .input_extern_file("hosts/default/src/lib.rs")
        .input_extern_file("src/abi.rs")
        .csharp_dll_name("gpui_dotnet")
        .csharp_namespace("Gpui.Interop")
        .csharp_class_name("NativeMethods")
        .csharp_class_accessibility("internal")
        .csharp_file_header("// <auto-generated />\n#nullable enable")
        .always_included_types([
            "NodeRecord",
            "OpRecord",
            "ChildRecord",
            "RenderArena",
            "NativeClickEvent",
            "NativeControlEvent",
            "NativeResourceCommand",
            "NativeExtensionCommand",
            "NativeApplicationCommand",
            "NativeMenuCommand",
            "NativeMenuRecord",
            "ManagedCallbacks",
            "GpuiDotnetApiV3",
        ])
        .generate_csharp_file("../../src/Gpui/Interop/NativeMethods.g.cs")
        .expect("failed to generate C# native bindings");
}
