// @generated by Gpui.Bindings.Generator. Do not edit.

namespace Gpui.Components;

internal static class ComponentSchema
{
    internal const string ExtensionId = "gpui.net.components";
    internal const uint SchemaVersion = 1u;
    internal const ulong SchemaHash = 0x96D6AEE59A1C9B2CUL;

    internal static class Spinner
    {
        internal const string Kind = "spinner";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Icon
        {
            Loader,
            LoaderCircle,
        }

        internal enum Ease
        {
            Linear,
            EaseInOut,
            EaseOutQuint,
        }

        internal static string EncodeConfiguration(Size size, Icon icon, Ease ease, string color)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var iconValue = icon switch
            {
                Icon.Loader => "loader",
                Icon.LoaderCircle => "loader_circle",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(icon)),
            };
            var easeValue = ease switch
            {
                Ease.Linear => "linear",
                Ease.EaseInOut => "ease_in_out",
                Ease.EaseOutQuint => "ease_out_quint",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(ease)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{iconValue}\n{easeValue}\n{color}");
        }
    }

    internal static class Skeleton
    {
        internal const string Kind = "skeleton";

        internal static string EncodeConfiguration(bool secondary)
        {
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{(secondary ? 1 : 0)}");
        }
    }

    internal static class Separator
    {
        internal const string Kind = "separator";

        internal enum Orientation
        {
            Horizontal,
            Vertical,
        }

        internal static string EncodeConfiguration(Orientation orientation, bool dashed, string label, string color)
        {
            var orientationValue = orientation switch
            {
                Orientation.Horizontal => "horizontal",
                Orientation.Vertical => "vertical",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(orientation)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{orientationValue}\n{(dashed ? 1 : 0)}\n{label}\n{color}");
        }
    }

    internal static class Badge
    {
        internal const string Kind = "badge";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool dot, uint count, uint max, string color)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(dot ? 1 : 0)}\n{count}\n{max}\n{color}");
        }
    }

    internal static class Tag
    {
        internal const string Kind = "tag";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Primary,
            Secondary,
            Danger,
            Success,
            Warning,
            Info,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, bool outline, bool roundedFull)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Primary => "primary",
                Variant.Secondary => "secondary",
                Variant.Danger => "danger",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Info => "info",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{(outline ? 1 : 0)}\n{(roundedFull ? 1 : 0)}");
        }
    }

    internal static class Progress
    {
        internal const string Kind = "progress";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, float value, bool loading, string color, string accessibilityLabel)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            if (!float.IsFinite(value))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(value), "Extension configuration numbers must be finite.");
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{value}\n{(loading ? 1 : 0)}\n{color}\n{accessibilityLabel}");
        }
    }

    internal static class ProgressCircle
    {
        internal const string Kind = "progress_circle";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, float value, bool loading, string color, string accessibilityLabel)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            if (!float.IsFinite(value))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(value), "Extension configuration numbers must be finite.");
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{value}\n{(loading ? 1 : 0)}\n{color}\n{accessibilityLabel}");
        }
    }

    internal static class Rating
    {
        internal const string Kind = "rating";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, uint value, uint max, bool disabled, string color, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{value}\n{max}\n{(disabled ? 1 : 0)}\n{color}\n{changedEvent}");
        }
    }

    internal static class Button
    {
        internal const string Kind = "button";
        internal const ushort EventClicked = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Default,
            Primary,
            Secondary,
            Danger,
            Success,
            Warning,
            Info,
            Ghost,
            Link,
            Text,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, string label, string accessibilityLabel, bool disabled, bool selected, bool loading, bool outline, bool compact, ulong clickedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Default => "default",
                Variant.Primary => "primary",
                Variant.Secondary => "secondary",
                Variant.Danger => "danger",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Info => "info",
                Variant.Ghost => "ghost",
                Variant.Link => "link",
                Variant.Text => "text",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{label}\n{accessibilityLabel}\n{(disabled ? 1 : 0)}\n{(selected ? 1 : 0)}\n{(loading ? 1 : 0)}\n{(outline ? 1 : 0)}\n{(compact ? 1 : 0)}\n{clickedEvent}");
        }
    }

    internal static class Alert
    {
        internal const string Kind = "alert";
        internal const ushort EventClosed = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Default,
            Info,
            Success,
            Warning,
            Error,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, string title, string message, bool banner, ulong closedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Default => "default",
                Variant.Info => "info",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Error => "error",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            global::System.ArgumentNullException.ThrowIfNull(message);
            if (message.Contains('\0') || message.Contains('\n') || message.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(message));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{title}\n{message}\n{(banner ? 1 : 0)}\n{closedEvent}");
        }
    }

    internal static class GroupBox
    {
        internal const string Kind = "group_box";

        internal enum Variant
        {
            Normal,
            Fill,
            Outline,
        }

        internal static string EncodeConfiguration(Variant variant, string title)
        {
            var variantValue = variant switch
            {
                Variant.Normal => "normal",
                Variant.Fill => "fill",
                Variant.Outline => "outline",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{variantValue}\n{title}");
        }
    }
}
