// @generated by Gpui.Bindings.Generator. Do not edit.

namespace Gpui.Components;

internal static class ComponentSchema
{
    internal const string ExtensionId = "gpui.net.components";
    internal const uint SchemaVersion = 7u;
    internal const ulong SchemaHash = 0x91B9D80440F5A196UL;

    internal static class Attachment
    {
        internal const string Kind = "attachment";
        internal const ushort EventClicked = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Axis
        {
            Horizontal,
            Vertical,
        }

        internal enum Status
        {
            Pending,
            Uploading,
            Processing,
            Failed,
            Complete,
        }

        internal static string EncodeConfiguration(Size size, Axis axis, Status status, string title, string description, string previewSource, bool mediaChild, bool contentChild, bool hasActions, ulong clickedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var axisValue = axis switch
            {
                Axis.Horizontal => "horizontal",
                Axis.Vertical => "vertical",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(axis)),
            };
            var statusValue = status switch
            {
                Status.Pending => "pending",
                Status.Uploading => "uploading",
                Status.Processing => "processing",
                Status.Failed => "failed",
                Status.Complete => "complete",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(status)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            global::System.ArgumentNullException.ThrowIfNull(description);
            if (description.Contains('\0') || description.Contains('\n') || description.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(description));
            }
            global::System.ArgumentNullException.ThrowIfNull(previewSource);
            if (previewSource.Contains('\0') || previewSource.Contains('\n') || previewSource.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(previewSource));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{axisValue}\n{statusValue}\n{title}\n{description}\n{previewSource}\n{(mediaChild ? 1 : 0)}\n{(contentChild ? 1 : 0)}\n{(hasActions ? 1 : 0)}\n{clickedEvent}");
        }
    }

    internal static class Spinner
    {
        internal const string Kind = "spinner";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Icon
        {
            Loader,
            LoaderCircle,
        }

        internal enum Ease
        {
            Linear,
            EaseInOut,
            EaseOutQuint,
        }

        internal static string EncodeConfiguration(Size size, Icon icon, Ease ease, string color)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var iconValue = icon switch
            {
                Icon.Loader => "loader",
                Icon.LoaderCircle => "loader_circle",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(icon)),
            };
            var easeValue = ease switch
            {
                Ease.Linear => "linear",
                Ease.EaseInOut => "ease_in_out",
                Ease.EaseOutQuint => "ease_out_quint",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(ease)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{iconValue}\n{easeValue}\n{color}");
        }
    }

    internal static class Skeleton
    {
        internal const string Kind = "skeleton";

        internal static string EncodeConfiguration(bool secondary)
        {
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{(secondary ? 1 : 0)}");
        }
    }

    internal static class Separator
    {
        internal const string Kind = "separator";

        internal enum Orientation
        {
            Horizontal,
            Vertical,
        }

        internal static string EncodeConfiguration(Orientation orientation, bool dashed, string label, string color)
        {
            var orientationValue = orientation switch
            {
                Orientation.Horizontal => "horizontal",
                Orientation.Vertical => "vertical",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(orientation)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{orientationValue}\n{(dashed ? 1 : 0)}\n{label}\n{color}");
        }
    }

    internal static class Badge
    {
        internal const string Kind = "badge";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool dot, uint count, uint max, string color)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(dot ? 1 : 0)}\n{count}\n{max}\n{color}");
        }
    }

    internal static class Tag
    {
        internal const string Kind = "tag";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Primary,
            Secondary,
            Danger,
            Success,
            Warning,
            Info,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, bool outline, bool roundedFull)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Primary => "primary",
                Variant.Secondary => "secondary",
                Variant.Danger => "danger",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Info => "info",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{(outline ? 1 : 0)}\n{(roundedFull ? 1 : 0)}");
        }
    }

    internal static class Progress
    {
        internal const string Kind = "progress";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, float value, bool loading, string color, string accessibilityLabel)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            if (!float.IsFinite(value))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(value), "Extension configuration numbers must be finite.");
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{value}\n{(loading ? 1 : 0)}\n{color}\n{accessibilityLabel}");
        }
    }

    internal static class ProgressCircle
    {
        internal const string Kind = "progress_circle";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, float diameter, float value, bool loading, string color, string accessibilityLabel)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            if (!float.IsFinite(diameter))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(diameter), "Extension configuration numbers must be finite.");
            }
            if (!float.IsFinite(value))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(value), "Extension configuration numbers must be finite.");
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{diameter}\n{value}\n{(loading ? 1 : 0)}\n{color}\n{accessibilityLabel}");
        }
    }

    internal static class Rating
    {
        internal const string Kind = "rating";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, uint value, uint max, bool disabled, string color, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{value}\n{max}\n{(disabled ? 1 : 0)}\n{color}\n{changedEvent}");
        }
    }

    internal static class Button
    {
        internal const string Kind = "button";
        internal const ushort EventClicked = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Default,
            Primary,
            Secondary,
            Danger,
            Success,
            Warning,
            Info,
            Ghost,
            Link,
            Text,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, string label, string accessibilityLabel, bool disabled, bool selected, bool loading, bool outline, bool compact, ulong clickedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Default => "default",
                Variant.Primary => "primary",
                Variant.Secondary => "secondary",
                Variant.Danger => "danger",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Info => "info",
                Variant.Ghost => "ghost",
                Variant.Link => "link",
                Variant.Text => "text",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{label}\n{accessibilityLabel}\n{(disabled ? 1 : 0)}\n{(selected ? 1 : 0)}\n{(loading ? 1 : 0)}\n{(outline ? 1 : 0)}\n{(compact ? 1 : 0)}\n{clickedEvent}");
        }
    }

    internal static class Alert
    {
        internal const string Kind = "alert";
        internal const ushort EventClosed = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Default,
            Info,
            Success,
            Warning,
            Error,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, string title, string message, bool banner, ulong closedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Default => "default",
                Variant.Info => "info",
                Variant.Success => "success",
                Variant.Warning => "warning",
                Variant.Error => "error",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            global::System.ArgumentNullException.ThrowIfNull(message);
            if (message.Contains('\0') || message.Contains('\n') || message.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(message));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{title}\n{message}\n{(banner ? 1 : 0)}\n{closedEvent}");
        }
    }

    internal static class GroupBox
    {
        internal const string Kind = "group_box";

        internal enum Variant
        {
            Normal,
            Fill,
            Outline,
        }

        internal static string EncodeConfiguration(Variant variant, string title)
        {
            var variantValue = variant switch
            {
                Variant.Normal => "normal",
                Variant.Fill => "fill",
                Variant.Outline => "outline",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{variantValue}\n{title}");
        }
    }

    internal static class Label
    {
        internal const string Kind = "label";

        internal static string EncodeConfiguration(string text, string secondary, bool masked, string highlight, bool highlightPrefix)
        {
            global::System.ArgumentNullException.ThrowIfNull(text);
            if (text.Contains('\0') || text.Contains('\n') || text.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(text));
            }
            global::System.ArgumentNullException.ThrowIfNull(secondary);
            if (secondary.Contains('\0') || secondary.Contains('\n') || secondary.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(secondary));
            }
            global::System.ArgumentNullException.ThrowIfNull(highlight);
            if (highlight.Contains('\0') || highlight.Contains('\n') || highlight.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(highlight));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{text}\n{secondary}\n{(masked ? 1 : 0)}\n{highlight}\n{(highlightPrefix ? 1 : 0)}");
        }
    }

    internal static class Kbd
    {
        internal const string Kind = "kbd";

        internal static string EncodeConfiguration(string keystroke, bool appearance, bool outline)
        {
            global::System.ArgumentNullException.ThrowIfNull(keystroke);
            if (keystroke.Contains('\0') || keystroke.Contains('\n') || keystroke.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(keystroke));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{keystroke}\n{(appearance ? 1 : 0)}\n{(outline ? 1 : 0)}");
        }
    }

    internal static class Link
    {
        internal const string Kind = "link";
        internal const ushort EventClicked = 1;

        internal static string EncodeConfiguration(string href, ulong clickedEvent)
        {
            global::System.ArgumentNullException.ThrowIfNull(href);
            if (href.Contains('\0') || href.Contains('\n') || href.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(href));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{href}\n{clickedEvent}");
        }
    }

    internal static class Avatar
    {
        internal const string Kind = "avatar";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, string name)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(name);
            if (name.Contains('\0') || name.Contains('\n') || name.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(name));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{name}");
        }
    }

    internal static class ShimmerText
    {
        internal const string Kind = "shimmer_text";

        internal static string EncodeConfiguration(string text, uint durationMs, bool reverse, bool once, string color)
        {
            global::System.ArgumentNullException.ThrowIfNull(text);
            if (text.Contains('\0') || text.Contains('\n') || text.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(text));
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{text}\n{durationMs}\n{(reverse ? 1 : 0)}\n{(once ? 1 : 0)}\n{color}");
        }
    }

    internal static class Switch
    {
        internal const string Kind = "switch";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool @checked, bool disabled, string label, string accessibilityLabel, string tooltip, string color, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            global::System.ArgumentNullException.ThrowIfNull(tooltip);
            if (tooltip.Contains('\0') || tooltip.Contains('\n') || tooltip.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(tooltip));
            }
            global::System.ArgumentNullException.ThrowIfNull(color);
            if (color.Contains('\0') || color.Contains('\n') || color.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(color));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(@checked ? 1 : 0)}\n{(disabled ? 1 : 0)}\n{label}\n{accessibilityLabel}\n{tooltip}\n{color}\n{changedEvent}");
        }
    }

    internal static class Checkbox
    {
        internal const string Kind = "checkbox";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool @checked, bool disabled, string label, string accessibilityLabel, string tooltip, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            global::System.ArgumentNullException.ThrowIfNull(tooltip);
            if (tooltip.Contains('\0') || tooltip.Contains('\n') || tooltip.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(tooltip));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(@checked ? 1 : 0)}\n{(disabled ? 1 : 0)}\n{label}\n{accessibilityLabel}\n{tooltip}\n{changedEvent}");
        }
    }

    internal static class Radio
    {
        internal const string Kind = "radio";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool @checked, bool disabled, string label, string accessibilityLabel, string tooltip, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(accessibilityLabel);
            if (accessibilityLabel.Contains('\0') || accessibilityLabel.Contains('\n') || accessibilityLabel.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(accessibilityLabel));
            }
            global::System.ArgumentNullException.ThrowIfNull(tooltip);
            if (tooltip.Contains('\0') || tooltip.Contains('\n') || tooltip.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(tooltip));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(@checked ? 1 : 0)}\n{(disabled ? 1 : 0)}\n{label}\n{accessibilityLabel}\n{tooltip}\n{changedEvent}");
        }
    }

    internal static class Toggle
    {
        internal const string Kind = "toggle";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal enum Variant
        {
            Ghost,
            Outline,
        }

        internal static string EncodeConfiguration(Size size, Variant variant, bool @checked, bool disabled, string label, string tooltip, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            var variantValue = variant switch
            {
                Variant.Ghost => "ghost",
                Variant.Outline => "outline",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            global::System.ArgumentNullException.ThrowIfNull(tooltip);
            if (tooltip.Contains('\0') || tooltip.Contains('\n') || tooltip.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(tooltip));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{variantValue}\n{(@checked ? 1 : 0)}\n{(disabled ? 1 : 0)}\n{label}\n{tooltip}\n{changedEvent}");
        }
    }

    internal static class Pagination
    {
        internal const string Kind = "pagination";
        internal const ushort EventChanged = 1;

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, uint currentPage, uint totalPages, uint visiblePages, bool disabled, bool compact, ulong changedEvent)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{currentPage}\n{totalPages}\n{visiblePages}\n{(disabled ? 1 : 0)}\n{(compact ? 1 : 0)}\n{changedEvent}");
        }
    }

    internal static class Collapsible
    {
        internal const string Kind = "collapsible";

        internal static string EncodeConfiguration(bool open, bool animated)
        {
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{(open ? 1 : 0)}\n{(animated ? 1 : 0)}");
        }
    }

    internal static class Empty
    {
        internal const string Kind = "empty";

        internal enum MediaVariant
        {
            Default,
            Icon,
        }

        internal static string EncodeConfiguration(MediaVariant mediaVariant, string title, string description, bool hasMedia, bool hasContent, bool hasFooter)
        {
            var mediaVariantValue = mediaVariant switch
            {
                MediaVariant.Default => "default",
                MediaVariant.Icon => "icon",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(mediaVariant)),
            };
            global::System.ArgumentNullException.ThrowIfNull(title);
            if (title.Contains('\0') || title.Contains('\n') || title.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(title));
            }
            global::System.ArgumentNullException.ThrowIfNull(description);
            if (description.Contains('\0') || description.Contains('\n') || description.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(description));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{mediaVariantValue}\n{title}\n{description}\n{(hasMedia ? 1 : 0)}\n{(hasContent ? 1 : 0)}\n{(hasFooter ? 1 : 0)}");
        }
    }

    internal static class Toolbar
    {
        internal const string Kind = "toolbar";

        internal enum Size
        {
            Xsmall,
            Small,
            Medium,
            Large,
        }

        internal static string EncodeConfiguration(Size size, bool disabled)
        {
            var sizeValue = size switch
            {
                Size.Xsmall => "xsmall",
                Size.Small => "small",
                Size.Medium => "medium",
                Size.Large => "large",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(size)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{sizeValue}\n{(disabled ? 1 : 0)}");
        }
    }

    internal static class ToolbarGroup
    {
        internal const string Kind = "toolbar_group";

        internal static string EncodeConfiguration(string label)
        {
            global::System.ArgumentNullException.ThrowIfNull(label);
            if (label.Contains('\0') || label.Contains('\n') || label.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(label));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{label}");
        }
    }

    internal static class StatusBar
    {
        internal const string Kind = "status_bar";

        internal static string EncodeConfiguration(bool hasLeft, bool hasCenter, bool hasRight)
        {
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{(hasLeft ? 1 : 0)}\n{(hasCenter ? 1 : 0)}\n{(hasRight ? 1 : 0)}");
        }
    }

    internal static class Bubble
    {
        internal const string Kind = "bubble";

        internal enum Variant
        {
            Filled,
            Secondary,
            Muted,
            Tinted,
            Outline,
            Ghost,
            Destructive,
        }

        internal enum Alignment
        {
            Inherit,
            Start,
            End,
        }

        internal enum ReactionSide
        {
            Top,
            Bottom,
        }

        internal enum ReactionAlignment
        {
            Start,
            End,
        }

        internal static string EncodeConfiguration(Variant variant, Alignment alignment, ReactionSide reactionSide, ReactionAlignment reactionAlignment, bool hasContent, bool hasReactions)
        {
            var variantValue = variant switch
            {
                Variant.Filled => "filled",
                Variant.Secondary => "secondary",
                Variant.Muted => "muted",
                Variant.Tinted => "tinted",
                Variant.Outline => "outline",
                Variant.Ghost => "ghost",
                Variant.Destructive => "destructive",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            var alignmentValue = alignment switch
            {
                Alignment.Inherit => "inherit",
                Alignment.Start => "start",
                Alignment.End => "end",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(alignment)),
            };
            var reactionSideValue = reactionSide switch
            {
                ReactionSide.Top => "top",
                ReactionSide.Bottom => "bottom",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(reactionSide)),
            };
            var reactionAlignmentValue = reactionAlignment switch
            {
                ReactionAlignment.Start => "start",
                ReactionAlignment.End => "end",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(reactionAlignment)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{variantValue}\n{alignmentValue}\n{reactionSideValue}\n{reactionAlignmentValue}\n{(hasContent ? 1 : 0)}\n{(hasReactions ? 1 : 0)}");
        }
    }

    internal static class BubbleGroup
    {
        internal const string Kind = "bubble_group";

        internal static string EncodeConfiguration()
        {
            return string.Empty;
        }
    }

    internal static class Message
    {
        internal const string Kind = "message";

        internal enum Alignment
        {
            Start,
            End,
        }

        internal static string EncodeConfiguration(Alignment alignment, bool accessibleListItem, bool contentHasGhostSurface, bool hasAvatar, bool hasHeader, bool hasContent, bool hasFooter)
        {
            var alignmentValue = alignment switch
            {
                Alignment.Start => "start",
                Alignment.End => "end",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(alignment)),
            };
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{alignmentValue}\n{(accessibleListItem ? 1 : 0)}\n{(contentHasGhostSurface ? 1 : 0)}\n{(hasAvatar ? 1 : 0)}\n{(hasHeader ? 1 : 0)}\n{(hasContent ? 1 : 0)}\n{(hasFooter ? 1 : 0)}");
        }
    }

    internal static class MessageGroup
    {
        internal const string Kind = "message_group";

        internal static string EncodeConfiguration()
        {
            return string.Empty;
        }
    }

    internal static class Marker
    {
        internal const string Kind = "marker";

        internal enum Variant
        {
            Plain,
            Separator,
            Border,
        }

        internal enum Alignment
        {
            Inherit,
            Start,
            Center,
            End,
        }

        internal enum LoadingStyle
        {
            Spinner,
            Shimmer,
        }

        internal static string EncodeConfiguration(Variant variant, Alignment alignment, bool loading, LoadingStyle loadingStyle, bool statusRole, string text, bool hasIcon, bool hasExtra)
        {
            var variantValue = variant switch
            {
                Variant.Plain => "plain",
                Variant.Separator => "separator",
                Variant.Border => "border",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(variant)),
            };
            var alignmentValue = alignment switch
            {
                Alignment.Inherit => "inherit",
                Alignment.Start => "start",
                Alignment.Center => "center",
                Alignment.End => "end",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(alignment)),
            };
            var loadingStyleValue = loadingStyle switch
            {
                LoadingStyle.Spinner => "spinner",
                LoadingStyle.Shimmer => "shimmer",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(loadingStyle)),
            };
            global::System.ArgumentNullException.ThrowIfNull(text);
            if (text.Contains('\0') || text.Contains('\n') || text.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(text));
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{variantValue}\n{alignmentValue}\n{(loading ? 1 : 0)}\n{loadingStyleValue}\n{(statusRole ? 1 : 0)}\n{text}\n{(hasIcon ? 1 : 0)}\n{(hasExtra ? 1 : 0)}");
        }
    }
}
