// @generated by Gpui.Bindings.Generator. Do not edit.

namespace Gpui.Editor;

internal static class EditorSchema
{
    internal const string ExtensionId = "gpui.net.editor";
    internal const uint SchemaVersion = 4u;
    internal const ulong SchemaHash = 0x98BDD874D7123B33UL;

    internal static class Editor
    {
        internal const string Kind = "editor";
        internal const uint FlagDisabled = 1u << 0;
        internal const uint FlagReadOnly = 1u << 1;
        internal const uint FlagLineNumbers = 1u << 2;
        internal const uint FlagFolding = 1u << 3;
        internal const uint FlagShowWhitespace = 1u << 4;
        internal const ushort CommandBootstrap = 1;
        internal const ushort EventChanged = 1;
        internal const uint KnownFlags =
            FlagDisabled
            | FlagReadOnly
            | FlagLineNumbers
            | FlagFolding
            | FlagShowWhitespace;
    }
}
