// @generated by Gpui.Bindings.Generator. Do not edit.

namespace Gpui.Editor;

internal static class EditorSchema
{
    internal const string ExtensionId = "gpui.net.editor";
    internal const uint SchemaVersion = 6u;
    internal const ulong SchemaHash = 0x5441198555E07694UL;

    internal static class Editor
    {
        internal const string Kind = "editor";
        internal const uint FlagDisabled = 1u << 0;
        internal const uint FlagReadOnly = 1u << 1;
        internal const uint FlagLineNumbers = 1u << 2;
        internal const uint FlagFolding = 1u << 3;
        internal const uint FlagShowWhitespace = 1u << 4;
        internal const ushort CommandBootstrap = 1;
        internal const ushort CommandFocus = 2;
        internal const ushort CommandSetSelection = 3;
        internal const ushort CommandReplaceDocument = 4;
        internal const ushort CommandApplyEdit = 5;
        internal const ushort EventChanged = 1;
        internal const ushort EventCommandRejected = 2;
        internal const uint KnownFlags =
            FlagDisabled
            | FlagReadOnly
            | FlagLineNumbers
            | FlagFolding
            | FlagShowWhitespace;

        internal static string EncodeConfiguration(uint flags, string language, ulong changedEvent, ulong commandRejectedEvent, float lineNumberWidth)
        {
            if ((flags & ~KnownFlags) != 0)
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(flags), "Unknown extension flags were supplied.");
            }
            global::System.ArgumentNullException.ThrowIfNull(language);
            if (language.Contains('\0') || language.Contains('\n') || language.Contains('\r'))
            {
                throw new global::System.ArgumentException("Extension configuration strings cannot contain NUL or newline characters.", nameof(language));
            }
            if (!float.IsFinite(lineNumberWidth))
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(lineNumberWidth), "Extension configuration numbers must be finite.");
            }
            return global::System.String.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{flags}\n{language}\n{changedEvent}\n{commandRejectedEvent}\n{lineNumberWidth}");
        }
    }
}
