<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Gpui.Tests" />
        <ProjectReference Include="../../src/Gpui/Gpui.csproj" />
        <ProjectReference
            Include="../../src/Gpui.Generators/Gpui.Generators.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Assets/cover.svg">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
